CONTRIBUTING.md
LICENSE
README.md
rclpy/CMakeLists.txt
rclpy/__init__.py.in
rclpy/package.xml
rclpy/rclpy/__init__.py
rclpy/rclpy/node.py
rclpy/rclpy/publisher.py
rclpy/rclpy/qos.py
rclpy/rclpy/subscription.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_talker_listener.py

This is an initial implementation of `rclpy`.
Depends on https://github.com/ros2/rosidl/pull/73

Initial implementation

---

rclpy/CMakeLists.txt

Skip tests if no valid typesupport found

---

rclpy/src/rclpy/_rclpy.c

Connects to ros2/rcl#27
We'll delay implementing Python services until C services are merged. This is necessary for the C services branch to compile.

wait_set API change

---

rclpy/test/test_select_rmw_implementation.py

remove hardcoded map from implementation identifier test

---

rclpy/package.xml
rclpy/test/talker_nested.py
rclpy/test/test_talker_listener.py

Connects to ros2/rosidl#96
This PR allows to test nested messages added in https://github.com/ros2/rosidl/pull/113

extended test to cover nested messages

---

rclpy/rclpy/__init__.py

Follow up to https://github.com/ros2/rclpy/pull/12

fix import order

---

rclpy/CMakeLists.txt

Connect to ament/ament_cmake#68

use CTest BUILD_TESTING

---

rclpy/package.xml
rclpy/test/talker_fixed_array.py
rclpy/test/talker_nested_array.py
rclpy/test/talker_unbounded_array.py
rclpy/test/test_talker_listener.py

Add testing for primitive arrays bounded or not + tests for nested messages arrays
Note: feature working but tests failing on windows because of underlying rclpy issues that should be addressed in a separate PR.
Connects to https://github.com/ros2/rosidl/issues/114

add tests for array

---

rclpy/test/talker_fixed_array.py
rclpy/test/talker_nested.py
rclpy/test/talker_nested_array.py
rclpy/test/talker_unbounded_array.py

This removes the now useless string initialization in test files
Connects to https://github.com/ros2/rclpy/issues/17
Relies on https://github.com/ros2/rclpy/pull/23

Fix null terminator

---

rclpy/CMakeLists.txt

Only merge after the switch to Xenial.

require Python 3.5

---

rclpy/CMakeLists.txt

Connect to ament/ament_cmake#72

require CMake 3.5

---

rclpy/rclpy/node.py

Connects to https://github.com/ros2/rclpy/issues/36

import type_support at subscriber/publisher creation time

---

rclpy/rclpy/impl/excepthook.py
rclpy/rclpy/impl/implementation_singleton.py
rclpy/rclpy/impl/rmw_implementation_tools.py

see https://github.com/ament/ament_lint/pull/61

(dev) comply with D213

---

rclpy/rclpy/impl/rmw_implementation_tools.py

choose FastRTPS as the default if available

---

rclpy/rclpy/__init__.py

fix indent

---

rclpy/src/rclpy/_rclpy.c

refactor mentionned in https://github.com/ros2/rclpy/pull/51#discussion_r88342583
Don't know where the right place to put the new macro would be ? a macros.h file ? on top of this file ?

use macro to limit code duplication

---

rclpy/src/rclpy/_rclpy.c

raise errors on argument mismatch rather than asserts. Also gives more descriptive error messages when asserts fail

Error handling

---

rclpy/rclpy/qos.py

Connects to https://github.com/ros2/rmw/issues/85

Rename QoS policies

---

rclpy/package.xml
rclpy/rclpy/node.py
rclpy/test/test_destruction.py

This PR:
* prevents user from setting/modifying the handle of a python node
* adds a bunch of tests for destruction of various node entities

Prevent null handle

---

rclpy/rclpy/impl/implementation_singleton.py
rclpy/rclpy/node.py
rclpy/rclpy/qos.py

Connects to ament/ament_lint#53

Comply with flake8 + flake8-import-order linters

---

rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_create_node.py

* [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2364)](http://ci.ros2.org/job/ci_linux/2364/)
* [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1819)](http://ci.ros2.org/job/ci_osx/1819/)
* [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2475)](http://ci.ros2.org/job/ci_windows/2475/)
Ready for review.

expose node name

---

rclpy/rclpy/__init__.py
rclpy/rclpy/node.py
rclpy/test/test_timer.py

* [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2399)](http://ci.ros2.org/job/ci_linux/2399/)

force using explicit kwargs

---

rclpy/rclpy/__init__.py
rclpy/src/rclpy/_rclpy.c

updates to support node namespace and new rcl API

---

rclpy/CMakeLists.txt
rclpy/package.xml
rclpy/src/rclpy/_rclpy.c

use string_array_t from c_utilities package

---

rclpy/src/rclpy/_rclpy.c

Connects to ros2/c_utilities#16

refactor to pass allocator to some rcl functions

---

rclpy/CMakeLists.txt
rclpy/package.xml
rclpy/src/rclpy/_rclpy.c

Connects to ros2/c_utilities#17
looks like this one was missing

rename {c_}utilities to rcutils

---

rclpy/src/rclpy/_rclpy.c

This is a follow on from #79. It pairs every ```convert_from_py``` call with a ```destroy_ros_message```. Running valgrind on a python subscriber (same test setup used in #79) yielded something like:
```
Before fix
==7972== LEAK SUMMARY:
==7972==    definitely lost: 709,984 bytes in 12,104 blocks
==7972==    indirectly lost: 1,232,986 bytes in 28,242 blocks
==7972==      possibly lost: 217,896 bytes in 348 blocks
==7972==    still reachable: 11,638,082 bytes in 28,306 blocks
==7972==         suppressed: 0 bytes in 0 blocks
==7972== Reachable blocks (those to which a pointer was found) are not shown.
```
After adding ```destroy_ros_message``` to ```rclpy_take``` (and others):
```
After fix
==23836== LEAK SUMMARY:
==23836==    definitely lost: 1,240 bytes in 23 blocks
==23836== …
```

Fixes memory leaks in python subscribers (and probably also python services)

---

rclpy/src/rclpy/_rclpy.c

string array takes allocator

---

rclpy/rclpy/__init__.py
rclpy/rclpy/client.py
rclpy/rclpy/node.py
rclpy/rclpy/topic_or_service_is_hidden.py
rclpy/rclpy/utilities.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_topic_or_service_is_hidden.py

Refactor get topic names and types

---

rclpy/src/rclpy/_rclpy.c

This goes together with ros2/rosidl#226.

check return code of convert functions

---

rclpy/rclpy/__init__.py
rclpy/test/test_init_shutdown.py

Raise NotInitializedException if rclpy has not been initialized

---

rclpy/rclpy/client.py
rclpy/rclpy/exceptions.py
rclpy/rclpy/publisher.py
rclpy/rclpy/qos.py
rclpy/rclpy/topic_or_service_is_hidden.py
rclpy/test/test_destruction.py
rclpy/test/test_init_shutdown.py
rclpy/test/test_timer.py

update style to satisfy new flake8 plugins

---

rclpy/src/rclpy/_rclpy.c

Same as #109 but for all other entities.

free all entities after fini

---

rclpy/src/rclpy/_rclpy.c

Same as #109 and #110 but for the qos profiles.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3165)](http://ci.ros2.org/job/ci_linux/3165/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=504)](http://ci.ros2.org/job/ci_linux-aarch64/504/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2522)](http://ci.ros2.org/job/ci_osx/2522/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3217)](http://ci.ros2.org/job/ci_windows/3217/)

free allocated qos profiles

---

rclpy/rclpy/__init__.py
rclpy/rclpy/client.py
rclpy/src/rclpy/_rclpy.c

add abilitiy to destroy guard conditions and destroy the sigint guard condition in spin_once

---

rclpy/src/rclpy/_rclpy.c

Fixes other aspects of #74.
Due to the extra `Py_INCREF` message instance were never collected.

fix ref count of messages

---

rclpy/rclpy/node.py

this refactors the type support checks and add a hint as of the reason it is failing

Improve type support error message

---

rclpy/src/rclpy/_rclpy.c

define doc string as in rclpy_logging module (follow up of https://github.com/ros2/rclpy/pull/102#discussion_r137093816)

define docstring as in logging module

---

rclpy/CMakeLists.txt

follow up of https://github.com/ros2/ros2/issues/362 revived during review of https://github.com/ros2/rclpy/pull/102#discussion_r137089299

default to c11

---

rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c

Follow up to address comments #104 that didn't make it into r2b3
connects to ros2/examples#184

Follow up to executor pull request

---

rclpy/CMakeLists.txt

python extras is required to build c extensions

---

rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_logging.c

Connect to ament/uncrustify#18.

update style to match latest uncrustify

---

rclpy/CMakeLists.txt
rclpy/package.xml

Connect to ament/ament_cmake#115.

use ament_cmake_pytest instead of ament_cmake_nose

---

rclpy/rclpy/impl/rcutils_logger.py
rclpy/rclpy/logging.py
rclpy/src/rclpy/_rclpy_logging.c
rclpy/test/test_logging.py
rclpy/test/test_node.py

Rename severity_thresold -> level

---

rclpy/src/rclpy/_rclpy.c

Change to align to the update of APIs `rmw_*_validation_result_string()`
Signed-off-by: Ethan Gao <ethan.gao@linux.intel.com>
Connects to ros2/rmw#130

adapt to the NULL removal from rmw result validation string

---

rclpy/src/rclpy/_rclpy.c

Update for changing rcl time primative to int64_t

---

rclpy/rclpy/utilities.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_utilities.py

Python support for remove command line arguments for ros2/rcl#219
Connects to ros2/rcl#219

Remove ros arguments

---

rclpy/package.xml

See: https://github.com/ros2/ros2/issues/519

claim maintainership

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

Backport #216 and #217 to bouncy branch
Connects to ros2/ros2#563

Bouncy patch2 backports

---

rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py

Add a new method to return a list of tuple to get both node names and namespaces.
Connects to ros2/rmw#142

Get node names and namespaces

---

rclpy/src/rclpy/_rclpy.c

I was getting a segfault parsing an invalid yaml file.

Avoid repeated fini-ing on failure to parse yaml params

---

rclpy/src/rclpy/_rclpy.c

use new error handling API from rcutils

---

rclpy/src/rclpy/_rclpy.c

Connects to ros2/rcl#335
Now the functions take an optional output index argument.

Update rcl_wait_set_add_* calls

---

rclpy/rclpy/action/client.py
rclpy/rclpy/action/server.py
rclpy/test/action/test_client.py
rclpy/test/action/test_server.py

Connected to [ros2/rosidl#334](https://github.com/ros2/rosidl/pull/334).

update to use separated action types

---

rclpy/rclpy/impl/rcutils_logger.py

add RcutilsLogger.warning

---

rclpy/CMakeLists.txt

Partially targets ros2/ros2#658

Using ament_target_dependencies where possible

---

rclpy/test/action/test_server.py

Connect to ros2/rosidl_python#35.

update tests to pass with numpy arrays

---

rclpy/src/rclpy/_rclpy.c

Cherry-pick of #288 for crystal patch release 4 ros2/ros2#668
closes #295

fix sigint guard condition's lifecycle bug (#288)

---

rclpy/CHANGELOG.rst
rclpy/package.xml

Opening for visibility, but immediately merging

Crystal patch 4 changelogs

---

rclpy/rclpy/__init__.py
rclpy/rclpy/executors.py
rclpy/test/test_executor.py

Fix #261.
Signed-off-by: vinnamkim <vinnam.kim@gmail.com>

Add timeout to executor_spin_until_future_complete

---

rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy_common/src/common.c

Just found these while debugging something else.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6718)](http://ci.ros2.org/job/ci_linux/6718/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=3032)](http://ci.ros2.org/job/ci_linux-aarch64/3032/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5521)](http://ci.ros2.org/job/ci_osx/5521/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=6548)](http://ci.ros2.org/job/ci_windows/6548/)

add missing error handling and cleanup

---

rclpy/test/test_executor.py

The threaded sleep waits *at least* 0.1 seconds from when it
is started, but there are no guarantees on when the other
thread gets scheduled in to finish the testing.  Thus, just
remove the various timing checks and just make sure that the
future completes; if it doesn't, it will get picked up by
the overall test timeout.
Fixes https://github.com/ros2/build_cop/issues/187
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6813)](http://ci.ros2.org/job/ci_linux/6813/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=3107)](http://ci.ros2.org/job/ci_linux-aarch64/3107/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5602 …

Remove most of the timing checks in test_executor

---

rclpy/src/rclpy/_rclpy.c

Signed-off-by: Michael Carroll <michael@openrobotics.org>

API updates for RMW preallocation work.

---

rclpy/rclpy/executors.py
rclpy/rclpy/waitable.py
rclpy/src/rclpy/_rclpy.c

Connects to ros2/rmw#171
Allows this package to build when new QoS APIs are checked in, but exposes none of the new functionality

QoS - Minimal change for build against new rcl API

---

rclpy/src/rclpy/_rclpy_signal_handler.c

This pull request rewrites `rclpy` signal handling code after `rclcpp`. Fixes #327.

Improve signal handling

---

rclpy/rclpy/node.py

Follow-up on #325; addressing this pending [comment](https://github.com/ros2/rclpy/pull/325#discussion_r280966366).

Setting automatic declaration for initial parameters to False.

---

rclpy/test/test_action_graph.py
rclpy/test/test_node.py

Update tests to include namespace in ROS types

---

rclpy/test/test_messages.py

Related to ros2/rosidl_python#57.

update test since unicode characters are allowed now

---

rclpy/rclpy/impl/__init__.py

Since documentation has moved.
Signed-off-by: Michael Carroll <michael@openrobotics.org>

Update troubleshooting reference to index.ros.org

---

rclpy/test/test_messages.py

destroy publishers after test is done

---

rclpy/rclpy/exceptions.py
rclpy/rclpy/node.py
rclpy/test/test_node.py

Closes #350.
See https://github.com/ros2/rclcpp/issues/728 for details and related discussion.

Enforcing parameter ranges.

---

rclpy/rclpy/node.py
rclpy/test/test_node.py

The modified signature allows to write code which is compatible with Crystal as well as Dashing (without getting a warning).
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7254)](http://ci.ros2.org/job/ci_linux/7254/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=3435)](http://ci.ros2.org/job/ci_linux-aarch64/3435/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5932)](http://ci.ros2.org/job/ci_osx/5932/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=7067)](http://ci.ros2.org/job/ci_windows/7067/)

consolidate create_publisher arguments

---

rclpy/CMakeLists.txt
rclpy/test/test_qos_event.py
rclpy/test/test_waitable.py

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7288)](http://ci.ros2.org/job/ci_linux/7288/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=3463)](http://ci.ros2.org/job/ci_linux-aarch64/3463/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5963)](http://ci.ros2.org/job/ci_osx/5963/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=7102)](http://ci.ros2.org/job/ci_windows/7102/)

Treat warnings as test failures and fix warnings

---

rclpy/rclpy/action/graph.py
rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c

Signed-off-by: Jacob Perron <jacob@openrobotics.org>

Fix API documentation related to ROS graph methods (#366)

---

rclpy/rclpy/qos.py

…ters
Signed-off-by: Abhinav <singhabhinav9051571833@gmail.com>
----
Edit(@ivanpauno):
Fixes https://github.com/ros2/rclpy/issues/371

Rename QoS*Policy enum's to *Policy

---

rclpy/rclpy/node.py
rclpy/test/test_node.py

Allowing parameter declaration without a given value.

---

rclpy/rclpy/node.py
rclpy/test/test_node.py

Adding get_parameters_by_prefix method to Node.

---

rclpy/rclpy/node.py
rclpy/test/test_node.py

Solves #391.
Signed-off-by: Juan Ignacio Ubeira <jubeira@ekumenlabs.com>

Adding ignore_override parameter to declare_parameter(s).

---

rclpy/src/rclpy/_rclpy.c

This is a backport of #370 for Dashing.
---
The short-term goal of this change is to enable the creation of a parameter YAML file which is applied to each node, regardless of node name or namespace.
Future work is to support all wildcard syntax in node names in parameter YAML files.

[Backport] Use params from node '/**' from parameter YAML file

---

rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_pycapsule.c
rclpy/src/rclpy/_rclpy_signal_handler.c

Replace 'NULL == ' with ! Signed-off-by: Geno117

---

rclpy/rclpy/clock.py

[backport] Missing raise to Dashing

---

rclpy/rclpy/time.py
rclpy/test/test_time.py

[backport] Time conversion fix to Dashing

---

rclpy/test/test_node.py
rclpy/test/test_utilities.py

Precisely what the title says.
Connected to https://github.com/ros2/rcl/pull/491.

Use of -r/--remap flags where appropriate.

---

rclpy/src/rclpy/_rclpy.c

Precisely what the title says. Follow-up after #415.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8092)](http://ci.ros2.org/job/ci_linux/8092/)

Fix _rclpy.c formatting.

---

rclpy/src/rclpy/_rclpy.c

The comment is no longer true.

Remove comment

---

rclpy/rclpy/parameter.py
rclpy/test/test_parameter.py

[Dashing] Accept tuples as parameter arrays.

---

rclpy/rclpy/action/client.py

Fixes #446
Signed-off-by: Werner Neubauer <werner.neubauer@siemens.com>

Send feedback callbacks properly in send_goal() of action client

---

rclpy/rclpy/action/client.py

[eloquent backport] Send feedback callbacks properly in send_goal() of action client (#451)

---

rclpy/rclpy/action/client.py

[dashing backport] Send feedback callbacks properly in send_goal() of action client (#451)

---

rclpy/rclpy/logging.py
rclpy/src/rclpy/_rclpy_logging.c
rclpy/test/test_logging.py

Connected to https://github.com/ros2/ros2cli/pull/390
As the title says, this PR provides an API to get the logging severity from a name in string format

Provide logging severity for string

---

rclpy/rclpy/action/client.py
rclpy/rclpy/action/server.py
rclpy/rclpy/node.py
rclpy/rclpy/qos_event.py

Resolves D401 errors with pydocstyle 5.0.0.
Contributes to closing https://github.com/ros2/build_cop/issues/255

Update constructor docstrings to use imperative mood.

---

rclpy/rclpy/task.py
rclpy/test/test_task.py

[Dashing] Future invokes done callbacks when done

---

rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_action.c
rclpy/src/rclpy_common/include/rclpy_common/common.h
rclpy/src/rclpy_common/src/common.c

CI testing rclpy:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8983)](http://ci.ros2.org/job/ci_linux/8983/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4751)](http://ci.ros2.org/job/ci_linux-aarch64/4751/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7355)](http://ci.ros2.org/job/ci_osx/7355/)
* Windows [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8921)](https://ci.ros2.org/job/ci_windows/8921/)

Move logic for getting type support into a common function

---

rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_action.c
rclpy/src/rclpy/_rclpy_logging.c
rclpy/src/rclpy/_rclpy_pycapsule.c
rclpy/src/rclpy/_rclpy_qos_event.c
rclpy/src/rclpy/_rclpy_signal_handler.c
rclpy/src/rclpy_common/src/common.c

Style update to match the ROS 2 development guide and pass with the updated linter configuration from ament/ament_lint#210.

code style only: wrap after open parenthesis if not in one line

---

rclpy/src/rclpy_common/src/common.c

See https://github.com/ros2/rmw/pull/196.

Rename rmw_topic_endpoint_info_array count to size

---

rclpy/rclpy/utilities.py

Fixed flake8 test https://github.com/ros2/rclpy/pull/517#discussion_r387252972

[rclpy] fixed flake8 test utilities.py

---

rclpy/rclpy/utilities.py

Same as https://github.com/ros2/rmw/pull/199#pullrequestreview-370664368.

add env var to filter available RMW implementations

---

rclpy/rclpy/publisher.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_messages.py

- add `rclpy_publish_raw` to `_rclpy.c`
- add `publish_raw` to `publisher.py`
- add tests
- fixes [496](https://github.com/ros2/rclpy/issues/496)

Add capability to publish serialized messages

---

rclpy/test/test_qos_event.py

Maybe fix https://github.com/ros2/rmw_cyclonedds/issues/117
Signed-off-by: Dan Rose <dan@digilabs.io>

Don't persist node and context between tests

---

rclpy/src/rclpy/_rclpy.c

update includes to use non-entry point headers from detail subdir

---

rclpy/src/rclpy/_rclpy.c
rclpy/test/resources/test_node/test_parameters.yaml

Connected to https://github.com/ros2/rclcpp/issues/953.

Enforce a precedence for wildcard matching in parameter overrides.

---

rclpy/test/test_logging_rosout.py

Signed-off-by: Barry Xu <Barry.Xu@sony.com>

Fix bug that not to get expected data because use less timeout

---

rclpy/rclpy/executors.py

Precisely what the title says. Came across this apparent omission while working on https://github.com/ros2/ros2cli/pull/521. Calling `Executor.shutdown` from another thread would often cause `Executor.spin` to throw when `Executor.wait_for_ready_callbacks` returned `None`.
```sh
Traceback (most recent call last):
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/home/michel/Workspaces/focal_ros2_ws/install/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 284, in spin
self.spin_once()
File "/home/michel/Workspaces/focal_ros2_ws/install/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 680, in spin_once
handler, entity, node = …
```

Ensure executors' spinning API handles shutdown properly.

---

rclpy/rclpy/action/client.py
rclpy/rclpy/node.py

Noticed these when attempting to generate docs.

Fix docstrings

---

README.md

Fixes https://github.com/ros2/rclpy/issues/561

Improve documentation on building API documentation

---

rclpy/CMakeLists.txt
rclpy/rclpy/publisher.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_publisher.py

The method internally call the c function [`rcl_publisher_get_topic_name`](https://github.com/ros2/rcl/blob/master/rcl/include/rcl/publisher.h#L456) in rcl library.

Add resolved_name() method to publisher

---

rclpy/src/rclpy/_rclpy.c

add `rcutils/macros.h` that configures `RCUTILS_STRINGIFY`, see discussion on https://github.com/ros2/ros2/issues/942
Signed-off-by: claireyywang <22240514+claireyywang@users.noreply.github.com>

add missing macro 

---

rclpy/rclpy/qos_event.py
rclpy/src/rclpy/_rclpy_qos_event.c

See https://github.com/ros2/rmw/issues/226.

Add message lost subscription event

---

rclpy/CMakeLists.txt
rclpy/rclpy/subscription.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_subscription.py

[Foxy backport] Add `topic_name` property to Subscription (#571)

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

[Foxy Backport] Fix executor behavior on shutdown (#574)

---

rclpy/rclpy/impl/__init__.py

Since the page was moved in ros2/ros2_documentation#700.

fix moved troubleshooting url

---

rclpy/rclpy/impl/__init__.py

Follow up of #579. Also use f-string.

wrap lines to shorten line length

---

rclpy/CMakeLists.txt
rclpy/rclpy/publisher.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_publisher.py

[Foxy backport] Backport `Publisher.topic_name` #568

---

rclpy/rclpy/impl/__init__.py

[backport eloquent] fix moved troubleshooting url

---

rclpy/rclpy/impl/__init__.py

[backport dashing] improve error message if rclpy C extensions are not found

---

rclpy/rclpy/impl/__init__.py

Backports #579, #580, and #586.

[backport foxy] fix/improve error message failing to load C extension

---

rclpy/rclpy/impl/__init__.py

[backport dashing] fix moved troubleshooting url

---

rclpy/rclpy/impl/__init__.py
rclpy/rclpy/impl/implementation_singleton.py
rclpy/test/__init__.py

Depends on https://github.com/ros2/rpyutils/pull/4
Related to https://github.com/ros2/rosbag2/issues/445
Uses the new function that has been moved to rpyutils

Use the rpyutils shared import_c_library function.

---

rclpy/rclpy/node.py

See: http://docs.ros2.org/latest/api/rclpy/api/node.html
Signed-off-by: Dereck Wonnacott <dereck.wonnacott@havalus.com>

PARAM_REL_TOL comment was incorrect in the api doc.

---

rclpy/rclpy/time_source.py

See https://github.com/ros2/rclcpp/pull/1312.

Use best effort, keep last, history depth 1 QoS Profile for '/clock' subscriptions

---

rclpy/rclpy/executors.py

[foxy] MultiThreadedExecutor spin_until_future complete should not continue waiting when the future is done (#605)

---

rclpy/src/rclpy/_rclpy.c

address https://github.com/ros2/rclpy/issues/643
Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>
Co-authored-by: Chen Lihui <lihui.chen@sony.com>

memory leak (#643)

---

rclpy/src/rclpy/_rclpy.c

https://github.com/ros2/rclpy/issues/643 backport for foxy
Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>
Co-authored-by: Chen Lihui <lihui.chen@sony.com>

[foxy] memory leak (#643)

---

rclpy/test/test_rate.py

This ensures that we don't get an exception in the extra
thread, which as of pytest 6.2.0 also causes an exception in
the main program.

[Foxy backport]: Make sure to catch the ROSInterruptException when calling rate.sleep. (#649)

---

rclpy/docs/source/conf.py
rclpy/rclpy/qos.py

Forward port of #653 (from Foxy).
I plan to keep the two commits separate when merging.

Document qos_profile_* constants

---

rclpy/CMakeLists.txt
rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/service_info.cpp
rclpy/src/rclpy/service_info.hpp

Part of #665
Converts:
* rclpy_service_info_get_sequence_number
* rclpy_service_info_get_source_timestamp
* rclpy_service_info_get_received_timestamp

Convert service info functions to pybind11

---

rclpy/CMakeLists.txt
rclpy/rclpy/node.py
rclpy/rclpy/type_support.py
rclpy/test/test_node.py
rclpy/test/test_type_support.py
rclpy/test/test_waitable.py

Fixes https://github.com/ros2/rclpy/issues/622.
I will check if something similar can be done for actions and implement it either as an extra commit here or in a new PR.

Better checks for valid msg and srv types

---

rclpy/CMakeLists.txt
rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_action.cpp
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/client.cpp
rclpy/src/rclpy/publisher.cpp
rclpy/src/rclpy/serialization.cpp
rclpy/src/rclpy/serialization.hpp
rclpy/src/rclpy/service.cpp
rclpy/src/rclpy/subscription.cpp
rclpy/src/rclpy/wait_set.cpp
rclpy/src/rclpy_common/include/rclpy_common/common.h

Convert serialize/deserialize to pybind11

---

rclpy/src/rclpy/_rclpy_action.cpp

I found this when running tests under valgrind.

Fix bug in unique_ptr type argument

---

rclpy/rclpy/executors.py
rclpy/rclpy/timer.py
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/timer.cpp
rclpy/src/rclpy/timer.hpp
rclpy/src/rclpy/wait_set.cpp
rclpy/src/rclpy/wait_set.hpp
rclpy/test/test_destruction.py
rclpy/test/test_waitable.py

This converts the Timer functions to a C++ class. 

Convert Timer to use a C++ Class

---

rclpy/rclpy/executors.py
rclpy/rclpy/node.py
rclpy/rclpy/service.py
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/service.cpp
rclpy/src/rclpy/service.hpp
rclpy/src/rclpy/wait_set.cpp
rclpy/src/rclpy/wait_set.hpp
rclpy/test/test_client.py
rclpy/test/test_destruction.py
rclpy/test/test_waitable.py

This converts the Service functions to a C++ class. 

Convert Service to use C++ Class

---

rclpy/rclpy/action/server.py
rclpy/rclpy/clock.py
rclpy/rclpy/timer.py
rclpy/src/rclpy/_rclpy_action.cpp
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/clock.cpp
rclpy/src/rclpy/clock.hpp
rclpy/src/rclpy/timer.cpp
rclpy/src/rclpy/timer.hpp
rclpy/test/test_waitable.py

This PR builds on top of this other PR https://github.com/ros2/rclpy/pull/745
This converts the Clock functions to a C++ class. 

Convert Clock to use a C++ Class

---

rclpy/CMakeLists.txt
rclpy/rclpy/action/server.py
rclpy/src/rclpy/_rclpy_action.cpp
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/action_goal_handle.cpp
rclpy/src/rclpy/action_goal_handle.hpp

Use py::class_ for rcl_action_goal_handle_t

---

rclpy/CMakeLists.txt
rclpy/rclpy/action/client.py
rclpy/rclpy/context.py
rclpy/src/rclpy/_rclpy_action.cpp
rclpy/src/rclpy/action_client.cpp
rclpy/src/rclpy/action_client.hpp
rclpy/src/rclpy/utils.cpp
rclpy/src/rclpy/utils.hpp

This converts the ActionClient functions to a C++ class. 

Convert ActionClient to use C++ classes

---

rclpy/src/rclpy/_rclpy_action.cpp
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/action_client.hpp
rclpy/src/rclpy/action_server.cpp
rclpy/src/rclpy/action_server.hpp
rclpy/src/rclpy/clock.hpp
rclpy/src/rclpy/guard_condition.hpp
rclpy/src/rclpy/publisher.hpp
rclpy/src/rclpy/service.hpp
rclpy/src/rclpy/subscription.hpp
rclpy/src/rclpy/timer.hpp
rclpy/src/rclpy/wait_set.hpp

related with the post-merge comments in this PR https://github.com/ros2/rclpy/pull/766
- use of `append_rcl_error`
- improved documentation

Pybind11 actionserver nitpicks and docblock improvements

---

rclpy/rclpy/impl/rcutils_logger.py

An attempt to solve https://github.com/ros2/rclpy/issues/775.

Break log function execution ASAP if configured severity is too high

---

rclpy/rclpy/action/server.py

[galactic] reject cancel request if failed to transit to CANCEL_GOAL state. (#791)

---

rclpy/rclpy/action/server.py

[foxy] reject cancel request if failed to transit to CANCEL_GOAL state. (#791)

---

rclpy/rclpy/exceptions.py
rclpy/rclpy/node.py
rclpy/test/test_node.py

[galactic] Allow declaring uninitialized parameters (#798)

---

rclpy/test/test_subscription.py

Signed-off-by: Shane Loretz <sloretz@openrobotics.org>

Remove unused function make_mock_subscription

---

rclpy/src/rclpy/signal_handler.cpp

Addresses https://github.com/ros2/rclpy/pull/830#issuecomment-957918665.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=15566)](http://ci.ros2.org/job/ci_linux/15566/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=10250)](http://ci.ros2.org/job/ci_linux-aarch64/10250/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=13234)](http://ci.ros2.org/job/ci_osx/13234/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15781)](http://ci.ros2.org/job/ci_windows/15781/)

Shutdown asynchronously when sigint is received

---

rclpy/rclpy/node.py
rclpy/rclpy/parameter.py

Fixes https://github.com/ros2/ros2/issues/1173.
Fixes https://github.com/ros2/rclpy/issues/829.

Fix automatically declared parameters descriptor type

---

rclpy/src/rclpy/action_server.cpp
rclpy/src/rclpy/graph.cpp
rclpy/src/rclpy/node.cpp
rclpy/src/rclpy/signal_handler.cpp
rclpy/src/rclpy/utils.cpp

Relates to https://github.com/ament/ament_lint/pull/324

Fix include order for cpplint

---

rclpy/src/rclpy/_rclpy.c

to fix https://github.com/ros2/rclpy/issues/897
Signed-off-by: Chen Lihui <lihui.chen@sony.com>

[Foxy] fix memory leak for serialization

---

rclpy/rclpy/action/client.py
rclpy/test/test_action_client.py

address https://github.com/ros2/rclpy/issues/921

remove feedback callback when the goal has been completed.

---

rclpy/src/rclpy/context.cpp
rclpy/test/test_init_shutdown.py

address https://github.com/ros2/rclpy/issues/937

check if the context is already shutdown.

---

rclpy/rclpy/executors.py
rclpy/rclpy/node.py
rclpy/test/test_client.py

addresses https://github.com/ros2/rclpy/issues/983

Raise user handler exception in MultiThreadedExecutor.

---

rclpy/src/rclpy/node.cpp
rclpy/test/resources/test_node/complicated_wildcards.yaml
rclpy/test/resources/test_node/params_by_order.yaml
rclpy/test/resources/test_node/wildcards.yaml
rclpy/test/test_node.py

to address https://github.com/ros2/rclcpp/pull/1839#issuecomment-1208171350

support wildcard matching for params file

---

rclpy/src/rclpy/node.cpp

related to https://github.com/ros2/rclpy/pull/1003
Signed-off-by: Chen Lihui <lihui.chen@sony.com>

resolve conflict

---

rclpy/rclpy/executors.py

address https://github.com/ros2/rclpy/issues/1000

Waitable should check callback_group if it can be executed.

---

rclpy/rclpy/executors.py
rclpy/rclpy/node.py

This reverts commit 6c0847a70df2a359c28ffae7e49ece2e62c1794d.

Revert "Raise user handler exception in MultiThreadedExecutor. (#984)"

---

rclpy/rclpy/node.py

Mostly for consistency and to fix some typos.

Update the rclpy method documentation.

---

rclpy/rclpy/utilities.py

This adds type annotations and doc strings to the functions in `rclpy.utilities`. I didn't change any behavior of the functions (maybe this is backportable?). I did remove a couple unnecessary `return` statements ( they were returning the value from another function that itself always returns `None`). 
Here's how it looks now

Improve documentation in rclpy.utilities

---

rclpy/CMakeLists.txt
rclpy/rclpy/parameter_service.py
rclpy/test/test_parameter_client.py

Deal with ParameterUninitializedException for parameter service

---

rclpy/rclpy/qos_overriding_options.py
rclpy/test/test_qos_overriding_options.py

address  https://github.com/ros2/rclpy/issues/1047

decorator should not be callable.

---

rclpy/rclpy/qos.py

Minor addition, will be used in https://github.com/ros2/ros2cli/pull/788.

Add default preset qos profile

---

rclpy/CMakeLists.txt
rclpy/rclpy/impl/rcutils_logger.py
rclpy/src/rclpy/_rclpy_logging.cpp
rclpy/test/test_rosout_subscription.py

rely on https://github.com/ros2/rcl/pull/921

to create a sublogger while getting child of Logger

---

rclpy/src/rclpy/service_introspection.cpp
rclpy/src/rclpy/service_introspection.hpp

This is compatible with pybind11 2.4.3, which is what is in Ubuntu 20.04.

Switch to using module instead of module_

---

rclpy/rclpy/parameter.py
rclpy/test/test_parameter.py

Allow space or empty strings when using ros2 param set

---

rclpy/rclpy/duration.py
rclpy/rclpy/time.py
rclpy/test/test_time.py

Fixes #952.
Ought to be back-ported to Galactic and Foxy as well.

Fix Time and Duration raising exception when compared to another type

---

rclpy/rclpy/context.py
rclpy/test/test_context.py

Turn Context into a ContextManager

---

rclpy/rclpy/__init__.py
rclpy/rclpy/executors.py
rclpy/rclpy/node.py

I combed through all 154 matches of = None in the codebase and made Optional things, well, `Optional`
Signed-off-by: Brian Chen <brian.chen@openrobotics.org>

Make Optional things Optional

---

rclpy/CMakeLists.txt
rclpy/rclpy/node.py
rclpy/rclpy/type_description_service.py
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/type_description_service.cpp
rclpy/src/rclpy/type_description_service.hpp
rclpy/test/test_node.py

Backports #1139 to Iron
Depends on ros2/rcl#1082
Linked with ros2/ros2cli#839
* Add get_type_description service

[Iron] get_type_description service (backport #1139)

---

rclpy/rclpy/time_source.py

Addresses https://github.com/ros2/rclcpp/issues/2253 in `rclpy`, [matching PR in rclcpp](https://github.com/ros2/rclcpp/pull/2257)

Store time source clocks in a set

---

rclpy/rclpy/executors.py

The rclpy executor collects all of the entities in one pass, then creates async tasks for each of the ready ones and attempts to "take" and execute them.  If one of those entities is destroyed after the collection but before we attempt to "take" it, then we can end up attempting to __enter__ a Destroyable-derived class that has already been destroyed. The Destroyable will then raise an InvalidHandle error.
Fix this by explicitly catching the InvalidHandle error that can be raised in all of the Destroyable-derived entities. If we do catch it, then we actually let the machinery continue but tell things to just not execute; in a subsequent executor iteration, the entity will be destroyed and hence not looked at anymore.  This seems to fix the race in my testing.
Fixes #1147 
@sloretz I'm …

Fix an inherent race in execution vs. destruction.

---

rclpy/rclpy/type_description_service.py
rclpy/test/test_type_description_service.py

It actually just crashed when called, not sure how I let that through.
This fixes the issue and adds a unit test to try out the service.
Will need backport to Iron.

Fix get_type_description service bug and add a unit test

---

rclpy/CMakeLists.txt
rclpy/rclpy/client.py
rclpy/rclpy/node.py
rclpy/rclpy/service.py
rclpy/src/rclpy/client.cpp
rclpy/src/rclpy/client.hpp
rclpy/test/test_client.py
rclpy/test/test_service.py

Address #954  
`srv_name` in service & client save real service name (remapped name).

Support to get remapped service name

---

rclpy/rclpy/type_description_service.py
rclpy/test/test_type_description_service.py

Backports #1155 to Iron
* Fix `get_type_description` service bug and add a unit test

[iron] Fix get_type_description service bug and add a unit test (backport #1155)

---

rclpy/src/rclpy/node.cpp

address https://github.com/ros2/rclcpp/issues/2147

Decouple rosout publisher init from node init.

---

rclpy/rclpy/__init__.py
rclpy/rclpy/clock.py
rclpy/rclpy/node.py

Fixed new occurrences to continue efforts of #974
Signed-off-by: antonkesy@gmail.com

making optional things Optional

---

rclpy/rclpy/wait_for_message.py

Fix to https://github.com/ros2/rclpy/issues/1179 (backport)

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

Fix conflicts for mergify/bp/iron/pr-1165

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

Fix conflicts for mergify/bp/humble/pr-1165

---

rclpy/rclpy/__init__.py
rclpy/test/test_context.py
rclpy/test/test_init_shutdown.py

address https://github.com/ros2/rclpy/issues/190

call ok() to see if rclpy and context is initialized.

---

rclpy/rclpy/client.py
rclpy/rclpy/publisher.py
rclpy/rclpy/service.py

follow up for https://github.com/ros2/rclpy/pull/1204

Add doc-string warnings for destroy methods for services.

---

rclpy/rclpy/node.py
rclpy/test/test_node.py

address part of https://github.com/ros2/ros2/issues/1517

forbid parameter to be declared statically without initialization.

---

rclpy/package.xml

via issue: https://github.com/lopsided98/nix-ros-overlay/issues/367#issuecomment-1982036281

added python3-yaml  to rclpy

---

rclpy/rclpy/expand_topic_name.py
rclpy/rclpy/topic_or_service_is_hidden.py
rclpy/rclpy/validate_full_topic_name.py
rclpy/rclpy/validate_namespace.py
rclpy/rclpy/validate_node_name.py
rclpy/rclpy/validate_parameter_name.py
rclpy/rclpy/validate_topic_name.py

Added static typing to validate files. This change was already done similarly in https://github.com/ros2/rclpy/pull/979 in response to issue https://github.com/ros2/rclpy/issues/976.

Add Static Typing to Validate files

---

rclpy/rclpy/context.py
rclpy/rclpy/destroyable.py

Adds types to context.py also creates a Destroyable Protocol.

Add types to context.py

---

rclpy/rclpy/executors.py

Backport of https://github.com/ros2/rclpy/pull/1150
I ran into this and noticed a solution is already available.
Thank you @clalancette for the works!

[iron] Fix an inherent race in execution vs. destruction. (backport of #1150)

---

rclpy/rclpy/action/server.py
rclpy/src/rclpy/action_server.cpp

part of https://github.com/ros2/ros2/issues/1462

update RCL_RET_TIMEOUT error handling with action service response.

---

rclpy/src/rclpy/action_client.hpp
rclpy/src/rclpy/action_server.hpp
rclpy/src/rclpy/clock.hpp
rclpy/src/rclpy/context.hpp
rclpy/src/rclpy/guard_condition.hpp
rclpy/src/rclpy/publisher.hpp
rclpy/src/rclpy/subscription.hpp
rclpy/src/rclpy/wait_set.hpp

only typo doc fixes. (guess come from copy&paste...)

pybind11 definition doc typo fixes.

---

rclpy/rclpy/subscription.py

This will partially fix https://github.com/ros2/rclpy/issues/1280 , though we need more PRs to do the rest of the classes.

Make subscriptions context-manager aware.

---

rclpy/rclpy/action/server.py

part of https://github.com/ros2/rcl/issues/1103

reduce result_timeout to 10 sec from 15 mins.

---

rclpy/rclpy/event_handler.py
rclpy/rclpy/node.py
rclpy/rclpy/publisher.py
rclpy/rclpy/type_support.py

Makes publisher.py type complete.

Creates PublisherHandle and updates publisher.py

---

rclpy/rclpy/__init__.py

Jazzy backport of https://github.com/ros2/rclpy/pull/1331, this should be able to backport to iron and humble.

Install signal handlers after context is initialized.

---

rclpy/test/test_messages.py

minor cosmetic fix to remove TODO for https://github.com/ros2/rmw_opensplice

Remove TODO for OpenSplice DDS issue.

---

rclpy/rclpy/callback_groups.py
rclpy/rclpy/executors.py
rclpy/rclpy/task.py
rclpy/rclpy/timer.py
rclpy/src/rclpy/action_client.hpp
rclpy/src/rclpy/action_server.cpp
rclpy/src/rclpy/action_server.hpp

This reverts commit 533d50c396ad2eb611193f099560f70835c9c7e6.
This needs to be merged before https://github.com/ros2/rclpy/pull/1359

Revert "Executors types (#1345)"
