ros2/rclpy

CMakeLists.txt
src/rclpy/_rclpy.c

The big change here is that I renamed `_rclpy.c.in` to `_rclpy.c` and changed to using a preprocessor definition instead of the CMake template that was being used before. I thought this was better so that editors could more easily detect and color the file, and for me it allowed me to add a definition to my C++ checker and then it could parse and check for warnings/errors in my editor, which is obviously harder when it's a CMake template.
I also addressed the style stuff in `_rclpy.c` according to uncrusfity and cpplint, added a copyright header, and changed it so that rcl errors are propagated up to Python as `RuntimeError`'s.
@esteve I made this as a pull request so you could consider the changes before merging it into your pull request.

fix up warnings and use definition to specialize _rclpy.c

---

CMakeLists.txt
__init__.py.in

Based on the discussion in https://github.com/ros2/rclpy/pull/2#discussion_r52928354

avoid copying Python files from source to build space

---

rclpy/rclpy/impl/rmw_implementation_tools.py

If I have both Connext and fastRTPS installed, I get the following error when trying to run either `listener_py` or `talker_py`
```
Traceback (most recent call last):
File "/home/dhood/ros2_ws/install_isolated/rclpy_examples/bin/listener_py", line 9, in <module>
load_entry_point('rclpy-examples==0.0.0', 'console_scripts', 'listener_py')()
File "/home/dhood/ros2_ws/build_isolated/rclpy_examples/listener_py.py", line 30, in main
rclpy.init(args)
File "/home/dhood/ros2_ws/install_isolated/rclpy/lib/python3.4/site-packages/rclpy/__init__.py", line 42, in init
rmw_implementation_tools.import_rmw_implementation()
File "/home/dhood/ros2_ws/install_isolated/rclpy/lib/python3.4/site-packages/rclpy/impl/rmw_implementation_tools.py", line 85, in import_rmw_implementation
__rmw_implementation_module …
```

Don't allow fastrtps to be selected in rclpy

---

rclpy/CMakeLists.txt
rclpy/rclpy/impl/rmw_implementation_tools.py
rclpy/test/test_select_rmw_implementation.py

I added a new "ament index" entry specifically for rmw implementations with Python extensions and use that to load from. This removes the need for the blacklist in #10 and also addresses the style issues from #10.
I also removed the exceptions in the tests for these failures. However, in order to get the tests working I had to add another patch to `ament_cmake` so that I can use the ament index before installing.

register rmw python extensions separately

---

rclpy/rclpy/__init__.py
rclpy/rclpy/exceptions.py
rclpy/rclpy/impl/excepthook.py
rclpy/rclpy/impl/rmw_implementation_tools.py

I achieved this by adding a helpful message which prints when the import fails, but only if it goes unhandled.
I wanted to avoid printing it always incase someone is explicitly trying each of the implementations and wants to avoid the logging output. To accomplish this I added a custom `excepthook` for `rclpy` to override the built-in `sys.excepthook`. You can also add "addendum's" for uncaught exceptions, which will printed before the traceback. In the custom `excepthook`, it looks for a matching addendum, prints it if it finds one, and then passes along the unhandled exception to the original `excepthook`.
This is the observed behavior:
- In the normal case you get something like:
```
% python3 -c "import talker_py; talker_py.main()"
Failed to import the Python extension for the …
```

Improved rclpy import failed message

---

rclpy/CMakeLists.txt

For reducing hardcoded rmw implementation blacklisting.
Needs ros2/rmw#67

Skip building rclpy for rmw implementations with no C typesupport

---

rclpy/src/rclpy/_rclpy.c

Avoid code duplication by using rcl underlying functions to initialize all rcl structures

use rcl functions for initialization

---

rclpy/rclpy/__init__.py
rclpy/src/rclpy/_rclpy.c

This add support for SIGINT signals to be processed from C code and raise the interrupt in Python.
This solves the current issue of Python scripts not killable if they're spinning

Add sigint guard condition

---

rclpy/package.xml

All these are artifacts from the time rclpy was testing pub/sub internally and not in test_communication.
Linux: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2036)](http://ci.ros2.org/job/ci_linux/2036)
OSX: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1568)](http://ci.ros2.org/job/ci_osx/1568/)
Windows: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2025)](http://ci.ros2.org/job/ci_windows/2025/)

remove unused dependencies

---

rclpy/rclpy/__init__.py

Fixes a traceback in the server side of `example_rclpy`.

check return value of rclpy_take_request for None

---

rclpy/rclpy/impl/excepthook.py

I couldn't find a way to make the docstring imperative and still make sense. So I added a noqa as suggested by pydocstyle when this one gives a false positive. I'm 100% happy with the solution, but I'm going to merge it as soon as I get a green CI back since it is broken on master atm due to the new pydocstyle version.
If someone has a better solution please open up a new pr for it.

skip D401 on rclpy_excepthook

---

rclpy/src/rclpy/_rclpy.c

I believe this PR fixes the memory leak referred to in #74. Here are my results with valgrind, pre- and post-fix:
```
Without fix (Float64MultiArray test):
==23766== LEAK SUMMARY:
==23766==    definitely lost: 584 bytes in 17 blocks
==23766==    indirectly lost: 2,400,702 bytes in 22 blocks
==23766==      possibly lost: 8,888 bytes in 14 blocks
==23766==    still reachable: 3,967,098 bytes in 3,247 blocks
==23766==         suppressed: 0 bytes in 0 blocks
With fix (Float64MultiArray test):
==18138== LEAK SUMMARY:
==18138==    definitely lost: 323 bytes in 13 blocks
==18138==    indirectly lost: 320 bytes in 7 blocks
==18138==      possibly lost: 8,200 bytes in 13 blocks
==18138==    still reachable: 3,949,000 bytes in 3,240 blocks
==18138==         suppressed: 0 bytes in 0 blocks
Without …
```

fixes memory leak in rclpy_publish

---

rclpy/package.xml
rclpy/rclpy/__init__.py
rclpy/rclpy/exceptions.py
rclpy/rclpy/expand_topic_name.py
rclpy/rclpy/node.py
rclpy/rclpy/validate_full_topic_name.py
rclpy/rclpy/validate_namespace.py
rclpy/rclpy/validate_node_name.py
rclpy/rclpy/validate_topic_name.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_create_node.py
rclpy/test/test_expand_topic_name.py
rclpy/test/test_node.py
rclpy/test/test_validate_full_topic_name.py
rclpy/test/test_validate_namespace.py
rclpy/test/test_validate_node_name.py
rclpy/test/test_validate_topic_name.py

Connects to ros2/rcl#137
Here are some examples of what it looks like when you give invalid names now:
- invalid node name
```
% python3 -c "import rclpy; rclpy.init(); rclpy.create_node('invalid_node?')"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/william/ros2_ws/install/lib/python3.6/site-packages/rclpy/__init__.py", line 38, in create_node
validate_node_name(node_name)
File "/Users/william/ros2_ws/install/lib/python3.6/site-packages/rclpy/validate_node_name.py", line 34, in validate_node_name
raise InvalidNodeNameException(node_name, error_msg, invalid_index)
rclpy.exceptions.InvalidNodeNameException: Invalid node name: node name must not contain characters other than alphanumerics or '_':
'invalid_node?'
^
```
- invalid node namespace
```
% …
```

Use namespaces

---

rclpy/src/rclpy/_rclpy.c

Otherwise Python code not blocked on `wait` but anywhere else can't be `Ctrl-C`ed.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2706)](http://ci.ros2.org/job/ci_linux/2706/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=247)](http://ci.ros2.org/job/ci_linux-aarch64/247/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2163)](http://ci.ros2.org/job/ci_osx/2163/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2836)](http://ci.ros2.org/job/ci_windows/2836/)

restore signal handler after wait

---

rclpy/rclpy/qos.py
rclpy/src/rclpy/_rclpy.c

CI:
- Linux:
- [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2711)](http://ci.ros2.org/job/ci_linux/2711/)
- Linux-aarch64:
- [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=253)](http://ci.ros2.org/job/ci_linux-aarch64/253/)
- macOS:
- [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2170)](http://ci.ros2.org/job/ci_osx/2170/)
- macOS (with nightly release settings):
- [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2171)](http://ci.ros2.org/job/ci_osx/2171/)
- Windows:
- [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2840)](http://ci.ros2.org/job/ci_windows/2840/)
- Windows (with nightly release settings):
- [![Build …

support new qos avoid_ros_namespace_conventions

---

rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c

The patch fixes three problems:
* The destroy logic was broken. Removing elements from a list while iterating of it results in the wrong behavior (only every second item was destroyed before).
* When an exception is being set the function must return `NULL` in order to pass it correctly from the C extension to Python.
* ~~Before using the node handle for the destroy calls in needs to be checked if it is valid.~~ **Update:** covered by the fixed error handling code already.
This can be reproduced by running these two commands with `rmw_connext_cpp`:
* `ros2 run examples_rclpy_minimal_service examples_rclpy_minimal_service`
* `ros2 run examples_rclpy_minimal_client examples_rclpy_minimal_client_async`
With the patch the problem of the node being invalid when the client is trying to be …

fix destroy logic and error handling

---

rclpy/test/test_destruction.py

After messing with the internal node handle and testing that the destroy function will raise the expected exception the test needs to restore the original node handle and actually destroy the node correctly. Otherwise the Python GC will try to delete the node (eventually) later and run into the same exception the test checked for.
This will get rid of the exception which is being raised even though the actual test passes (happening in existing CI jobs e.g. http://ci.ros2.org/view/nightly/job/nightly_linux_debug/524/consoleFull#console-section-264):
```
test 1
Start 1: rclpytests
1: Test command: /home/rosbuild/ci_scripts/venv/bin/python3 "-u" "/home/rosbuild/ci_scripts/ws/install/ament_cmake_test/share/ament_cmake_test/cmake/run_test.py" …
```

cleanup node correctly in test

---

rclpy/CMakeLists.txt

connects to ros2/rmw_connext#236
Running these tests with Connext takes longer than 60s (http://ci.ros2.org/job/ci_linux/2907/). Therefore increasing the timeout (http://ci.ros2.org/job/ci_linux/2908/).

increase timeout for python tests

---

rclpy/src/rclpy/_rclpy.c

Not sure exactly why this fails on some machines and pass on others. I found that patch when investigating the numerous python test failures on Windows Debug on windshield.
Looks like "p" provides a bool but it's actually an int.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2929)](http://ci.ros2.org/job/ci_linux/2929/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=397)](http://ci.ros2.org/job/ci_linux-aarch64/397/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2373)](http://ci.ros2.org/job/ci_osx/2373/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3054)](http://ci.ros2.org/job/ci_windows/3054/) (unrelated test failures)
Job on …

convert bool to int to fix failure on windshield

---

rclpy/rclpy/node.py
rclpy/rclpy/timer.py

This removes an extra call to `rclpy_create_timer()`  and two unused arguments in `WallTimer.__init__()`. A timer handle was created inside of `Node.create_timer()` and given to `WallTimer.__init__()` which ignored the handle and created its own.

Remove duplicate call to rclpy_create_timer()

---

rclpy/rclpy/qos.py
rclpy/rclpy/timer.py

In python 3 classes [implicitely inherit from object](https://docs.python.org/3.5/tutorial/classes.html#multiple-inheritance), so no need to express inheritence except if the class inherits from something else.
Addresses https://github.com/ros2/rclpy/pull/104#discussion_r135370317

implicitly inherit from object

---

rclpy/rclpy/__init__.py
rclpy/src/rclpy/_rclpy.c

Addresses the memory leak described in #74. The script still uses a large amount of memory though.
This PR only fixes the leak of the waitset. A similar patch is required for every entity allocated with `PyMem_Malloc` (node, publisher, subscriptions, service, client, timer, guard condition, header (twice), qos_profile).

add function to destroy waitset and call it in spin_once

---

rclpy/src/rclpy/_rclpy.c

Before the calling code would still own the list items and therefore their ref count would never go to zero. Preallocating the list and then using `PyList_SET_ITEM` will make sure that the ref count of each item is decremented automatically when being added to the list.
This gives me a constant memory usage for an infinite `spin_once` loop as described in #74 :tada:

fix ref count of list items

---

rclpy/rclpy/__init__.py
rclpy/rclpy/callback_groups.py
rclpy/rclpy/client.py
rclpy/rclpy/executors.py
rclpy/rclpy/node.py
rclpy/rclpy/service.py
rclpy/rclpy/subscription.py
rclpy/rclpy/timer.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_callback_group.py
rclpy/test/test_executor.py
rclpy/test/test_timer.py

This adds Executors and CallbackGroups to rclpy. This is part of feature parity with rclcpp.
Executors and CallbackGroups are added in the fourth commit on this branch. The first 3 commits are prerequisites:
1. Release the GIL so other python threads can run during a call to `rcl_wait()`
2. Add functions to rclpy for guard conditions
3. Change `Node.__init__` arguments so it can be created by inheriting from it
See examples in ros2/examples#182 and ros2/demos#169
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3213)](http://ci.ros2.org/job/ci_linux/3213/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=533)](http://ci.ros2.org/job/ci_linux-aarch64/533/)
* macOS [![Build …

Executors and Callback Groups

---

rclpy/rclpy/impl/implementation_singleton.py

closes #115 
connects to #115 
Thew content of the [referenced wiki page](https://github.com/ros2/ros2/wiki/Rclpy-Import-error-hint) can be updated at a later date
Without this change
```
Failed to load entry point 'pub': DLL load failed: The specified module could not be found.
Traceback (most recent call last):
File "C:\dev\ros2\lib\demo_nodes_py\talker-script.py", line 11, in <module>
load_entry_point('demo-nodes-py==0.0.0', 'console_scripts', 'talker')()
File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 570, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2687, in load_entry_point
return ep.load()
File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line …
```

add hint if rclpy fails to be imported

---

rclpy/src/rclpy/_rclpy.c

The first commit makes sure that we return `NULL` each time `PyArg_ParseTuple` fails and raises an exception.
The second commit uses `PyCapsule_CheckExact` rather than comparing capsules to `Py_None`. It is an attempt to address https://github.com/ros2/rclpy/pull/120#pullrequestreview-63114812 but doesnt reduce the amount of code unfortunately because we still need to extract the pointer (to pass it's value to the entity we create) and then free it... This could be changed to a call to `PyCapsule_IsValid` and adapt the names passed to in when our [capsules get names](https://github.com/ros2/rclpy/issues/124).

Check exact capsules

---

rclpy/rclpy/executors.py
rclpy/rclpy/guard_condition.py
rclpy/rclpy/node.py
rclpy/test/test_guard_condition.py

Adds a class `GuardCondition` that can be instantiated with `node.create_guard_condition(callback)`. The callback will be executed after `gc.trigger()` is called.
There is no queue of callbacks. If a user triggers a guard condition multiple times the callback will only be called once during the next spin cycle.
Labeled in-progress while CI is running. I'll switch it to in-review when the jobs complete.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3363)](http://ci.ros2.org/job/ci_linux/3363/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=618)](http://ci.ros2.org/job/ci_linux-aarch64/618/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2696)](http://ci.ros2.org/job/ci_osx/2696/ …

Rclpy GuardCondition

---

rclpy/src/rclpy/_rclpy.c

@sloretz I made a few fixups in the modified docblocks of #129 but didnt want to push directly on your branch. Feel free to cherry pick/apply what you think makes sense.

Rclpy named capsules fixups

---

rclpy/rclpy/client.py
rclpy/rclpy/executors.py
rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py

Naming capsules prevents calling the wrong kind of cleanup on a pointer. This also removes the string parameter from `rclpy_destroy_entity` and `rclpy_destroy_node_entity` since it can be figured out from the capsule name.
If a non-capsule or a capsule of the wrong type is specified, the functions let `PyCapsule_GetPointer` raise.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3381)](http://ci.ros2.org/job/ci_linux/3381/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=630)](http://ci.ros2.org/job/ci_linux-aarch64/630/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2714)](http://ci.ros2.org/job/ci_osx/2714/)
* Windows [![Build …

Use PyCapsule names

---

rclpy/rclpy/impl/implementation_singleton.py

Error looks something like:
```
File "C:\path\to\ws\install\Lib\site-packages\rclpy\impl\implementation_singleton.py", line 35, in <module>
if os.path.isfile(e.path):
File "C:\Python36\lib\genericpath.py", line 30, in isfile
st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

protect against ImportError.path being None

---

rclpy/src/rclpy/_rclpy.c

Fixes #136 
Standard CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3403)](http://ci.ros2.org/job/ci_linux/3403/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=648)](http://ci.ros2.org/job/ci_linux-aarch64/648/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2733)](http://ci.ros2.org/job/ci_osx/2733/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3450)](http://ci.ros2.org/job/ci_windows/3450/)
Windows Debug retest-until-fail 10 on rclpy: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3451)](http://ci.ros2.org/job/ci_windows/3451/)

Fix incorrect reference to service instead of pyservice

---

rclpy/src/rclpy/_rclpy.c

Follow up to comments on #137 
* Reverted moving of the PyCapsule creation to eliminate some `Py_DECREF()`
* Added `PyMem_Free` calls to failure cases (sometimes moving code down to reduce the number of places where this is called)
CI
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3417)](http://ci.ros2.org/job/ci_linux/3417/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=664)](http://ci.ros2.org/job/ci_linux-aarch64/664/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2744)](http://ci.ros2.org/job/ci_osx/2744/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3461)](http://ci.ros2.org/job/ci_windows/3461/)

Free memory when things don't go as planned

---

rclpy/rclpy/impl/implementation_singleton.py
rclpy/rclpy/impl/rcutils_logger.py
rclpy/rclpy/logging.py
rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy_logging.c
rclpy/test/test_logging.py

connects to ros2/rcutils#57
currently including commits from https://github.com/ros2/rclpy/pull/130; if this PR is ready before https://github.com/ros2/rcutils/pull/57 gets merged then it can replace #130.
This PR exposes the new notions from https://github.com/ros2/rcutils/pull/57:
1. ~there's a default severity threshold,~
1. each logger can have its own severity threshold specified,
1. there's a hierarchy of loggers: I've added a get_child() method on loggers; children inherit the severity threshold of their parent if set (the severity threshold inheritance taken care of by rcutils now that it has a notion of logger hierarchy)
1. all loggers at some point are attached to the root rclpy logger (which is where they get their default severity threshold)
Out of scope:
1. node.get_logger() …

Named logger config + logger hierarchy

---

rclpy/test/test_logging.py

Too strict on ARM debug repeated: http://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/267/
Repeating rclpy tests (manually excluding the flaky `test_timer.py`) 50 times on ARM debug: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=736)](http://ci.ros2.org/job/ci_linux-aarch64/736/)

 Relax the tolerance on throttle timing

---

rclpy/src/rclpy/_rclpy.c

Equivalent of https://github.com/ros2/rclcpp/pull/373
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3514)](http://ci.ros2.org/job/ci_linux/3514/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=737)](http://ci.ros2.org/job/ci_linux-aarch64/737/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2845)](http://ci.ros2.org/job/ci_osx/2845/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3573)](http://ci.ros2.org/job/ci_windows/3573/)

Check for the client error code, not server

---

rclpy/test/test_logging.py

Timing was too strict on ARM: http://ci.ros2.org/job/ci_linux-aarch64/740/testReport/junit/rclpy.src.ros2.rclpy.rclpy.test.test_logging/TestLogging/test_log_skip_first_throttle/
followup of https://github.com/ros2/rclpy/pull/144
also added comments to explain the expected output of the throttle tests
CI ARM (not repeated): [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=743)](http://ci.ros2.org/job/ci_linux-aarch64/743/)

Relax the tolerance on throttle + skipfirst timing

---

rclpy/rclpy/node.py

Fixes the bad behavior described in ros2/ros2cli#62 but not the actual case of the exception.

keep consistency when destroying node raises an exception

---

rclpy/test/test_timer.py

now that we have better time resolution on windows these tests can be restored.
Unfortunately the 1kHz timer tests still fail and have to stay disabled.
* Windows (rclpy tests ranusing --retest-until-fail 50) [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3653)](http://ci.ros2.org/job/ci_windows/3653/)

reenable 100Hz timer test on windows

---

rclpy/src/rclpy/_rclpy.c

the `expanded_topic` is possible to be `NULL` from
`rcl_expand_topic_name()` and then the free is problematic
Signed-off-by: Ethan Gao <ethan.gao@linux.intel.com>

Avoid unexpected free to null

---

rclpy/rclpy/__init__.py
rclpy/rclpy/node.py
rclpy/test/test_node.py
rclpy/test/test_validate_node_name.py

Minimum required to switch demos to using node loggers: logger names are not using namespaces at the moment nor calling to rcl to get their logger name.

Give nodes a logger

---

rclpy/src/rclpy/_rclpy.c

waitset -> wait_set

---

rclpy/rclpy/impl/rcutils_logger.py

connects to ros2/rcutils#75
no test for this has been added because there isn't currently support in rclpy for the equivalent of the "expression"/"function" filters that rcutils supports

Only check logger filters if severity is sufficient

---

rclpy/rclpy/executors.py
rclpy/rclpy/utilities.py
rclpy/test/test_utilities.py

Taken from #140 / #127. It adds a utility for converting timeouts from seconds to nanoseconds for rcl_wait. Additionally executor timeouts now block if None or negative and are only non-blocking if the timeout is zero.
CI
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3632)](http://ci.ros2.org/job/ci_linux/3632/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=814)](http://ci.ros2.org/job/ci_linux-aarch64/814/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2963)](http://ci.ros2.org/job/ci_osx/2963/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3726)](http://ci.ros2.org/job/ci_windows/3726/)

Added timeout_sec_to_nsec utility

---

rclpy/rclpy/client.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_client.py

This adds a method `service_is_ready` to the client, [same as rclcpp](https://github.com/ros2/rclcpp/blob/c70f2f145239ca4dfe86c6d806f331602a0e5c68/rclcpp/include/rclcpp/client.hpp#L81). 
It also adds a temporary implementation of `wait_for_service`. It is not an acceptable implementation long term. Including it allows merging ros2/demos#182, ros2/examples#185, and ros2/system_tests#244.
CI (4th run with 111a4cb6da8b682448950abf5e858205412cb7b6 )
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3638)](http://ci.ros2.org/job/ci_linux/3638/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=819)](http://ci.ros2.org/job/ci_linux-aarch64/819/) (Flaky 1kHz python timer tests failed).
* macOS [![Build …

Add client.service_is_ready

---

rclpy/rclpy/executors.py

These are some minor optimizations pulled out of #140.
All of them avoid unnecessary list comprehensions. The result is the time spent in the executor during `spin_once` in the 1kHz timer test using `func_number_callbacks` drops from 25.5% to 22.2% (average of 100 runs). It's not much, but it might be enough to reduce the test flakiness. I made one change at a time checking the overhead with a script, so I'm confident that each change here is an optimization.
CI
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3643)](http://ci.ros2.org/job/ci_linux/3643/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=823)](http://ci.ros2.org/job/ci_linux-aarch64/823/)
* macOS [![Build …

Executor avoids list comprehensions

---

rclpy/src/rclpy/_rclpy_logging.c

rcutils logging sets error messages on failure as of ros2/rcutils#65
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3652)](http://ci.ros2.org/job/ci_linux/3652/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=832)](http://ci.ros2.org/job/ci_linux-aarch64/832/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2989)](http://ci.ros2.org/job/ci_osx/2989/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3754)](http://ci.ros2.org/job/ci_windows/3754/)

Clear rcutils error on failure

---

rclpy/rclpy/executors.py

This adds a wrapper around `wait_for_ready_callbacks` that reuses the callback generator when multiple things are ready. It avoids unnecessary wait list construction and waiting. It also prevents one callback (like a very fast timer) from starving other callbacks (similar to ros2/rclcpp#392).
Taken from #140 and improved upon. 
CI (New run after fixing a merge conflict)
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3635)](http://ci.ros2.org/job/ci_linux/3635/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=816)](http://ci.ros2.org/job/ci_linux-aarch64/816/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2969)](http://ci.ros2.org/job/ci_osx/2969/)
* Windows [![Build …

Reuse ready callbacks generator

---

rclpy/rclpy/impl/rcutils_logger.py
rclpy/rclpy/logging.py
rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy_logging.c
rclpy/test/test_logging.py

In light of the upcoming supported release I want to remove some things that have been bothering me about the logging API.
We decided that in rclcpp users should be "forced" to create a named logger to make a call, so that they think about the hierarchy etc. Because of this I have removed the convenience functions `rclpy.loginfo` etc on the root logger (now "private") to match.
I did not remove the root logger completely: user-created loggers still attach to the root logger because the root logger's name, though it's currently empty, will encapsulate prefix conventions should they ever be introduced.
https://github.com/ros2/rclpy/commit/10cea411b37530eee92e8b352df771e2705a02ab
https://github.com/ros2/rclpy/commit/6d67190b698dbd979b4e5037eee422fb709d8171
Matches python logging module; the …

Remove root logger usage (rclpy.loginfo) and get_severity_threshold()

---

rclpy/test/test_timer.py

This pull request disables the 1kHz timer tests on arm. They sometimes fail due to the time it takes for the executor to execute the timer callbacks being slightly too long. That issue will need to be fixed, but this will eliminate the noise in the meantime.
CI (only testing rclpy)
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3836)](http://ci.ros2.org/job/ci_linux/3836/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=968)](http://ci.ros2.org/job/ci_linux-aarch64/968/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3172)](http://ci.ros2.org/job/ci_osx/3172/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3917)](http://ci.ros2.org/job/ci_wind …

Disable 1kHz timer tests on arm

---

rclpy/test/test_executor.py

This adds a sleep to workaround a race condition in `test_multi_threaded_executor_executes`. `MultiThreadedExecutor` runs callbacks in a thread pool. It is possible for `func_execution` to return `False` before the thread pool executes `timer_callback`.
CI with testing set test only rclpy since this only changes a test.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3835)](http://ci.ros2.org/job/ci_linux/3835/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=966)](http://ci.ros2.org/job/ci_linux-aarch64/966/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3170)](http://ci.ros2.org/job/ci_osx/3170/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&buil …

Sleep to workaround race condition in MultiThreadedExecutor test

---

rclpy/rclpy/executors.py

This removes the addition of a leading underscore to imported names. I believe it was a review comment from @dirk-thomas on an earlier pull request, but I wasn't able to quickly find it.
CI
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3834)](http://ci.ros2.org/job/ci_linux/3834/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=965)](http://ci.ros2.org/job/ci_linux-aarch64/965/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3169)](http://ci.ros2.org/job/ci_osx/3169/)
* `test_composition__rmw_fastrtps_cpp` timed out, unrelated to these changes
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3914)](http://ci.ros2.org/job/ci_windows/3914/) 
* …

Remove underscores from imports

---

rclpy/rclpy/executors.py
rclpy/rclpy/task.py
rclpy/test/test_executor.py
rclpy/test/test_task.py

This adds coroutine support to the executor and is part of service feature parity #123 and `wait_for_service` without a `GraphListener` #58.
Any callback can now be a coroutine function (`async def`). If the callback is a coroutine and it becomes blocked the executor will move on and resume executing it later. The details of this are handled in the class `Task` which is a class very similar to [asyncio.Task](https://docs.python.org/3/library/asyncio-task.html#task). `asyncio` can't be used directly because it is not thread safe.
This PR also adds a `Future` class that represents the result of a stored task. It is not used in this PR, but an example of using it is in #170.
**CI** ( with 5f2cb1eb6cc451acbe0bb58b93672ebe224b45e6)
* Linux [![Build …

Futures and coroutines

---

rclpy/rclpy/client.py
rclpy/rclpy/executors.py
rclpy/src/rclpy/_rclpy.c

This fixes a bug where rclpy_take_response ignores the sequence number in a struct populated by rcl_take_response. This becomes important once the client supports multiple outstanding requests (#170).
connects to ros2/rcl#205
CI (with  e260ce6)
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3883)](http://ci.ros2.org/job/ci_linux/3883/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1002)](http://ci.ros2.org/job/ci_linux-aarch64/1002/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3209)](http://ci.ros2.org/job/ci_osx/3209/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3972)](http://ci.ros2.org/job/ci_windows/3972/)

rclpy_take_response checks sequence number

---

rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py

connects to ros2/rcl#212
Note that the rclpy logger associated with a node won't be created until after the rcl node is created. I don't see an issue with this because we're not using the logger before that point anyway.

Get node's logger name from rcl

---

rclpy/src/rclpy/_rclpy.c

This passes command line arguments through to rcl. Previously there was only a TODO message. This PR allows python nodes to be remapped using ros2/rcl#217.
CI
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4016)](http://ci.ros2.org/job/ci_linux/4016/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1111)](http://ci.ros2.org/job/ci_linux-aarch64/1111/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3342)](http://ci.ros2.org/job/ci_osx/3342/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4107)](http://ci.ros2.org/job/ci_windows/4107/)
connects to ros2/ros2#450

rclpy_init() passes command line arguments to rcl_init()

---

rclpy/rclpy/__init__.py
rclpy/rclpy/client.py
rclpy/rclpy/executors.py
rclpy/test/test_client.py

Opening a PR for feedback. This uses the `Future` class added in pull request #166 to allow simultaneous requests from the same client (part of #123). It is implemented like [option 3 in this comment](https://github.com/ros2/rclpy/issues/58#issuecomment-344697128).
Specifically any ideas about `call`? This new version should not be called inside a callback because it would deadlock a `SingleThreadedExecutor`. It also is not very useful outside because an executor would need to be running in another thread for the client response to be taken from rcl.
CI
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3902)](http://ci.ros2.org/job/ci_linux/3902/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1020)](http://ci.r …

Refactor client for multiple requests

---

rclpy/src/rclpy/_rclpy.c

Necessary since each item can potentially contain a `nullptr`.
Connect to ros2/ros2#438.

handle node names which are null

---

rclpy/src/rclpy/_rclpy.c

Fix zero-initialization of rcl_arguments_t

---

rclpy/rclpy/__init__.py
rclpy/rclpy/executors.py
rclpy/test/test_executor.py

This fixes a bug where coroutine callbacks that yield while being handled in `rclpy.spin_once()` never get executed again. The task is stored in the executor, but the executor is thrown away after spinning.
This PR makes the global methods reuse an executor. The test checks that a task which yields during `rclpy.spin_once()` gets resumed on a second invocation.
CI
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3935)](http://ci.ros2.org/job/ci_linux/3935/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1053)](http://ci.ros2.org/job/ci_linux-aarch64/1053/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3262)](http://ci.ros2.org/job/ci_osx/3262/)
* Unrelated failure in …

Make rclpy.spin*() use a persistent executor

---

rclpy/rclpy/__init__.py
rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py

This adds `cli_args` and `use_global_arguments` as keyword arguments to the node constructor.
I moved code from `remove_ros_arguments()` that created a c-array from a python sequence of strings into separate functions so I could reuse it. The downside is the c-strings in the array are now copied where before a pointer to the string was borrowed. I think reusing code is preferable to avoiding a copy in this case because removing ros arguments or creating a node is probably an infrequent task.
In progress while CI runs
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4300)](http://ci.ros2.org/job/ci_linux/4300/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1301)](http://ci.ros2.org/job/ci_linux-aarch64/1301/) …

Node accepts command line args and can ignore global args

---

rclpy/src/rclpy/_rclpy.c

Finalize arguments because caller is responsible for freeing memory used by node options.
connects to ros2/rcl#231

Fini arguments passed to rcl_node_init()

---

rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py

This is a partial implementation of [https://github.com/ros2/ros2cli/issues/60](https://github.com/ros2/ros2cli/issues/60).  I marked it as a WIP since I expect some comments.  Plan to merge changes later and do another PR.
Connects to ros2/ros2cli#60

Count publishers and subscribers

---

rclpy/rclpy/executors.py
rclpy/src/rclpy/_rclpy.c

Fixes ros2/launch#80
Previously we just stored it and restored it after wait woke up.

call the original signal handler when receiving SIGINT during wait

---

rclpy/rclpy/client.py
rclpy/rclpy/executors.py
rclpy/rclpy/task.py

Fixes #198.
Looking for feedback on this patch.

Fix exception handling

---

rclpy/src/rclpy/_rclpy.c

This separates memory allocation out from convert_from_py function. Now it uses separate create_message function to allocate message, making it explicit gives better control where and how memory is allocated and freed.
See https://github.com/ros2/rosidl_python/issues/5 for details.
This pull request depends on changes in https://github.com/ros2/rosidl_python/pull/7
connects to ros2/rosidl_python#7

Fixes memory leaks for nested fields

---

rclpy/package.xml
rclpy/test/test_callback_group.py
rclpy/test/test_destruction.py
rclpy/test/test_node.py

To be backported in bouncy https://github.com/ros2/ros2/issues/537
Allows to release the `rclpy` repo without needing to release `common_interfaces` first
Connects to https://github.com/ros2/rcl/pull/270
CI at https://github.com/ros2/rcl/pull/270#issue-201414918

use test_msgs instead of std_msgs

---

rclpy/package.xml
rclpy/rclpy/clock.py
rclpy/rclpy/duration.py
rclpy/rclpy/time.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_clock.py
rclpy/test/test_time.py

connects to ros2/rclpy#186
Still a work-in-progress but input is welcome.
The scope of this PR is the first few steps of https://github.com/ros2/rclpy/issues/186#issuecomment-405412508. It excludes TimeSource/ROS time implementation to avoid the PR getting too large.

Time, Duration, Clock wrapping rcl

---

rclpy/rclpy/node.py
rclpy/rclpy/timer.py
rclpy/src/rclpy/_rclpy.c

I was having trouble putting feedback for ros2/rclpy#211 into words. This passes the clock into `rclpy_create_timer()` instead of it being returned in an unused variable, and makes use of the cleanup code in `_rclpy_destroy_clock()`.

Alternative way of giving timers a clock

---

rclpy/rclpy/clock.py
rclpy/rclpy/node.py
rclpy/rclpy/time_source.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_clock.py
rclpy/test/test_node.py
rclpy/test/test_time_source.py

Connects to ros2/rclpy#186
Requires ros2/rcl#274
Gives nodes a clock of type ROS_TIME which will reflect the time received on `/clock` topic if the Time Source has had use of ROS time activated. Since parameters aren't available in python yet, there's no support for the `use_sim_time` parameter, but the Time Source can have ROS time activated manually by calling `time_source.ros_time_is_active = True`.
Support for clock jump notifiers not targeted for this PR.

TimeSource and support for ROS time

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

The documentation for `executor.add_node()` says it returns `True` if the node was added; however it currently just returns `None`. This fixes the function, and also makes it so the guard condition to rebuild the waitset is only triggered if the node really was added.

executor.add_node() returns a bool

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

`executor.remove_node()` was adding the node to `executor._nodes` instead of removing it. This PR fixes the function and adds a unit test.

Fix executor.remove_node()

---

rclpy/rclpy/executors.py
rclpy/rclpy/node.py
rclpy/test/test_node.py

This adds a property `node.executor` which accesses the executor the node has been added to. Internally the node stores the executor as a weak reference to avoid a reference cycle.
The purpose is to allow something with a node reference call executor functions. Specifically I want to make another PR where `TimeSource` calls `node.executor.create_task()` with time jump callbacks.
A nice side effect is `node.executor` enforces that a node has only been added to one executor. This should prevent the same entities from being waited on in multiple wait sets.
CI
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5021)](http://ci.ros2.org/job/ci_linux/5021/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1831)](http://c …

Node has a reference to its executor

---

rclpy/rclpy/duration.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_time.py

This allows `Duration` instances to be negative as talked about in ros2/rclcpp#525. `Time` is unchanged and cannot have negative values in this PR.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5029)](http://ci.ros2.org/job/ci_linux/5029/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1836)](http://ci.ros2.org/job/ci_linux-aarch64/1836/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4182)](http://ci.ros2.org/job/ci_osx/4182/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=5037)](http://ci.ros2.org/job/ci_windows/5037/)

Allow Duration to be negative

---

rclpy/rclpy/duration.py
rclpy/test/test_time.py

Allow a `Duration` to be initialized with a negative value for nanoseconds. This allows two `Time` instances being subtracted to initialize negative duration without converting the result to floating point seconds.
CI
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5032)](http://ci.ros2.org/job/ci_linux/5032/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1839)](http://ci.ros2.org/job/ci_linux-aarch64/1839/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4185)](http://ci.ros2.org/job/ci_osx/4185/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=5040)](http://ci.ros2.org/job/ci_windows/5040/)

Allow duration to be initialized with negative nanoseconds

---

rclpy/package.xml
rclpy/test/test_timer.py

these tests fail more and more often on all platforms (e.g. [here](https://ci.ros2.org/view/nightly/job/nightly_osx_repeated/1216/testReport/junit/rclpy.test/test_timer/test_timer_cancel_reset_1000hertz/))
Disabling the 1kHz test on all platforms for now until we decide how to refactor them
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5045)](http://ci.ros2.org/job/ci_linux/5045/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1842)](http://ci.ros2.org/job/ci_linux-aarch64/1842/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4189)](http://ci.ros2.org/job/ci_osx/4189/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=5042)](http://ci.ros2.org/ …

disable 1kHz test on all platforms

---

rclpy/rclpy/node.py
rclpy/test/test_parameters_callback.py

In #214 I wired up support for invoking a callback function to accept or reject a set of parameters but did not add the API to set that callback or tests for that functionality.
This pull request adds a `set_parameters_callback` method to rclpy.Node and some unit tests verifying that the callbacks are used and that the parameter values are set or not appropriately.
Every test case I used has been put into the unit tests below.
Connects to #202

Add Node API method for setting the parameters_callback.

---

rclpy/rclpy/node.py
rclpy/rclpy/parameter.py
rclpy/rclpy/parameter_service.py
rclpy/rclpy/qos.py
rclpy/test/test_destruction.py

This is a recreation of a change that was accidentally authored in a temporary container :sob:. 
Adds a parameter events publisher to rclpy nodes and publishes events when parameters are successfully set atomically.
I did some basic testing of the earlier version of this using `ros2 topic echo` and comparing the results with rclcpp nodes but I need to do a bit more before I feel good putting this in review.
Connects to #202

Publish parameter events

---

rclpy/rclpy/executors.py
rclpy/src/rclpy/_rclpy.c

Use consolidated rcl_wait_set_clear()

---

rclpy/rclpy/clock.py
rclpy/rclpy/time_source.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_clock.py
rclpy/test/test_time_source.py

This adds callbacks when ROSTime jumps. The implementation closely mimics the implementation in `rclcpp`.
Time jump callbacks use the `rcl_clock_t` time jump callbacks. Python code is called in the callbacks using `PyObject_CallObject()`.
Requires ros2/rcl#284

Callbacks when time jumps

---

rclpy/CMakeLists.txt
rclpy/package.xml
rclpy/rclpy/__init__.py
rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c

With this pull request initial parameters can be passed via yaml parameters file with the `__params:=` and as a list of parameters in the `initial_parameters` kwarg of the Node constructor.
Parameters in the constructor will override parameters from a parameters file.
If at least one reviewer could keep a close eye on my use of Py_DECREF and make sure that I have employed everywhere I should and nowhere I shouldn't have I'd be grateful..  I'm fairly confident in my usage but it's also my first time in Python's C API. 
To test this PR I've been using the params.yaml in this gist https://gist.github.com/nuclearsandwich/8753121711671bfa8d9cb5f718ce09bc and the talker node from demo_nodes_py as well as the parameter services behavior just merged from #214 
Connects to #202

Take initial parameters from parameters yaml files and constructor arguments.

---

rclpy/src/rclpy/_rclpy.c

Resolves the warning below which popped up in the nightlies ([example](https://ci.ros2.org/view/nightly/job/nightly_linux_release/918)) from #225 
```
In file included from /usr/include/python3.6m/pytime.h:6:0,
from /usr/include/python3.6m/Python.h:68,
from /home/rosbuild/ci_scripts/ws/src/ros2/rclpy/rclpy/src/rclpy/_rclpy.c:15:
/home/rosbuild/ci_scripts/ws/src/ros2/rclpy/rclpy/src/rclpy/_rclpy.c: In function ‘_parse_param_files’:
/usr/include/python3.6m/object.h:791:27: warning: ‘value’ may be used uninitialized in this function [-Wmaybe-uninitialized]
--(_py_decref_tmp)->ob_refcnt != 0)             \
^~
/home/rosbuild/ci_scripts/ws/src/ros2/rclpy/rclpy/src/rclpy/_rclpy.c:3547:14: note: ‘value’ was declared here
PyObject * value;
^~~~~
```

Fix warning when parameter value is uninitialized.

---

rclpy/rclpy/time.py
rclpy/test/test_time.py

Exposing the tuple avoids calling code to perform the same computation in numerous places.

add getter for tuple with seconds and nanoseconds

---

rclpy/test/mock_compat.py
rclpy/test/test_clock.py
rclpy/test/test_time_source.py

This fixes some test failures on xenial caused by ros2/rclpy#222. The tests used methods on `unittest.mock.Mock` that were added in python 3.6. This PR ~~~adds a subclass with those methods defined~~~ monkey patches those methods onto the mock class if they are not present.
Xenial CI just rclpy
[![Build Status](https://ci.ros2.org/job/ci_linux/5177/badge/icon)](https://ci.ros2.org/job/ci_linux/5177/)
CI bionic just rclpy
[![Build Status](https://ci.ros2.org/job/ci_linux/5178/badge/icon)](https://ci.ros2.org/job/ci_linux/5178/)
Will run full CI post review
Connects to ros2/build_cop#147

Add methods on Mock class for Python 3.5 compatibility

---

rclpy/test/mock_compat.py

ros2/rclpy#237 added monkey patching to `unitest.mock.Mock` for compatibility with python 3.5. It looks like I got confused and ended up merging without running xenial CI again, and the approach had test failures: https://ci.ros2.org/view/nightly/job/nightly_xenial_linux_release/101/testReport/junit/(root)/rclpy/test_test_clock/
There seems to be a difference in the number of arguments `MethodType` takes in python 3.5 and 3.6. It turns out `MethodType` isn't necessary when adding new methods to a class rather than an instance, so this PR removes it. 
Xenial
[![Build Status](https://ci.ros2.org/job/ci_linux/5202/badge/icon)](https://ci.ros2.org/job/ci_linux/5202/)
CI
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5203)](http://ci.ros2.org/job/ci_linux/5203/) …

Don't use MethodType when monkey patching

---

rclpy/CMakeLists.txt

Set library path environment hook for this package. This package is one of a handful which installs libraries without setting an environment hook to add them to the platform library path.
Connects to ros2/ros_workspace#10

Add library path hook.

---

.gitignore
rclpy/rclpy/__init__.py
rclpy/rclpy/client.py
rclpy/rclpy/context.py
rclpy/rclpy/executors.py
rclpy/rclpy/guard_condition.py
rclpy/rclpy/node.py
rclpy/rclpy/task.py
rclpy/rclpy/timer.py
rclpy/rclpy/utilities.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_callback_group.py
rclpy/test/test_client.py
rclpy/test/test_create_node.py
rclpy/test/test_destruction.py
rclpy/test/test_executor.py
rclpy/test/test_guard_condition.py
rclpy/test/test_init_shutdown.py
rclpy/test/test_node.py
rclpy/test/test_parameters_callback.py
rclpy/test/test_time_source.py
rclpy/test/test_timer.py
rclpy/test/test_waitable.py

Notable this pr, unlike the rclcpp one, does not provide access to the ingoing init options, partially because I think it's not as useful right now and partially because I'm completely out of time to work on this set of changes.
Connects to ros2/rmw#154

refactor to allow for non-global init

---

rclpy/rclpy/node.py

Connects to ros2/rcl_interfaces#51
This PR follows my pull request in rcl_interfaces: ros2/rcl_interfaces#51 which adds a node name field and timestamp field to the ParameterEvents.msg. This pull request fills those fields.

Fill ParameterEvent.msg with timestamp and node path name

---

rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c

*Summary:* Add node graph calls to Node class in ros2 python
Connects to ros2/rcl#333

Add node graph functions

---

rclpy/test/test_messages.py

This pull request validates that only ASCII strings are published on `string` fields.
Connected to https://github.com/ros2/rosidl_python/pull/26.

Adds a test for invalid string checks on publishing

---

rclpy/rclpy/executors.py
rclpy/rclpy/node.py
rclpy/rclpy/subscription.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py
rclpy/test/test_waitable.py

Note: This implementation is incomplete and at the moment this PR exists primarily for getting feedback.
This is being done so that [ros2cli#132](https://github.com/ros2/ros2cli/issues/132) can implement "ros2 topic bw".
The general idea is to allow creating a raw subscription like so:
```
class ListenerRaw(Node):
def __init__(self):
super().__init__('listener')
self.sub = self.create_subscription(String, 'chatter', self.chatter_callback, raw=True)
def chatter_callback(self, msg):
self.get_logger().info('I heard: [%s]' % msg)
```
This will call rcl_take_serialized_message rather than rcl_take internally, and return a python byte array representing the serialised message.
> [INFO] [listener]: I heard: [b'\x00\x01\x00\x00\x05\x00\x00\x00Test\x00\x00\x00\x00']
(For the message "Test").

rclpy raw subscriptions

---

rclpy/rclpy/waitable.py
rclpy/test/test_waitable.py

Resolves #264 
This fixes an assertion error that occurs if a Waitable is used with a MutuallyExclusiveCallbackGroup.
Added a unit test to cover this case.

Add Waitable to callback group

---

rclpy/rclpy/executors.py
rclpy/src/rclpy/_rclpy.c

pass context to wait set

---

rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py

Resolves #266 
Ensure return value is `const char *` for compatibility with Python v3.7+.
Also, renamed PyObject variables for consistency with the rest of the file.
Update expected error message in unit test.

Replace PyUnicode_1BYTE_DATA() with PyUnicode_AsUTF8()

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

If a task is created, then trigger the Executors guard condition. This will wake any blocking call to `rcl_wait()`.
In this scenario, no work is yielded, so we also have to move the check for 'in-progress' tasks into the wait loop.
Added a unit test to reproduce the issue.
This resolves an issue in some cases where the result response from the action server is never processed, therefore never reaching the action client.

Fix Executor not executing tasks if there are no ready entities in the wait set

---

rclpy/src/rclpy/_rclpy.c
rclpy/test/test_init_shutdown.py

Connected to ros2/rcl#374. An additional check to provide better exception messages.

Enforce UTF8 argv on rclpy.init()

---

rclpy/rclpy/node.py
rclpy/test/test_executor.py

Previously, if a `Node` was added to an `Executor` using the executors `add_node` method, then the nodes `executor` property would return `None`.

Fix Node's reference to executor

---

rclpy/CMakeLists.txt
rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_action.c
rclpy/src/rclpy/impl/common.h
rclpy/src/rclpy_common/include/rclpy_common/common.h
rclpy/src/rclpy_common/include/rclpy_common/visibility_control.h
rclpy/src/rclpy_common/src/common.c

This helps with readability and maintainability.
Also eliminated use of assertions during conversions, defering to exceptions.
I plan to make use of these functions for the Action extension module (#257) in a follow-up PR.

Abstract type conversions into functions

---

rclpy/rclpy/executors.py

Dictionaries raise `KeyError` instead of `IndexError`. I'm not sure how to write a test for this, so I didn't.
See https://github.com/ros2/rclpy/pull/170#discussion_r257388836

Dictionaries raise KeyError

---

rclpy/rclpy/action/__init__.py
rclpy/rclpy/action/server.py
rclpy/rclpy/clock.py
rclpy/rclpy/executors.py
rclpy/src/rclpy/_rclpy_action.c
rclpy/test/action/test_client.py
rclpy/test/action/test_server.py

Resolves #257 
Similar to `ActionClient`, `ActionServer` is implemented as a `Waitable` and the user interacts with goals via `ServerGoalHandle` objects. 
This is a work in progress. Still need to implement the "get result" logic, add documentation, and some more tests. I separated some changes to `_rclpy.c` into #269 to avoid adding more to this large change. Since this PR is based on that branch, #269 should be resolved first.

Add ActionServer

---

rclpy/test/action/test_client.py

Closes #268. 
I believe the issue was resolved by #272. This PR enables the previously failing test.
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6312)](http://ci.ros2.org/job/ci_linux/6312/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=2726)](http://ci.ros2.org/job/ci_linux-aarch64/2726/)
* macOS [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5190)](https://ci.ros2.org/job/ci_osx/5190/)
* Windows [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=6158)](https://ci.ros2.org/job/ci_windows/6158/)
Errors are unrelated to this change (ros2/build_cop#166).

Enable test using MultiThreadedExecutor

---

rclpy/rclpy/action/client.py
rclpy/rclpy/action/server.py

Some middlewares (e.g. Connext and OpenSplice) appear to send empty messages after a successful service call which results in a 'failed take'.
It is unclear if this is correct behavior from the rmw/rcl layers, but it doesn't hurt to guard against this scenario.
Connects to ros2/system_tests#332.

Guard against failed take when taking action messages

---

rclpy/CMakeLists.txt
rclpy/package.xml
rclpy/rclpy/action/__init__.py
rclpy/rclpy/action/client.py
rclpy/rclpy/action/server.py
rclpy/rclpy/clock.py
rclpy/rclpy/executors.py
rclpy/rclpy/node.py
rclpy/rclpy/qos.py
rclpy/rclpy/type_support.py
rclpy/rclpy/waitable.py
rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_action.c
rclpy/src/rclpy/impl/common.h
rclpy/src/rclpy_common/include/rclpy_common/common.h
rclpy/src/rclpy_common/include/rclpy_common/visibility_control.h
rclpy/src/rclpy_common/src/common.c
rclpy/test/action/test_client.py
rclpy/test/action/test_server.py
rclpy/test/test_executor.py

Cherry-picking the following commits related to Python Actions (#257):
- 6e086af90d5a2a760104c09ae87205d3bc6407e7 ros2/rclpy#262
- 0bfd0b71bbf0341a3e97601920fe7f867bd3d628 ros2/rclpy#272
- 4028bc6ab204cea5d44d8f1c14faa5fd4f26562d ros2/rclpy#275
- 174e3375d137f7239c9c83bebaf87c048e132bd5 ros2/rclpy#269
- be4bc8821404b8ca4b2e1bf25ace755b06856870 ros2/rclpy#270
- 3b57762c97d18ca0a38d8340740680df5ebec2f6 ros2/rclpy#280
- ba90da48216748d6f29973d232ab31ea9152bb20 ros2/rclpy#281

Backport Python Actions

---

rclpy/rclpy/action/server.py
rclpy/test/test_logging.py

Use [non-deprecated method](https://docs.python.org/3.7/library/logging.html#logging.Logger.warning).
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6367)](https://ci.ros2.org/job/ci_linux/6367/)

update logger.warn (deprecated) to logger.warning

---

rclpy/src/rclpy/_rclpy.c

* fix https://github.com/ros2/rclpy/issues/215, https://github.com/ros2/rclpy/issues/253
Signed-off-by: reed-lau <geoliuwei@gmail.com>

fix sigint guard condition's lifecycle bug

---

rclpy/src/rclpy/_rclpy.c

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6305)](http://ci.ros2.org/job/ci_linux/6305/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=2721)](http://ci.ros2.org/job/ci_linux-aarch64/2721/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5182)](http://ci.ros2.org/job/ci_osx/5182/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=6143)](http://ci.ros2.org/job/ci_windows/6143/)
Edit: test failures are unrelated.

Improve error handling to avoid memory leaks in C extension

---

rclpy/rclpy/node.py
rclpy/rclpy/time_source.py
rclpy/test/test_time_source.py

Targets to #240
Since it seems there have been no response on #240 for a long time, I made this PR. However, It seems that the callback function should be changed from [parameter callback](https://github.com/ros2/rclpy/pull/228) to something like rclcpp::SyncParametersClient or rclcpp::AsyncParametersClient.
Signed-off-by: vinnamkim <vinnam.kim@gmail.com>

Add param callback to time_source

---

rclpy/package.xml
rclpy/rclpy/time_source.py
rclpy/test/test_time_source.py

Fix #303.
Signed-off-by: vinnamkim <vinnam.kim@gmail.com>

Use rosgraph_msgs.msg.Clock for TimeSource

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

This makes `executor.shutdown()` trigger the executor's guard condition. Without this the executor could block forever if no more work comes in.

Executor exits immediately when shut down

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

This fixes bug where executor would rebuild wait_set without adding or
removing nodes. This happened when an executor was waiting and had not
executed any work yet at the time the node was added or removed.

Refresh nodes when executor is woken

---

rclpy/src/rclpy/_rclpy.c

Set allocated `rmw_qos_profile_t` to the default, to future-proof against uninitialized data if new fields are added. E.g. if a field is added to `rmw_qos_profile_t` and that field is not immediately exposed in `rclpy`, the value of that field will be garbage data, and be passed all the way to the RMW implementation.

Set QoS profile to default values (pre-QoS, standalone)

---

rclpy/src/rclpy_common/src/common.c

The manual ordering of DECREFs is unwieldy - refactor to a simpler pattern that is easier to extend.
I am adding new policy types for QoS - which will utilize this change to make it much easier to do so. 

Refactor QoS Python-C conversion into less error-prone pattern (pre-QoS, standalone)

---

rclpy/rclpy/action/server.py
rclpy/src/rclpy/_rclpy_action.c
rclpy/test/action/test_server.py

Now using active verbs as described in the design doc:
http://design.ros2.org/articles/actions.html#goal-states
Connects to ros2/rcl#399.

Rename action state transitions

---

rclpy/CMakeLists.txt
rclpy/rclpy/action/server.py
rclpy/rclpy/executors.py
rclpy/rclpy/impl/implementation_singleton.py
rclpy/rclpy/signals.py
rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_action.c
rclpy/src/rclpy/_rclpy_signal_handler.c
rclpy/src/rclpy_common/src/common.c
rclpy/test/action/test_server.py

Implements @wjwwood's comment https://github.com/ros2/rclpy/issues/192#issuecomment-398251659
This moves signal handling code to a separate module `_rclpy_signal_handler`. Every executor adds a guard condition to a global list. The signal handler triggers all guard conditions in that list.
Resolves ros2/rclpy#192, and because of that this PR also allows multiple executors to wait in parallel again. This also resolves ros2/rclpy#287 by having each executor reuse the same guard condition.
It does not change the updated behavior of ros2/rclpy#253 described here: https://github.com/ros2/rclpy/issues/253#issuecomment-475613097 . Maybe that should be an issue downstream of rclpy?

Every executor gets its own SIGINT guard condition

---

rclpy/rclpy/action/client.py
rclpy/rclpy/action/server.py
rclpy/rclpy/client.py
rclpy/rclpy/publisher.py
rclpy/rclpy/service.py
rclpy/test/action/test_client.py
rclpy/test/action/test_server.py
rclpy/test/test_client.py
rclpy/test/test_messages.py

Closes #314.
The PR contains two commits:
* Adding tests passing an invalid type to the various APIs PR and expecting a `TypeError` to be raised. CI with these tests failing: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6760)](https://ci.ros2.org/job/ci_linux/6760/) ( intentionally failing tests)
* Update the implementation to check the passes type and raise `TypeError` in case it doesn't match the expected type: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6761)](https://ci.ros2.org/job/ci_linux/6761/)

enforce correct message type is passed to various API

---

rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_pycapsule.c

Fixes bug in #318.
The subscription is never being destroyed because `rclpy_pycapsule_destroy` was passing the destructor the pointer held by the pycapsule rather than the pycapsule itself. This fixes the issue and adds a warning to `_rclpy_destroy_subscription` to make this visible if it happens again.

Fix subscription pycapsule not being destroyed

---

rclpy/rclpy/subscription.py

Fixes #322
**TL;DR** the default `__eq__` and `__hash__` work just fine.
The Subscription class was using the address held by the pycapsule as the hash. However, that address is `free`'d when `Subscription.destroy()` is called. This makes it possible for a new subscription to be created using the same address, and therefore having the same hash as a `destroy()`'d subscription.
This is a problem in the unit tests that reuse the same node for multiple tests. After the subscription is destroyed in one test, a new test can create a subscription that has the same memory address. Callback groups keep a `set()` of weak references to entities (including subscriptions) that are in them. This prevents the new subscription from being added to the node's default callback group, because a weak …

Remove __eq__ and __hash__ from Subscription

---

rclpy/rclpy/duration.py
rclpy/rclpy/qos.py
rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_action.c
rclpy/src/rclpy_common/include/rclpy_common/common.h
rclpy/src/rclpy_common/src/common.c
rclpy/test/test_qos.py

Depends on ros2/rmw#173
Expose the new QoS policy settings for the Python client. Needs `rmw/types.h` from the above mentioned PR

QoS - Expose Lifespan, Deadline, and Liveliness policy settings

---

rclpy/src/rclpy/_rclpy.c

`rclpy_get_ready_entities` is returning a list of pointers to the `entity->impl` pointer, but it should be returning a list of pointers to the `entity`. For most entities this doesn't matter because the `impl` object is the first member of the struct, so the addresses are the same. `rcl_guard_condition_t` is different because the [first member is a pointer to the context](https://github.com/ros2/rcl/blob/64610d254864b87d7b35a6c9473b97a03598c3e2/rcl/include/rcl/guard_condition.h#L36).
This fixes the macro used by `rcl_get_ready_entities` and removes the workaround to the bug in `rclpy_create_guard_condition`.
Blocks #319

Wait set uses pointers to rcl types not rcl->impl types

---

rclpy/src/rclpy/_rclpy_logging.c

Before this fix, rclpy_logging_rcutils_log was using
rcutils_log without a format string (log message was
passed directly as the foramt).
This is unsafe because if the log message contains
a sequence of character which can be interpreted by
snprintf ("%d" for instance), snprintf will look for
this argument value which was never passed.
This leads to reading invalid memory and may cause a crash
or corrupted log messages.
The simple fix is to always pass "%s" when a static log
string needs to be logged.
Signed-off-by: Thomas Moulard <tmoulard@amazon.com>

Prevent rcutils_log from accessing invalid memory

---

rclpy/CMakeLists.txt
rclpy/rclpy/action/client.py
rclpy/rclpy/action/graph.py
rclpy/rclpy/action/server.py
rclpy/rclpy/client.py
rclpy/rclpy/handle.py
rclpy/rclpy/node.py
rclpy/rclpy/publisher.py
rclpy/rclpy/subscription.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_destruction.py
rclpy/test/test_handle.py
rclpy/test/test_waitable.py

Blocks #319
I was going to make this part of #319, but I think it would be easier to review separately. This makes `Node.handle` use the `Handle` class from #308. It also adds `handle.requires(another_handle)` to make sure `handle` is destroyed before `another_handle`.
#308 makes `destroy_subscription` thread safe by delaying destruction if the handle is currently being used. This makes it possible for a subscription to be destroyed after the node; which crashes when doing the same strategy with services using fast-rtps. See https://github.com/ros2/rclpy/pull/319#issuecomment-486860562 for a better explanation.
* Previously `node.destroy_node()` either returned `True` or raised an exception. I removed the return value since it was only ever `True`.
* Previously `node.handle` was set to …

Make `destroy_node` thread safe

---

rclpy/rclpy/action/server.py
rclpy/rclpy/client.py
rclpy/rclpy/clock.py
rclpy/rclpy/executors.py
rclpy/rclpy/guard_condition.py
rclpy/rclpy/node.py
rclpy/rclpy/publisher.py
rclpy/rclpy/service.py
rclpy/rclpy/signals.py
rclpy/rclpy/timer.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_action_client.py
rclpy/test/test_destruction.py
rclpy/test/test_waitable.py

Follow up to ros2/rclpy#318 and ros2/rclpy#330. This PR applies the changes done to `Subscription` to the rest of the entities on the node so they can all be destroyed safely.
Not done in this PR. These might require a change to the waitable API.
* action server
* action client

Thread safe node.destroy_*

---

rclpy/test/test_callback_group.py
rclpy/test/test_destruction.py
rclpy/test/test_messages.py
rclpy/test/test_node.py

Connects to https://github.com/ros2/rcl_interfaces/issues/58

Use new test interface definitions

---

rclpy/rclpy/signals.py

This catches an exception that causes a warning to be printed during interpreter shutdown.
```
ros2 run examples_rclcpp_minimal_action_server action_server_not_composable
```
```
ros2 action send_goal /fibonacci example_interfaces/Fibonacci '{order: 10}'
```
```
$ ros2 action send_goal /fibonacci example_interfaces/Fibonacci '{order: 10}'
Waiting for an action server to become available...
Sending goal:
order: 10
Goal accepted with ID: 7569e0d6d7624a59b80bd1960ce5c8ee
Result:
sequence: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
Goal finished with status: SUCCEEDED
```
```
$ ros2 action send_goal /fibonacci example_interfaces/Fibonacci '{order: 10}'
Waiting for an action server to become available...
Sending goal:
order: 10
Goal accepted with ID: 88ed3bca54be425b981be303eee95c27
Result: …
```

Ignore ValueError in SignalHandlerGuardCondition.__del__

---

rclpy/rclpy/node.py
rclpy/test/test_destruction.py

~~I would call this API neutral, but it is possible this raises an exception in already broken downstream code.~~ **Edit**: Changes APIs to be generators in 236b20a
Currently `Node` stores `publishers`, `subscriptions`, `clients`, ... in lists on itself. These names are pretty generic, and since we expect users to inherit from `Node` there is a risk of the names colliding. This is a problem because the executor uses these lists to add stuff to a wait set. This PR uses `@property` to at least prevent the attribute from being assigned a different object.

Make pub/sub/cli/srv/etc lists use @property on node

---

rclpy/rclpy/client.py
rclpy/rclpy/node.py
rclpy/rclpy/publisher.py
rclpy/rclpy/service.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_waitable.py

After #319 entities don't need a reference to the node handle. The entity's pycapsule has the pointer already. This PR removes the extra references.

Remove extra references to node handle

---

rclpy/rclpy/node.py
rclpy/rclpy/publisher.py
rclpy/src/rclpy/_rclpy.c

Depends on ros2/rmw#171
Expose the rcl assert_liveliness APIs for Nodes and Publishers

QoS - Expose the assert_liveliness API for Publishers and Nodes

---

rclpy/rclpy/__init__.py
rclpy/rclpy/exceptions.py
rclpy/rclpy/node.py
rclpy/rclpy/parameter.py
rclpy/rclpy/parameter_service.py
rclpy/rclpy/time_source.py
rclpy/rclpy/validate_parameter_name.py
rclpy/test/test_node.py
rclpy/test/test_parameters_callback.py
rclpy/test/test_time_source.py
rclpy/test/test_waitable.py

Closes #321; refer to the issue for details.

Parameter API enhancements

---

rclpy/CMakeLists.txt
rclpy/rclpy/executors.py
rclpy/rclpy/node.py
rclpy/test/test_create_while_spinning.py

Replaces #206 
Fixes #188 
This wakes the executor when entities are created or destroyed. I added tests for creating entities waking the executor, but I haven't figured out how to add tests for destroying entities waking the executor.
This was unblocked by #308 which made it possible to write a test for creating entities.

Wake executor when entities created or destroyed

---

rclpy/rclpy/node.py
rclpy/rclpy/publisher.py

I overlooked this when merging #313. The publisher and node pycapsules are managed by `self.handle` instead of using `node_handle` and `publisher_handle`.
There are no tests for these APIs at the moment.

Fix assert_liveliness use of node and publisher capsules

---

rclpy/rclpy/__init__.py
rclpy/rclpy/executors.py

Fixes http://build.ros2.org/job/Ddev__rclpy__ubuntu_bionic_amd64/27/testReport/
Build up to rclpy; test rclpy:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7038)](http://ci.ros2.org/job/ci_linux/7038/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=3272)](http://ci.ros2.org/job/ci_linux-aarch64/3272/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5767)](http://ci.ros2.org/job/ci_osx/5767/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=6858)](http://ci.ros2.org/job/ci_windows/6858/)

Ignore flake8 error 'imported but unused'

---

rclpy/CMakeLists.txt
rclpy/rclpy/node.py
rclpy/rclpy/publisher.py
rclpy/rclpy/qos_event.py
rclpy/rclpy/subscription.py
rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_qos_event.c
rclpy/src/rclpy_common/include/rclpy_common/common.h
rclpy/test/test_qos_event.py
rclpy/test/test_waitable.py

Depends on ros2/rmw#171
Depends on ros2/rmw_fastrtps#276
Depends on ros2/rcl#432
* Present the Python-side API for receiving QoS event callbacks for Liveliness and Deadline QoS policies.
* Provide the C-side translation layer to `rcl` to support that API.
Unit tests are still in progress - but the code is working according to manual testing and is ready for review.

QoS - API and implementation for Liveliness and Deadline event callbacks

---

rclpy/rclpy/action/client.py
rclpy/rclpy/action/server.py
rclpy/rclpy/node.py
rclpy/rclpy/qos.py
rclpy/rclpy/time_source.py
rclpy/src/rclpy_common/src/common.c
rclpy/test/test_action_client.py
rclpy/test/test_action_server.py
rclpy/test/test_callback_group.py
rclpy/test/test_create_while_spinning.py
rclpy/test/test_destruction.py
rclpy/test/test_messages.py
rclpy/test/test_node.py
rclpy/test/test_qos.py
rclpy/test/test_time_source.py
rclpy/test/test_waitable.py

Resolves #342 
* Added a new parameter to methods for creating publishers and subscriptions
The new parameter is required and must be a QoSProfile object or an integer value for the history depth.
For now, it is possible to not use the parameter for backwards compatibility, but a deprecation warning is made.
* Add deprecation warning when constructing a QoSProfile without a history depth
If the history setting is KEEP_ALL, then it is not required to pass the depth setting.

Encourage users to always provide a QoS history depth

---

rclpy/rclpy/exceptions.py
rclpy/rclpy/node.py
rclpy/test/test_node.py

Closes #341.
There are some details that still need a bit of attention (see https://github.com/ros2/rclpy/issues/341#issuecomment-491292717). The PR includes a proposal for `set_descriptor` as described in the comment.
On the other hand, I'd like some input about the optional signature using `Parameter` as input for `declare_parameter` (see [comment](https://github.com/ros2/rclpy/pull/325#discussion_r280534305)). Is it worth implementing it even if it only applies to `declare_parameter` but not `declare_parameters`?
Other than that, this should be ready for an initial review.

Parameter handling improvements.

---

rclpy/rclpy/node.py
rclpy/rclpy/parameter.py
rclpy/rclpy/parameter_service.py
rclpy/test/test_node.py
rclpy/test/test_parameter.py

This PR is another iteration for #341.
- Addresses [this comment](https://github.com/ros2/rclpy/pull/345#discussion_r283552026) about `declare_parameter` and `declare_parameters` usability.
- Allows creating `Parameter` objects without specifying the type, which is deduced in the constructor without changing the API.
- Prevents service calls from raising exceptions for `set` and `describe` parameters (as in https://github.com/ros2/rclcpp/pull/718).

Parameter flexibility enhancements

---

rclpy/rclpy/qos_event.py

It was a mistake introduced in a review feedback on the original PR https://github.com/ros2/rclpy/pull/316

Don't wrap QoS Event callback argument in a list

---

rclpy/rclpy/handle.py

This is attempt to fix an exception raised in interpreter shutdown: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1194/testReport/launch_testing_ros.test/test_examples/test_examples_talker_listener_test_py_/
<details><summary>Traceback</summary>
```
[listener-2] Exception ignored in: <bound method Executor.__del__ of <rclpy.executors.SingleThreadedExecutor object at 0x7f6c2fbacc50>>
[listener-2] Traceback (most recent call last):
[listener-2]   File "/home/jenkins-agent/workspace/nightly_linux_debug/ws/install/rclpy/lib/python3.6/site-packages/rclpy/executors.py", line 223, in __del__
[listener-2]   File "/home/jenkins-agent/workspace/nightly_linux_debug/ws/install/rclpy/lib/python3.6/site-packages/rclpy/signals.py", line 40, in destroy
[listener-2]   File …
```

Create RLock() early to avoid exception at shutdown

---

rclpy/test/test_action_graph.py

Precisely what the title says. Test tends to flake otherwise, specially when using RTI Connext as RMW implementation.
As seen in [CI](https://ci.ros2.org/job/ci_linux/7148/testReport/junit/rclpy.test.test_action_graph/TestActionGraph/test_get_action_client_names_and_types_by_node/).

Wait for nodes to discover each other in test_action_graph.py

---

rclpy/rclpy/qos.py
rclpy/test/test_qos.py

Add convenience name translations for use by commandline utilities etc.

---

rclpy/rclpy/qos.py
rclpy/test/test_qos.py

To match behavior in rclcpp.
Fixes https://github.com/ros2/rclpy/issues/353
Would like some feedback on the approach, it feels a little kludgy. It's an awkward situation though, where the default profile values we want are only exposed via a QoSProfile instance from _rclpy.c, so we have a circular dependency.

Initialize QoSProfile with values from rmw_qos_profile_default

---

rclpy/rclpy/__init__.py
rclpy/rclpy/node.py
rclpy/test/test_node.py

Connects to ros2/ros2_documentation#242

Rename parameter options

---

rclpy/rclpy/executors.py

Certainly something fishy here - I was getting unduly long blocks when the service server was not available.

[executors] don't convert a timeout_sec to nsecs

---

rclpy/src/rclpy/_rclpy.c

The short-term goal of this change is to enable the creation of a parameter YAML file which is applied to each node, regardless of node name or namespace.
Future work is to support all wildcard syntax in node names in parameter YAML files.

Use params from node '/**' from parameter YAML file

---

rclpy/rclpy/node.py
rclpy/rclpy/validate_parameter_name.py
rclpy/test/test_node.py

Closes #375.
Partially addresses #373 considering the first option described in https://github.com/ros2/rclpy/issues/373#issuecomment-504408873.
The complete parameter name validation has yet to be implemented; removing the current (incorrect) check is required to address #375. If this patch is accepted, the next step would be implementing the correct check at RCL level so that it can be used both in `rclpy` and `rclcpp` like the current topic name check.
Finally, note that in `rclcpp` the current [parameter name validation](https://github.com/ros2/rclcpp/blob/e7c463dc74849aa64cb8a74e13f2a57b4ed59862/rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp#L376-L379) is also a 'non-empty' check.

Fixing namespace expansion for declare_parameters.

---

rclpy/rclpy/qos.py

A flake8 failure appeared on Windows after https://github.com/ros2/rclpy/pull/379.
eg:
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=7289)](http://ci.ros2.org/job/ci_windows/7289/)
I don't know why they didn't appear on Linux.

Make flake8 happy on windows

---

rclpy/rclpy/time.py
rclpy/test/test_time.py

Related to #293
- Change from the floating constant value(1e9) to the integer constant value(10 ** 9)
Signed-off-by: vinnamkim <vinnam.kim@gmail.com>

Fix time conversion for a big nanoseconds value

---

rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py

Connects to https://github.com/ros2/sros2/pull/141
Requires https://github.com/ros2/rcl/pull/459

Added clients by node implementation from rcl

---

rclpy/test/test_node.py

This is causing all of our nightly jobs to be unstable, e.g.:
https://ci.ros2.org/view/nightly/job/nightly_linux_release/1232/testReport/junit/(root)/projectroot/flake8/
I think it's a follow up of https://github.com/ros2/rclpy/pull/383, but I'm not sure.

remove whitespace

---

rclpy/rclpy/node.py
rclpy/rclpy/validate_parameter_name.py
rclpy/test/test_node.py

This PR is a backport of:
- #377 (namespace expansion check; commit https://github.com/ros2/rclpy/commit/d6291cf5bbe682cf0beb18dc5556724829edb9ce).
- #382 (allowing parameter declaration without a value; commit https://github.com/ros2/rclpy/commit/72f55462e7fb9c0011904da9949557996ba56396).

[Backport] Fixes for parameter handling

---

rclpy/rclpy/executors.py

[Backport] Don't convert a timeout_sec to nsecs in executors

---

rclpy/rclpy/node.py
rclpy/rclpy/time_source.py
rclpy/test/test_node.py

Closes #395.
Signed-off-by: Juan Ignacio Ubeira <jubeira@ekumenlabs.com>

Declaring 'use_sim_time' when attaching node to time source.

---

rclpy/rclpy/node.py
rclpy/rclpy/time_source.py
rclpy/test/test_node.py

[Backport - dashing] Declaring 'use_sim_time' when attaching node to time source

---

rclpy/rclpy/__init__.py
rclpy/rclpy/node.py
rclpy/test/test_node.py
rclpy/test/test_utilities.py

Precisely what the title says. Connected to https://github.com/ros2/rcl/pull/477.

Adapt to '--ros-args ... [--]'-based ROS args extraction

---

rclpy/rclpy/parameter.py
rclpy/test/test_parameter.py

Providing a python dict inside a launch file that contains a list parameter, e.g.
```Python
composable_node = ComposableNode(parameters=[{"tag_ids": [9, 14]}])
```
or loading a YAML file (that contains `tag_ids: [9, 14]`)
```Python
composable_node = ComposableNode(parameters=["path/to/configuration.yaml"])
```
results in an error like:
`[ERROR] [launch]: Caught exception in launch (see debug for traceback): invalid parameter value (9, 14)`
because `[9, 14]` is recognised as `tuple` and not as `list`.
However, the parameter list logic only expects python lists.
This PR simply extends the parameter check to tuples to allow them to be used as iterables. There might be more places where a type check against list should be extended to all iterables.

accept tuples as parameter arrays

---

rclpy/rclpy/context.py
rclpy/rclpy/executors.py

Replaces https://github.com/ros2/rclpy/pull/402.
Fixes #398.
It solves two problems:
- The executor wasn't awaken when shutdown
- `_wait_for_ready_callbacks` was looping until yielding work, without checking if the context is valid.
Some error messages may still appear when shutting down contexts (similar to https://github.com/ros2/rclcpp/issues/812), but they are harder to reproduce.

Awake waitables on shutdown, check if context is valid

---

rclpy/rclpy/task.py
rclpy/test/test_task.py

This matches the behavior of `result` and `__await__` on asyncio Future's, and makes them a little more convenient to use in other coroutines.
* [`asyncio.futures.Future.result()`](https://github.com/python/cpython/blob/96b4087ce784ee7434dffdf69c475f5b40543982/Lib/asyncio/futures.py#L174-L175)
* [`asyncio.futures.Future.__await__`](https://github.com/python/cpython/blob/96b4087ce784ee7434dffdf69c475f5b40543982/Lib/asyncio/futures.py#L260)
Before
```python3
result = await future
if result is None:
raise future.exception()
```
After
```python3 
result = await future
```

Make Future result() and __await__ raise exceptions

---

rclpy/rclpy/callback_groups.py
rclpy/rclpy/client.py
rclpy/rclpy/executors.py
rclpy/rclpy/node.py
rclpy/rclpy/qos_event.py

Some of the type hints introduced in Dashing are not compatible with
Python 3.5. Where possible I tried to convert the hints to type comments
but for the type hints within function definitions that did not appear
to be possible so those hints were simply removed.
This is going to make backporting changes more challenging since we'll
have to:
1. Review backported changes for incompatible type hints.
2. Reconcile merge conflicts caused by the removal of type hints on the
dashing development branches.

[Dashing] Fix Python 3.5 compatibility by removing unsupported type hints.

---

rclpy/rclpy/node.py
rclpy/test/test_node.py

Precisely what the title says. Follow-up after https://github.com/ros2/rclcpp/pull/816 and https://github.com/ros2/rclpy/pull/405#discussion_r319069482. Necessary for https://github.com/ros2/rcl/pull/493 considering https://github.com/ros2/rclcpp/pull/784.

Force explicit --ros-args in cli args.

---

rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py

Precisely what the title says. This pull request makes `rclpy` raise if either an invalid or an unknown ROS argument is found.

Fail on invalid and unknown ROS specific arguments

---

rclpy/rclpy/executors.py
rclpy/rclpy/node.py
rclpy/rclpy/timer.py

* Renamed WallTimer to Timer and made it accept a clock
* create_timer() uses the node's clock by default, which uses ROS time by default
* Executor stores and reuses clock to pass to Timer

Timer uses ROS time by default

---

rclpy/rclpy/__init__.py
rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c

Addresses https://github.com/ros2/ros2cli/pull/322#issuecomment-525364023

Raise custom error when node name is not found

---

rclpy/rclpy/publisher.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py

fixes #418 . Publisher python's class can get the amount of subscribers that it has.
- Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8159)](https://ci.ros2.org/job/ci_linux/8159/)
- Arch [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4141)](https://ci.ros2.org/job/ci_linux-aarch64/4141/)
- OSX [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6644)](https://ci.ros2.org/job/ci_osx/6644/)
- Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8038)](https://ci.ros2.org/job/ci_windows/8038/)
There are some **test failures** which I think they are unrelated with this change. You can see for example: 
- Linux job [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&buil …

Provide subscription count from Publisher #418

---

rclpy/rclpy/node.py
rclpy/rclpy/qos.py
rclpy/test/test_node.py
rclpy/test/test_qos.py

Existing warnings are replaced with a new exception, InvalidQoSProfileException.
Resolves #430

Remove deprecated QoS functionality

---

rclpy/CHANGELOG.rst
rclpy/package.xml

This brings the version and CHANGELOG on `master` up to date with the `dashing` branch.
@nuclearsandwich what's your opinion on keeping `master`'s version up to date with the latest release?

Changelog version to master

---

rclpy/src/rclpy/_rclpy.c
rclpy/test/resources/test_node/test_parameters.yaml
rclpy/test/test_node.py

This pull request delegates all parameter parsing to `rcl`, as introduced in https://github.com/ros2/rcl/pull/508.

Take parameter overrides provided through the CLI.

---

rclpy/src/rclpy_common/src/common.c

It looks like adding an assert fixes a false-positive from cppcheck.
Previously, cppcheck was complaining that `rclpy_profile` may not be set [![Build Status](https://ci.ros2.org/buildStatus/icon?job=nightly_win_extra_rmw_rel&build=494)](https://ci.ros2.org/job/nightly_win_extra_rmw_rel/494/)
With this fix: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8136)](https://ci.ros2.org/job/ci_windows/8136/)

Make cppcheck happy

---

rclpy/rclpy/action/server.py
rclpy/test/test_action_server.py

Fixes #296.
Catch and print exception traceback from user-defined execute callback.
Added unit test to cover this case.

Action server: catch exception from user execute callback

---

rclpy/rclpy/action/server.py
rclpy/test/test_action_server.py

Backport #437 to Dashing.
Fixes #296.
Catch and print exception traceback from user-defined execute callback.
Added unit test to cover this case.

[dashing backport] Action server: catch exception from user execute callback (#437)

---

rclpy/test/test_utilities.py

Follow-up PR after https://github.com/ros2/rcl/pull/518.

Drop rclpy test_remove_ros_args_empty test case.

---

rclpy/rclpy/impl/rcutils_logger.py
rclpy/test/test_logging.py

As the title says, this make use of the python clock class for throttling logs. Follow up PR for [rclcpp](https://github.com/ros2/rclcpp/pull/879) and [rcutils](https://github.com/ros2/rcutils/pull/183)
- Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8452)](https://ci.ros2.org/job/ci_linux/8452/)
- Arch [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4345)](https://ci.ros2.org/job/ci_linux-aarch64/4345/)
- Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8345)](https://ci.ros2.org/job/ci_windows/8345/)
- OSX [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6868)](https://ci.ros2.org/job/ci_osx/6868/)
CI failures are unrelated to my changes.

Make use of Clock class for throttling logs

---

rclpy/rclpy/parameter.py
rclpy/test/test_parameter.py

Fixes #424. Adds support for double and int python arrays
- Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8489)](https://ci.ros2.org/job/ci_linux/8489/)
- Arch [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4377)](https://ci.ros2.org/job/ci_linux-aarch64/4377/)
- macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6904)](http://ci.ros2.org/job/ci_osx/6904/)
- Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8392)](http://ci.ros2.org/job/ci_windows/8392/)
Edit: Rerunning jobs

Support array parameter types

---

rclpy/CMakeLists.txt

I didn't see any duplication as in other tests, the following are just very substantial test files.
Based on a test local to my laptop, two test exceed the current 60 second timeout:
```
test_executor .....................   Passed   61.35 sec
test_node .........................   Passed  103.98 sec
```
And one is marginal:
```
test_time_source ..................   Passed   54.96 sec
```
Signed-off-by: Michael Carroll <michael@openrobotics.org>

Expand test timeout to deflake rmw_connext

---

rclpy/test/test_messages.py

As the title says, this fixes a particular test for opensplice.
I don't think this is a proper solution for the issue, but it keeps CI happy. What I was able to understand and find, is that opensplice caches the topics that are created. I know we are using a `deb`, but I took a peek to their [community edition](https://github.com/ADLINK-IST/opensplice) and it seems that the errors matched just fine. You can see that error [here](https://ci.ros2.org/job/ci_linux/8480/testReport/junit/rclpy.test.test_messages/TestMessages/test_unicode_string/).
As I was saying, when one creates a publisher/subscriber, it reaches a point where it creates a topic, calling this function
https://github.com/ADLINK-IST/opensplice/blob/c98e118a2e4366d2a5a6af8cbcecdf112bf9e4ab/src/kernel/code/v_topicImpl.c#L477 …

Fix the unicode test string for opensplice rmw implementation

---

rclpy/package.xml

add missing exec depend on rcl_interfaces

---

rclpy/rclpy/duration.py
rclpy/rclpy/time.py

Fix functions using `builtin_interfaces.msg.Duration` / `builtin_interfaces.msg.Time`.

fix import to use builtin_interfaces.msg

---

rclpy/rclpy/parameter_service.py

For parameters without a "." prefix, the code wasn't working as it should. Connected to https://github.com/ros2/ros2cli/pull/389

Get proper parameters with prefixes without dot separator

---

rclpy/rclpy/node.py

This seems to reduce hangs during test runs described in
https://github.com/ros2/build_cop/issues/248.
Another few hours of testing will convince me to strengthen that statement.
The handles corresponding to the destroyed objects *should* be getting
destroyed explicitly when self.handle.destroy() is called below. It
seems however that when running with Fast-RTPS it's possible to get into
a state where multiple threads are waiting on futexes and none can move
forward. The rclpy context of this apparent deadlock is while clearing
a node's list of publishers or services (possibly others, although
publishers and services were the only ones observed).
I consider this patch to be a workaround rather than a fix as I'm not particularly proud of how little I understand why the existing destruction …

Expressly destroy a node's objects before the node.

---

rclpy/rclpy/handle.py

fix new linter warnings as of flake8-comprehensions 3.1.0

---

rclpy/rclpy/qos.py

Allows to retrieve the name of the QoS value.

make short key of a QoS policy accessible

---

rclpy/rclpy/task.py
rclpy/test/test_task.py

Fixes #460 
If an executor is set, the future try to schedule done callback on it. If no executor is set, the future will invoke the done callbacks directly. This is sort of a hybrid of how `asyncio` and `concurrent.futures` handle this situation.
This should be backported to Dashing.

Future invokes done callbacks when done

---

rclpy/rclpy/action/server.py
rclpy/test/action/test_server.py

Backport #437 to Crystal.
Fixes #296.
Catch and print exception traceback from user-defined execute callback.
Added unit test to cover this case.
* Linux [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8727)](https://ci.ros2.org/job/ci_linux/8727/)
* Linux-aarch64 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4558)](https://ci.ros2.org/job/ci_linux-aarch64/4558/)
* macOS [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7129)](https://ci.ros2.org/job/ci_osx/7129/)
* Windows [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8642)](https://ci.ros2.org/job/ci_windows/8642/)
Edit: retrigger CI with test refactor (bb76362).
Edit: Unrelated linter errors and one [rosidl_parser test …

[crystal backport] Action server: catch exception from user execute callback (#437)

---

rclpy/rclpy/logging.py
rclpy/src/rclpy/_rclpy_logging.c

Follow up of https://github.com/ros2/rclpy/pull/458. Remove log severity hard coded and copied values from rcutils

Make use of rcutils log severity defined enum instead of duplicating code

---

rclpy/test/test_action_client.py

https://github.com/ros2/rcl/pull/541 triggered some [failures](https://ci.ros2.org/view/nightly/job/nightly_linux_release/1383/#showFailuresLink) in CI, though the problem was that the test wasn't creating an status publisher.

Fix test_action_client failures

---

rclpy/rclpy/duration.py
rclpy/rclpy/time.py

[backport dashing] fix import to use builtin_interfaces.msg

---

rclpy/package.xml

[backport dashing] add missing exec depend on rcl_interfaces

---

rclpy/rclpy/action/client.py

[crystal backport] Send feedback callbacks properly in send_goal() of action client (#451)

---

rclpy/rclpy/action/client.py

Fixes https://github.com/ros2/demos/issues/417
If multiple action servers are running with the same action name, then it is possible that both
servers will reply to requests from the action client. In the event that this happens, we avoid
crashing the code by ignoring the unexpected response and logging a warning for the user.
We have similar behavior for the action client implementation in rclcpp.
---
Example output running the Python action tutorials client node when there are two action servers running:
```sh
$ ros2 run action_tutorials_py fibonacci_action_client
[INFO] [1575593387.895730727] [fibonacci_action_client]: Received feedback: array('i', [0, 1, 1])
[INFO] [1575593387.896286699] [fibonacci_action_client]: Goal accepted :)
[WARN] [1575593387.897040932] …
```

Guard against unexpected action responses

---

rclpy/test/test_logging_rosout.py

Matches the change made in https://github.com/ros2/rcl/pull/549 to fix test failures in nightlies.

Use absolute topic name for rosout.

---

rclpy/rclpy/action/client.py

Backport #474 to Dashing.
If multiple action servers are running with the same action name, then it is possible that both
servers will reply to requests from the action client. In the event that this happens, we avoid
crashing the code by ignoring the unexpected response and logging a warning for the user.
We have similar behavior for the action client implementation in rclcpp.

[dashing backport] Guard against unexpected action responses

---

rclpy/src/rclpy/_rclpy.c

Fixes https://github.com/ros2/rclpy/issues/31
Replacing `RuntimeError` with new custom exception `RCLError`.

Replace RuntimeError with new custom exception RCLError

---

rclpy/rclpy/action/client.py

They are not compatible with Python 3.5 and accidentally introduced in #475.
Fixes #481

[dashing] Remove f-strings

---

rclpy/rclpy/node.py

It definitely returns a dictionary of strings to Parameters,
not a list.  The documentation and code was right, but just
the type annotation was wrong.

Fix the type annotation on get_parameters_by_prefix

---

rclpy/src/rclpy/_rclpy.c
rclpy/test/test_init_shutdown.py

Follow up PR after https://github.com/ros2/rclpy/pull/415, for the exact same set of reasons. We should probably backport this on the next Eloquent patch release.

Handle unknown global ROS arguments.

---

rclpy/rclpy/time_source.py
rclpy/test/test_time_source.py

See https://github.com/ros2/rclpy/pull/470#issuecomment-570629990.

Avoid a reference cycle between Node and TimeSource

---

rclpy/rclpy/parameter_service.py

See https://github.com/ros2/rclpy/pull/470#issuecomment-570629990.

Avoid reference cycle between Node and ParameterService

---

rclpy/CMakeLists.txt

The package provides the cmake macro 'rosidl_generator_py_get_typesupports'.
There was no error before since calling 'ament_lint_auto_find_test_dependencies' appears to
be calling find_package for us. Though, I'm not sure we want to rely on the ament_lint command
since I presume it is responsible for finding linter dependencies, which rosidl_generator_py is not.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8984)](http://ci.ros2.org/job/ci_linux/8984/)
* Linux-aarch64 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4756)](https://ci.ros2.org/job/ci_linux-aarch64/4756/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7356)](http://ci.ros2.org/job/ci_osx/7356/)
* Windows [![Build …

Find test dependency rosidl_generator_py

---

rclpy/rclpy/action/client.py

Backport #474 to Eloquent.
If multiple action servers are running with the same action name, then it is possible that both
servers will reply to requests from the action client. In the event that this happens, we avoid
crashing the code by ignoring the unexpected response and logging a warning for the user.
We have similar behavior for the action client implementation in rclcpp.

[eloquent backport] Guard against unexpected action responses

---

rclpy/CMakeLists.txt
rclpy/rclpy/serialization.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_serialization.py

Related to https://github.com/ros2/rosbag2/issues/232
Added a serialization submodule with functions for serializing and deserializing ROS messages.
I noticed an issue related to the serialization of floating-point values. I believe it's a bug related to loss of precision for 32-bit floating point values as (de)serialization happens with underlying C-types. I'm not sure how to resolve it at the moment, but left a TODO and test that if uncommented
demonstrates the bug.

Add wrappers for RMW serialize and deserialize functions

---

README.md

I figured it might be easier to direct users to an existing page, then asking them to build their own documentation. Feel free to close this if it's not a preferable change.

add online doc link

---

rclpy/rclpy/node.py
rclpy/test/test_node.py

@allenh1 now #427 is continued here as my previous repos were a lot messy

Support multiple parameters callback

---

rclpy/rclpy/__init__.py
rclpy/rclpy/context.py

The rcl functions aren't thread safe.
The upper layer has to lock.

Call init and shutdown thread safely

---

rclpy/CMakeLists.txt
rclpy/rclpy/node.py
rclpy/rclpy/qos.py
rclpy/rclpy/topic_endpoint_info.py
rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy_common/include/rclpy_common/common.h
rclpy/src/rclpy_common/src/common.c
rclpy/test/test_node.py
rclpy/test/test_qos.py
rclpy/test/test_topic_endpoint_info.py

**NOTE: DO NOT MERGE until [rmw #186](https://github.com/ros2/rmw/pull/186),  [rmw_implementation #72](https://github.com/ros2/rmw_implementation/pull/72) and [rcl #511](https://github.com/ros2/rcl/pull/511) are merged.**
This PR makes the necessary changes to implement [this](https://github.com/ros2/rmw/issues/151) feature request. The `RCLPY` layer needs to expose functions to the `ros2cli` layer such that `ros2 topic info <topic_name>` can display publisher and subscriptions information for the given `topic_name`.
Summary of changes:
- Added a new helper function in `common.h/c` to convert `rmw_topic_info_array_t` to a Python list of dictionaries.
- Added  `get_publishers_info_by_topic` and `get_subscriptions_info_by_topic` in `node.py`
- Added  `rclpy_get_publishers_info_by_topic` and …

Implement functions to get publisher and subcription informations like QoS policies from topic name

---

rclpy/test/test_node.py

This is for addressing the comment at https://github.com/ros2/rmw_connext/issues/380#issuecomment-576794050.
Since https://github.com/ros2/rmw_connext/pull/391 is ready for review, this change can be reviewed and merged along with it.

Enable test_get_publishers_subscriptions_info_by_topic() unit test for more rmw_implementations

---

rclpy/rclpy/client.py

The potential for the synchronous `call()` to cause a deadlock if called from inside a callback warrants a more serious warning than how it is currently being documented.

Embolden the warning in the docs about Client.call() potentially deadlocking

---

rclpy/rclpy/utilities.py

As discussed in these PRs https://github.com/ros2/ros2cli/pull/460, https://github.com/ros2/rmw_implementation/pull/85 and https://github.com/ros2/rmw_implementation/pull/84 I included in rclpy the utility function `get_available_rmw_implementations()`

Included get_available_rmw_implementations

---

rclpy/test/test_rate.py

The calculation of the max_jitter, which is a criterion for this test's success, was incorrect. This fixes the `abs()` calculation and adds min/max to the `__str__()` call.

Fixes max_jitter calculation

---

rclpy/rclpy/node.py
rclpy/rclpy/time_source.py
rclpy/test/test_node.py
rclpy/test/test_parameters_callback.py

Resolves #499 
Replaced by new API that supports multiple callbacks introduced in #457.
Replaced references to the old API with the new API.
Left tests for the old API that should be removed or updated when we remove
the deprecated API.
CI up to rclpy:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9254)](http://ci.ros2.org/job/ci_linux/9254/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4939)](http://ci.ros2.org/job/ci_linux-aarch64/4939/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7561)](http://ci.ros2.org/job/ci_osx/7561/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9174)](http://ci.ros2.org/job/ci_windows/9174/)
* …

Deprecate set_parameters_callback API

---

rclpy/test/test_node.py

Similar to changes in ros2/rcl#571 and ros2/rclcpp#1002
Fixes CI issue http://build.ros2.org/view/Fci/job/Fci__nightly-cyclonedds_ubuntu_focal_amd64/lastCompletedBuild/testReport/rclpy.src.ros2.rclpy.rclpy.test.test_node/TestNodeAllowUndeclaredParameters/test_get_publishers_subscriptions_info_by_topic/
Signed-off-by: Dan Rose <dan@digilabs.io>

Don't check lifespan on subscriber QoS

---

rclpy/rclpy/executors.py

rcl timer must create a guard condition in order to reset a canceled timer.
When calling rcl_create_timer, it will alls guard condition and it is need context.
Signed-off-by: Donghee Ye <donghee.ye@samsung.com>
It is related to : https://github.com/ros2/rcl/pull/589

Set context when creating Timer.

---

rclpy/rclpy/qos.py
rclpy/rclpy/qos_event.py
rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_qos_event.c
rclpy/test/test_qos_event.py

**_Depends on [ros2/rcl:535](https://github.com/ros2/rcl/pull/535)_**
Related to [this](https://github.com/ros2/ros2/issues/822) feature request. The design and implementation details can also be found there.
- Added `INCOMPATIBLE_QOS` event type to `QoSPublisherEventType` and `QoSSubscriptionEventType`
- Added support for the above events in the `QoSEventHandler`
- modified `test_qos_event.py` to include the new events.
Signed-off-by: Jaison Titus <jaisontj92@gmail.com>

Support for ON_REQUESTED_INCOMPATIBLE_QOS and ON_OFFERED_INCOMPATIBLE_QOS events

---

rclpy/rclpy/context.py
rclpy/test/test_destruction.py

Add support for on_shutdown functions not just methods.
Otherwise you get an error like this: 
```
File "./test_shutdown.py", line 37, in <module>
main()
File "./test_shutdown.py", line 22, in main
rclpy.get_default_context().on_shutdown(lambda : print("lambda on shutdown called"))
File "/opt/ros/eloquent/lib/python3.6/site-packages/rclpy/context.py", line 82, in on_shutdown
self._callbacks.append(weakref.WeakMethod(callback, self._remove_callback))
File "/usr/lib/python3.6/weakref.py", line 50, in __new__
.format(type(meth))) from None
TypeError: argument should be a bound method, not <class 'function'>
```
I also added unit tests to cover the callback types and the weak pointers being broken.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9836)](http://ci …

Add support for functions passed to Context.on_shutdown

---

rclpy/src/rclpy_common/src/common.c

Required because of change here https://github.com/ros2/rmw/blob/cbb5fc008f4304a62cf070663e3174c9f7970f9f/rmw/include/rmw/types.h#L40 in https://github.com/ros2/rmw/pull/189.

Avoid unsigned/signed comparison warning

---

rclpy/rclpy/exceptions.py

Resolves a flake8 error which would manifest as a KeyError at runtime
when this exception is created.
Spotted in [nightlies](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1519/testReport/rclpy/flake8/F999____rclpy_exceptions_py_74_34_/) it took a minute to reproduce since the flake8 version we install claims to be incompatible with [pyflakes 2.2.0](https://pypi.org/project/pyflakes/#history) which was just released, which is likely why the error has the F999 code.

use f-string to fix flake8 warning

---

rclpy/src/rclpy/_rclpy.c

rename rosidl_generator_c namespace to rosidl_runtime_c

---

rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py

Fixes https://github.com/ros2/rclpy/issues/529.
With this, policy generation from a running example can be reactivated in `sros2`.

Add enclaves introspection method in `Node`

---

rclpy/rclpy/node.py
rclpy/rclpy/qos_event.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_qos_event.py

Signed-off-by: Emerson Knapp <emerson.b.knapp@gmail.com>

Create a default warning for qos incompatibility

---

rclpy/rclpy/qos_event.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_qos_event.py

Reverts ros2/rclpy#536 until test failures in ros2cli can be addressed.
FYI @ivanpauno as the reviewer of #536.

Revert "Create a default warning for qos incompatibility"

---

rclpy/rclpy/qos_event.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_qos_event.py

Reverts https://github.com/ros2/rclpy/pull/543
Let's work on solving the aforementioned test failures before merging this pull request.

Revert "Revert "Create a default warning for qos incompatibility""

---

rclpy/rclpy/context.py
rclpy/src/rclpy/_rclpy.c

Connects to https://github.com/ros2/rcl/pull/579.
Connects to https://github.com/ros2/rclcpp/pull/998.

Ensure logging is initialized only once

---

rclpy/rclpy/executors.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py
rclpy/test/test_waitable.py

This implements the Python side of https://github.com/ros2/design/issues/259 and needs https://github.com/ros2/rcl/pull/619
The message info is simply returned as a dictionary. I figured if we want to encapsulate it into something else, we can always do that in Python. That shouldn't break API.
So far, only subscriptions have a method to take with info.

Add method to take with message_info

---

rclpy/src/rclpy/_rclpy.c

Fixes https://github.com/ros2/rclpy/issues/549.

Handle a failed rcl_take() call in rclpy_take().

---

rclpy/src/rclpy/_rclpy.c

Seen in https://ci.ros2.org/job/nightly_linux_release/1525/gcc/new/
This initializes `pytaken_msg` with `NULL`, and changes the check that `pytaken_msg` is not `NULL` to cover both raw and non-raw cases.

Fix warning about pytaken_msg maybe being uninitialized

---

rclpy/rclpy/executors.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py
rclpy/test/test_waitable.py

#542 made `rclpy_take()` return a 2-tuple of `(message, message_info)`, but wrote a test that expected `rclpy_take()` to return `None` when there is no message to take. However, it seems it actually crashed in that case. #550 fixed the crash by making `rclpy_take()` return `(None, None)` when there was no message to take from the middleware, but the test still expected `None`. This causes the test added in #542 to be flaky: https://github.com/ros2/rclpy/pull/551#issuecomment-620327015 . This PR fixes the issue by making the test expect `(None, None)` and documenting this return code in `rclpy_take()`.

Fix flaky test expecting wrong return type of rclpy_take

---

rclpy/rclpy/node.py

As mentioned at https://github.com/ros2/ros2cli/issues/500#issuecomment-620916411 and https://github.com/ros2/ros2cli/issues/500#issuecomment-621446097, when `create_publisher()`/`create_subscription()` fails to register QoS event callbacks, there should not remain a dangling `rmw_publisher_t`/`rmw_subscription_t` instance until Python performs garbage collection.
This pull request changes the behavior of `create_publisher()`/`create_subscription()` so that it eagerly destroys the just newly created `rmw_publisher_t`/`rmw_subscription_t` instance if an exception occurs.

Cleanup rmw publisher/subscription on exception

---

rclpy/test/test_timer.py

Fixes failures on Windows CI https://ci.ros2.org/view/nightly/job/nightly_win_rel/1537/testReport/junit/(root)/projectroot/test_timer/.

Skip flaky timer test on windows

---

rclpy/src/rclpy_common/src/common.c

Fixes https://github.com/ros2/ros2cli/issues/503 (i.e. the failure, not the hang). `rmw_time_t` instances were being forced into an `rcutils_time_duration_t` value (actually, first into a single `uint64_t` total nanosecond count, then into an unsigned `PY_LONG_LONG`, and then into an `rcutils_time_duration_t` i.e. an `int64_t`), causing overflows.
---
This happened in the first place because, RMW graph APIs are not currently bound to return anything reasonable for QoS related durations that do not make sense in a given context. That is the case for data reader (subscribers' backbone) lifespans in `rmw_connext_cpp` (see [here](https://github.com/ros2/rmw_connext/blob/7781a5e5982032be9460840e33646028af21129e/rmw_connext_shared_cpp/src/qos.cpp#L259) and …

Fix bad rmw_time_t to nanoseconds conversion.

---

rclpy/package.xml
rclpy/rclpy/impl/__init__.py
rclpy/test/__init__.py

New in Python 3.8, we should call os.add_dll_directory for directories
containing the DLLs we intend to import as well as their recursive
dependencies.
See https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew
Unblocks https://github.com/ros2/ci/pull/432 🤞

Explicitly add DLL directories for Windows before importing

---

rclpy/src/rclpy_common/include/rclpy_common/handle.h
rclpy/src/rclpy_common/src/handle.c

This documents `rclpy_handle_get_pointer_from_capsule()` and fixes a case where `RuntimeError` is set when an exception was already set by [PyCapsule_GetPointer](https://docs.python.org/3.7/c-api/capsule.html#c.PyCapsule_GetPointer).

Doc+fix rclpy_handle_get_pointer_from_capsule()

---

rclpy/src/rclpy_common/include/rclpy_common/handle.h
rclpy/src/rclpy_common/src/handle.c

* Doc+fix rclpy_handle_get_pointer_from_capsule()
Document parameters and return value
Fix case where RuntimeError is set when an exception is already set if
the PyCapsule is invalid or the PyCapsule name does not match.
Signed-off-by: Shane Loretz<sloretz@openrobotics.org>
Signed-off-by: Shane Loretz <sloretz@osrfoundation.org>
* Typos
Signed-off-by: Shane Loretz <sloretz@osrfoundation.org>
* Period at end of sentence
Signed-off-by: Shane Loretz <sloretz@osrfoundation.org>

[Foxy Backport] Doc+fix rclpy_handle_get_pointer_from_capsule() (#569)

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

Fixes #435 and reverts the changes in #563. 
Note that this PR makes `wait_for_ready_callbacks()` return a `Tuple[Task, WaitableEntityType, 'Node']` as it's type annotation specifies.  Before this method could return `None` and this was implicitly handled in the `spin_once` method for the single and multi thread executors.

Fix executor behavior on shutdown

---

rclpy/rclpy/impl/__init__.py

There have been numerous tickets / questions regarding problems loading the `rclpy` C extensions (just the latest example https://answers.ros.org/question/355064/ros2-modulenotfounderror-no-module-named-rclpy_rclpy/):
> ModuleNotFoundError: No module named ‘rclpy._rclpy’
This PR adds more context to this specific failure (the expected library not being found / existing). See the referenced PR to add the linked section to the docs.

improve error message if rclpy C extensions are not found

---

rclpy/CMakeLists.txt

This fixes the rclpy's `unknown macro` error on osx and windows, but it may not be the best strategy, cuz it will require manually pass in `include_dirs` to cppcheck in all other repos listed on this test report https://ci.ros2.org/view/nightly/job/nightly_win_rel/1576/testReport/
We've encountered the same error before and managed to fix it in this ticket https://github.com/ament/ament_lint/issues/116/ I'm not sure why this is happening again. 
Original issue https://github.com/ros2/ros2/issues/942

Pass rcutils_include_dirs to cppcheck 

---

pytest.ini

Connects to https://github.com/ros2/ros2/issues/951, which has further explanation and CI.

Add pytest.ini so tests succeed without warnings when run locally.

---

rclpy/rclpy/impl/__init__.py

[backport eloquent] improve error message if rclpy C extensions are not found

---

rclpy/rclpy/publisher.py

I stumbled upon https://stackoverflow.com/questions/62324936/ros2-typeerror-when-publishing-custom-message-to-topic-python the other day and thought: "Should be an easy fix, if you know what you did wrong" and this PR should help with that.

Add useful debug info when trying to publish the wrong type

---

rclpy/rclpy/qos.py

I found it helpful to print all the attributes of a `QoSProfile` instance.
CI builds testing `rclpy`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11393)](http://ci.ros2.org/job/ci_linux/11393/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6614)](http://ci.ros2.org/job/ci_linux-aarch64/6614/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9340)](http://ci.ros2.org/job/ci_osx/9340/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11286)](http://ci.ros2.org/job/ci_windows/11286/)

add QoSProfile.__str__

---

rclpy/test/test_rate.py

Fixes #513.
The test uses a timer with a rate of 100ms and expected each and every period to not have a jitter of more than 10ms. On a non-realtime system (especially Windows) that isn't a realistic expectation. Therefore this test has been flaky for a while: https://ci.ros2.org/view/nightly/job/nightly_win_rel/1613/testReport/rclpy.rclpy.test.test_rate/TestRate/test_rate_valid_period/
The patch continues to check for a maximum jitter of 10ms over the *average* of all deltas: `abs(runner.avg_period - PERIOD) <= PASS_MAX_AVERAGE_JITTER`. If there are some outliers the average should still be close.
But the check for the biggest individual delta is relaxed from 10ms to 25ms since checking for 10ms on each period is more of a performance test (which isn't satisfies across all platforms all …

relax rate jitter test for individual periods

---

rclpy/rclpy/qos_event.py

It's currently being set when there's no user specified "message lost" callback, which doesn't make sense.
The regression was introduced in https://github.com/ros2/rclpy/pull/572.
Partially addresses https://github.com/ros2/rclpy/issues/588.
There's another failure in the same test file, but not related to this one.

Default incompatible qos callback should be set when there's no user specified callback

---

rclpy/rclpy/node.py
rclpy/rclpy/publisher.py
rclpy/rclpy/qos_event.py
rclpy/rclpy/subscription.py
rclpy/test/test_qos_event.py

The other half of https://github.com/ros2/rclpy/pull/601 to completely fix https://github.com/ros2/rclpy/issues/588.
The assumption in comment https://github.com/ros2/rclpy/blob/be1deb6746ae260a88c47aa2399f3fd6f5bfddc9/rclpy/test/test_qos_event.py#L271-L272 was wrong because some of the objects created in the previous test cases were still around.

Destroy event handlers owned by publishers/subscriptions when calling publisher.destroy()/subscription.destroy()

---

rclpy/rclpy/node.py

Follow up of https://github.com/ros2/rclcpp/pull/929.

Use absolute parameter events topic name

---

rclpy/test/test_client.py
rclpy/test/test_node.py

Skip test with Connext which have been failing since they have been added:
* ros2/rclpy#545: http://build.ros2.org/view/Rci/job/Rci__nightly-connext_ubuntu_focal_amd64/42/testReport/rclpy.rclpy.test.test_client/TestClient/test_service_timestamps/
* ros2/rclpy#542: http://build.ros2.org/view/Rci/job/Rci__nightly-connext_ubuntu_focal_amd64/42/testReport/rclpy.rclpy.test.test_node/TestNodeAllowUndeclaredParameters/test_take/
The missing feature is ticketed in ros2/rmw_connext#405.
Before: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11858)](https://ci.ros2.org/job/ci_linux/11858/)
After: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11861)](https://ci.ros2.org/job/ci_linux/11861/)

skip test relying on source timestamps with Connext

---

rclpy/rclpy/executors.py

Fixes https://github.com/ros2/rclpy/issues/585.

MultiThreadedExecutor spin_until_future complete should not continue waiting when the future is done

---

pytest.ini

Backport #587 to Foxy.
This should help resolve one of the outstanding failures in ros2/ci#503

[foxy backport] Add pytest.ini so tests succeed without warnings when run locally. (#587)

---

rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py

Add the binding to c function rcl_node_get_fully_qualified_name, which will be used in the composition API. Refer to the cpp implementation:
https://github.com/ros2/rclcpp/blob/9a7e33f3b18dcc631fb36a0806a4868384e19477/rclcpp_components/src/component_manager.cpp#L214

Node get fully qualified name

---

rclpy/rclpy/publisher.py
rclpy/rclpy/qos_event.py
rclpy/rclpy/subscription.py
rclpy/test/test_qos_event.py

This makes debugging for the user a little easier.
This is the rclpy counterpart to https://github.com/ros2/rclcpp/pull/1286 .  @codebot FYI.

Add in the topic name when QoS events are fired.

---

rclpy/src/rclpy/_rclpy_logging.c

This makes it look more like a C statement.
This goes along with https://github.com/ros2/rcutils/pull/290 ; see that PR for CI.

Add in semicolon on RCUTILS_LOGGING_AUTOINIT.

---

rclpy/src/rclpy/_rclpy.c

When there is an error, it is possible that pyservice_names_and_types
is NULL, so make sure to use Py_XDECREF when cleaning up.

Make sure to use Py_XDECREF in rclpy_get_service_names_and_types

---

rclpy/rclpy/node.py
rclpy/rclpy/publisher.py
rclpy/rclpy/qos.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py
rclpy/test/test_qos.py
rclpy/test/test_qos_event.py
rclpy/test/test_topic_endpoint_info.py

Deprecate the verbose versions (e.g. `rclpy.qos.HistoryPolicy.RMW_QOS_POLICY_HISTORY_KEEP_LAST`) in favor of the less verbose versions (e.g. `rclpy.qos.HistoryPolicy.KEEP_LAST`), so we can remove the verbose version in a future.

Deprecate verbose qos policy value names

---

rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy.c
rclpy/test/test_node.py

Adds bindings for https://github.com/ros2/rcl/pull/835.
Equivalent to https://github.com/ros2/rclcpp/pull/1410.
Will be useful in https://github.com/ros2/rclpy/pull/635.

Add method in Node to resolve a topic or service name

---

rclpy/rclpy/qos.py
rclpy/test/test_qos_event.py

Fix error introduced in https://github.com/ros2/rclpy/pull/634.
`qos_policy_name_from_kind()` was previously accepting either `QoSPolicyKind` or an `int` (which wasn't properly documented in the type annotation).
The changes introduced on that function only accepted a `QoSPolicyKind`, this patch reintroduce `int` support.
Here https://github.com/ros2/rclpy/blob/0a3a2bf895e0e50a66433c185fa60b9aa9bf7632/rclpy/rclpy/qos_event.py#L251
`event.last_policy_kind` is an `int`.
The error wasn't caught because fastrtps doesn't support the feature, but it the following nightlies were failing:
- http://build.ros2.org/view/Rci/job/Rci__nightly-cyclonedds_ubuntu_focal_amd64/
- http://build.ros2.org/view/Rci/job/Rci__nightly-connext_ubuntu_focal_amd64/

qos_policy_name_from_kind() should accept either a QoSPolicyKind or an int

---

rclpy/rclpy/node.py

[foxy backport] Use absolute parameter events topic name (#612)

---

rclpy/rclpy/node.py
rclpy/rclpy/publisher.py
rclpy/rclpy/qos_event.py
rclpy/rclpy/subscription.py

[foxy] Destroy event handlers owned by publishers/subscriptions when calling publisher.destroy()/subscription.destroy() (#603)

---

rclpy/src/rclpy/_rclpy.c

If we got here through PyList_New failing, then pytopic_names_and_types
could be NULL.  Therefore, we need to use Py_XDECREF to handle
the situation.  Pointed out by clang static analysis.

Use Py_XDECREF for pytopic_names_and_types.

---

rclpy/CMakeLists.txt
rclpy/rclpy/node.py
rclpy/rclpy/qos_overriding_options.py
rclpy/test/test_qos_overriding_options.py

~Depends on https://github.com/ros2/rclpy/pull/636.~ (update:merged)
Equivalent to https://github.com/ros2/rclcpp/pull/1408.
It adds all the needed helper function and classes to enable qos configurability.
~I haven't yet modified `Node.create_publisher` and `Node.create_subscription`.~ (update: done)

Qos configurability

---

rclpy/rclpy/parameter_service.py

fix https://github.com/ros2/rclpy/issues/640
Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>

Fix Enum not being comparable with ints in get_parameter_types service

---

rclpy/rclpy/node.py

As @ivanpauno suggested, this PR fixes https://github.com/ros2/rclpy/issues/628

added wake executor to Node.create_subscription to fix issue 628

---

rclpy/rclpy/timer.py
rclpy/test/test_rate.py

It is a valid situation that may happen sometimes in threading,
so just quietly clean ourselves up and don't throw an
exception.
This resolves the failures we are seeing in the latest CI builds, e.g. https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/1447/testReport/junit/rclpy.rclpy.test/test_rate/test_shutdown_wakes_rate/ .
Here's a build where I ran the tests 10 times with this patch in place: https://ci.ros2.org/job/ci_linux-aarch64/8191/
@sloretz I'd appreciate a look by you, since you put this code in to start with.  I'm not sure if what I'm doing here is OK.

Don't throw an exception if timer canceled while sleeping.

---

rclpy/rclpy/parameter_service.py

[foxy] Fix Enum not being comparable with ints in get_parameter_types service

---

rclpy/docs/source/conf.py
rclpy/rclpy/qos.py

This PR makes `qos_profile_*` constants in [QoS documentation](http://docs.ros2.org/foxy/api/rclpy/api/qos.html#rclpy.qos.QoSProfile) visible. Their usage is recommended on https://index.ros.org/doc/ros2/Releases/Release-Dashing-Diademata/#rclpy but hiding them in the documentation may confuse users.
The problem is that sphinx-autodoc currently does not include module-level variables, unless these variables include `#:` style comments. See https://github.com/sphinx-doc/sphinx/issues/1063
I did not look into source files other than `qos.py`, because including variables using this workaround is tedious. It is better to wait for https://github.com/sphinx-doc/sphinx/issues/1063
Note that this PR is only for foxy. 
fixes the issue: https://github.com/ros2/docs.ros2.org/issues/49

include qos_profile_* constants in documentation

---

rclpy/rclpy/__init__.py

This fixes a sphinx warning 'Definition list ends without a blank line; unexpected unindent'

Fix docstring indent error in create_node

---

rclpy/CMakeLists.txt
rclpy/package.xml
rclpy/rclpy/logging.py
rclpy/src/rclpy/_rclpy_logging.c
rclpy/test/test_logging.py

Similar to https://github.com/ros2/rclcpp/pull/1509.

Add method to get the current logging directory

---

rclpy/src/rclpy/_rclpy_pycapsule.c
rclpy/src/rclpy_common/src/common.c

The first one in pycapsule is truly a bug; if destructor
was ever NULL, we would have reported an error and then
immediately dereferenced the NULL pointer, leading to a
crash.
The second one is a false positive.  The documentation for
PyErr_NoMemory() says that it always returns NULL, but
clang static analysis can't tell that just from the function
declaration.  Thus, call PyErr_NoMemory() to set the error,
and return NULL ourselves.

Fix two clang static analysis warnings.

---

rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_action.c

Pointed out by clang static analysis.  The comments on all of
them say "to avoid linter warning", but I don't see that warning
in our current code.  It may have been an older version.

Fix dead stores.

---

rclpy/src/rclpy/_rclpy.c

As pointed out by clang static analysis, 'pyresult_list' could
be NULL during cleanup, so make sure to use Py_XDECREF to check
for that possibility.

Use Py_XDECREF for pyresult_list.

---

rclpy/src/rclpy/_rclpy.c

As pointed out by clang static analysis, it is possible for
pynode_names_and_namespaces to be NULL during cleanup.  Thus
use Py_XDECREF everywhere to do that checking for us.

Use Py_XDECREF for pynode_names_and_namespaces

---

rclpy/src/rclpy_common/src/common.c

clang static analysis pointed out that the check for NULL here
was wrong.  We were checking the double pointer for NULL, not
the derefenced one that we just attempted to fill in.  Fix the
check to look at the dereferenced pointer.

Fix the NULL check for destroy_ros_message.

---

rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_action.c

And add an error message as appropriate.  clang static
analysis pointed out that this was a dead store.

Check the rcl_action return value on cleanup.

---

rclpy/test/test_create_while_spinning.py

This causes a segfault under CycloneDDS, and I don't see an easy way to prevent it from happening. Until we get to the bottom of that, just defer the call to destroy_node until after we know the spin thread has finished.
#663 tracks the issue that this change avoids.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13530)](http://ci.ros2.org/job/ci_linux/13530/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8430)](http://ci.ros2.org/job/ci_linux-aarch64/8430/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11253)](http://ci.ros2.org/job/ci_osx/11253/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13595)](http://ci.ros2.org/job/ci_windows/1359 …

Don't call destroy_node while spinning

---

rclpy/CMakeLists.txt
rclpy/package.xml

Part of #665
This uses Pybind11's CMake code to build the CPython extensions. Once this is merged, every module will be able to use Pybind11.

Use Pybind11's CMake code

---

rclpy/CMakeLists.txt

Fixes #687
The `clean_windows_flags` function from #681 needs to be applied to these targets.

Clean windows flags on _rclpy_pybind11 and _rclpy_action

---

rclpy/src/rclpy/_rclpy_action.cpp

The main change here is the use of RCLError to replace the repeated pattern of fetching the RCL error string.

Clean up exceptions in _rclpy_action

---

rclpy/src/rclpy/context.cpp

Fixes #689
`handle.h` is including `Python.h`. Including `pybind11/pybind11.h` first makes sure the `Py_DEBUG` macro is handled in a way that avoids a warning on Windows.

Include Pybind11 before Python.h

---

rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/context.cpp
rclpy/src/rclpy/context.hpp

Converts two `rcl_context_t` functions to pybind11, keeping the C to Python API the same.
part of #665
Make a couple functions use pybind11. These ones didn't benefit too much in the short term, but it brings `rclpy` a little closer to using pybind11 everywhere.

rclpy_ok and rclpy_create_context to pybind11

---

rclpy/rclpy/exceptions.py
rclpy/rclpy/node.py
rclpy/test/resources/test_node/test_parameters.yaml
rclpy/test/test_node.py

Equivalent to https://github.com/ros2/rclcpp/pull/1522.

Enforce static parameter types when dynamic typing is not specified

---

rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_action.cpp

This "C" variant of the QoS profile object seems to be used only when initializing other objects.
I'm not entirely sure, but I believe that this may have simply been an optimization, since we *know* that the object won't be touched again.
In any case, it will be easier to convert to pybind11 if we allow it to be destroyed normally.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13826)](http://ci.ros2.org/job/ci_linux/13826/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8687)](http://ci.ros2.org/job/ci_linux-aarch64/8687/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11534)](http://ci.ros2.org/job/ci_osx/11534/)
* Windows [![Build …

Set destructor on QoS Profile struct

---

rclpy/rclpy/node.py
rclpy/test/test_node.py

Add tests checking that declaring an statically typed parameter when undeclared parameters are allowed works as described in #1568 (comment).
See also https://github.com/ros2/rclcpp/pull/1575.
Pending: tests.

Fix static typing when allow undeclared

---

rclpy/CMakeLists.txt

I think that all of the new files we've been adding for the Pybind11 effort are causing cppcheck to take longer.

Bump the cppcheck timeout by 2 minutes

---

rclpy/src/rclpy/clock.cpp

Change the time jump time type to just rcl_time_jump_t.

---

rclpy/src/rclpy/client.cpp

I made a false assumption that tuple members which weren't specifically populated would somehow default to 'None'. This change explicitly sets the members to `py::none()`.
Regression caused by #701
Closes #710
Closes ros2/ros2cli#608
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13889)](http://ci.ros2.org/job/ci_linux/13889/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8741)](http://ci.ros2.org/job/ci_linux-aarch64/8741/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11597)](http://ci.ros2.org/job/ci_osx/11597/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13980)](http://ci.ros2.org/job/ci_windows/13980/)

Explicitly populate tuple with None

---

rclpy/CMakeLists.txt
rclpy/rclpy/duration.py
rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/duration.cpp
rclpy/src/rclpy/duration.hpp

Part of #665
Converts:
* rclpy_create_duration
* rclpy_duration_get_nanoseconds
CI (build: --packages-up-to rclpy test: --packages-select rclpy)
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13945)](http://ci.ros2.org/job/ci_linux/13945/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8783)](http://ci.ros2.org/job/ci_linux-aarch64/8783/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11648)](http://ci.ros2.org/job/ci_osx/11648/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14031)](http://ci.ros2.org/job/ci_windows/14031/)

Convert duration to pybind11

---

rclpy/CMakeLists.txt

This patches fixes an unusual duplication in the CMakeListst.txt. 
Debug CI up to `rclpy`:
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14075)](http://ci.ros2.org/job/ci_windows/14075/)

Look up pybind11 package once

---

rclpy/src/rclpy/qos_events.cpp

I think this will fix the warning on Windows Debug https://ci.ros2.org/job/ci_windows/14100/
Part of #665

Include pybind11 first to fix windows debug warning

---

rclpy/test/test_client.py
rclpy/test/test_node.py

This PR removes all references to `rmw_connext_cpp`, so that it may be replaced by `rmw_connextdds`.
The PR re-enables two tests which were previously disabled for Connext.
See [rticommunity/rmw_connextdds #9](https://github.com/rticommunity/rmw_connextdds/issues/9) for a list of related PRs, and an overview of all the changes required to replace [ros2/rmw_connext](https://github.com/ros2/rmw_connext) (`rmw_connext_cpp`) with [rticommunity/rmw_connextdds](https://github.com/rticommunity/rmw_connextdds) in the ROS2 source tree.

Replace rmw_connext_cpp with rmw_connextdds

---

rclpy/CMakeLists.txt
rclpy/rclpy/qos.py
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/qos.cpp
rclpy/src/rclpy/qos.hpp
rclpy/src/rclpy_common/include/rclpy_common/exceptions.hpp
rclpy/test/test_qos.py

Add API for checking QoS profile compatibility

---

rclpy/rclpy/node.py

Similar to https://github.com/ros2/rclcpp/pull/1590
Related to https://github.com/ros2/rclcpp/issues/1587

Document misuse of parameter callbacks

---

rclpy/rclpy/clock.py
rclpy/rclpy/time.py
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/clock.cpp
rclpy/src/rclpy/clock.hpp
rclpy/src/rclpy/time_point.cpp
rclpy/src/rclpy/time_point.hpp

Part of #665
This is a PR that refactors the code using `rcl_time_point_t` to use a `py::class_` definition. This is an example of what moving away from PyCapsules looks like for C structs that aren't being wrapped with `rclpy_handle_t` currently.

Use py::class_ for rcl_time_point_t

---

rclpy/src/rclpy/init.cpp
rclpy/src/rclpy/node.cpp

Precisely what the title says. This patch addresses a regression introduced in #715 and #735, which is causing debug assertions to fail on Windows. 
CI up to `rclpy`: 
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14127)](http://ci.ros2.org/job/ci_linux/14127/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8932)](http://ci.ros2.org/job/ci_linux-aarch64/8932/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11814)](http://ci.ros2.org/job/ci_osx/11814/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14224)](http://ci.ros2.org/job/ci_windows/14224/)
* Windows Debug [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14225) …

Make sure only non-empty std::vector of arguments are indexed

---

rclpy/CMakeLists.txt
rclpy/rclpy/client.py
rclpy/rclpy/executors.py
rclpy/rclpy/handle.py
rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/client.cpp
rclpy/src/rclpy/client.hpp
rclpy/src/rclpy/destroyable.cpp
rclpy/src/rclpy/destroyable.hpp
rclpy/src/rclpy/handle.cpp
rclpy/src/rclpy/handle.hpp
rclpy/src/rclpy/wait_set.cpp
rclpy/src/rclpy/wait_set.hpp
rclpy/src/rclpy_common/include/rclpy_common/exceptions.hpp
rclpy/src/rclpy_common/include/rclpy_common/handle.h
rclpy/src/rclpy_common/src/handle.c
rclpy/test/test_destruction.py
rclpy/test/test_waitable.py

This converts the Client functions to a C++ class. It includes a couple infrastructure things needed for the conversion
This is an RAII wrapper around the `rclpy_handle_t` type. This class can be deleted as soon as all types are no longer using `rclpy_handle_t`. When constructed it increments the handle's reference to block destruction, and when destructed it decrements the reference. This allows the `Client` to keep a node alive, so a `Client` won't be destructed after a node.
While refactoring I found while `std::shared_ptr<>` solves the destruction order issue, there's still a need to block destruction of an object while it's in use. This class implements that very similarly to how it's done for `rclpy_handle_t` types - though I did choose to make a design change.
When destruction is …

Convert Client to use C++ Class

---

rclpy/rclpy/duration.py
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/duration.cpp
rclpy/src/rclpy/duration.hpp
rclpy/src/rclpy/qos.cpp
rclpy/src/rclpy/qos.hpp

Part of #665
This is a PR that refactors the code using `rcl_duration_t` to use a `py::class_` definition. 

Use py::class_ for rcl_duration_t

---

rclpy/rclpy/qos.py
rclpy/src/rclpy/_rclpy_action.cpp
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/client.cpp
rclpy/src/rclpy/client.hpp
rclpy/src/rclpy/publisher.cpp
rclpy/src/rclpy/publisher.hpp
rclpy/src/rclpy/qos.cpp
rclpy/src/rclpy/qos.hpp
rclpy/src/rclpy/service.cpp
rclpy/src/rclpy/service.hpp
rclpy/src/rclpy/subscription.cpp
rclpy/src/rclpy/subscription.hpp
rclpy/test/test_qos.py
rclpy/test/test_topic_endpoint_info.py

Part of #665. Precisely what the title says. This data structure remains opaque, as it is redundant with those found in `qos.py`. I still feel the urge to rewrite `qos.py` in full, but I'll hold back.

Use py::class_ for rmw_qos_profile_t

---

rclpy/CMakeLists.txt
rclpy/src/rclpy/client.cpp
rclpy/src/rclpy/python_allocator.hpp
rclpy/test/test_python_allocator.cpp

Follow up from https://github.com/ros2/rclpy/pull/739#discussion_r603542254
This implements a C++ allocator that uses `PyMem_Malloc()` and `PyMem_Free()`, and uses it to replace `new/delete` in the `Client` class.

Add PythonAllocator

---

rclpy/rclpy/executors.py
rclpy/rclpy/service.py
rclpy/src/rclpy/_rclpy_action.cpp
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/client.cpp
rclpy/src/rclpy/service.cpp
rclpy/src/rclpy/service.hpp
rclpy/src/rclpy/service_info.cpp
rclpy/src/rclpy/service_info.hpp
rclpy/test/test_client.py

Part of #665
This refactors the code using `rmw_service_info_t` and `rmw_request_id_t` to use a py::class_ definition.

Use py::class_ for rmw_service_info_t and rmw_request_id_t

---

rclpy/test/test_python_allocator.cpp

Should fix https://ci.ros2.org/view/nightly/job/nightly_win_rel/1891/msbuild/new/
Part of #665

Fix windows warning by using consistent types

---

rclpy/docs/source/about.rst

Change index.ros.org -> docs.ros.org.

---

rclpy/rclpy/context.py

Fixes https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/1555/testReport/junit/(root)/projectroot/test_client/.
The issue might also be related to some of the pybind11 migration changes, but checking if the weak method is valid before calling it seems reasonable to do.

Check if shutdown callback weak method is valid before calling it

---

rclpy/src/rclpy/client.cpp
rclpy/src/rclpy/client.hpp
rclpy/src/rclpy/clock.cpp
rclpy/src/rclpy/clock.hpp
rclpy/src/rclpy/destroyable.cpp
rclpy/src/rclpy/publisher.cpp
rclpy/src/rclpy/publisher.hpp
rclpy/src/rclpy/qos_event.cpp
rclpy/src/rclpy/qos_event.hpp
rclpy/src/rclpy/service.cpp
rclpy/src/rclpy/service.hpp
rclpy/src/rclpy/subscription.cpp
rclpy/src/rclpy/subscription.hpp
rclpy/src/rclpy/timer.cpp
rclpy/src/rclpy/timer.hpp

Opening a PR for comment on top of #756. I think this fixes https://github.com/ros2/rclpy/pull/756#pullrequestreview-629124458 and https://github.com/ros2/rclpy/pull/756#issuecomment-814246782
This changes the [holder type of `Destroyable` subclasses use std::shared_ptr](https://pybind11.readthedocs.io/en/stable/advanced/smart_ptrs.html#std-shared-ptr) and makes the subclasses of `Destroyable` use `enable_shared_from_this`. This allows classes like `QoSEvent` to keep a shared_ptr to the publisher or subscription wrapper type without creating a copy of those instances.
Opening as draft because I think I should make a bug fix PR applying these changes to Timer/Clock.

[pub/sub 756 addition] use std::shared_ptr holder type and shared_from_this

---

rclpy/rclpy/executors.py
rclpy/rclpy/node.py
rclpy/rclpy/publisher.py
rclpy/rclpy/qos_event.py
rclpy/rclpy/subscription.py
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/client.cpp
rclpy/src/rclpy/client.hpp
rclpy/src/rclpy/clock.cpp
rclpy/src/rclpy/clock.hpp
rclpy/src/rclpy/destroyable.cpp
rclpy/src/rclpy/publisher.cpp
rclpy/src/rclpy/publisher.hpp
rclpy/src/rclpy/qos_event.cpp
rclpy/src/rclpy/qos_event.hpp
rclpy/src/rclpy/service.cpp
rclpy/src/rclpy/service.hpp
rclpy/src/rclpy/subscription.cpp
rclpy/src/rclpy/subscription.hpp
rclpy/src/rclpy/timer.cpp
rclpy/src/rclpy/timer.hpp
rclpy/src/rclpy/utils.cpp
rclpy/src/rclpy/utils.hpp
rclpy/src/rclpy/wait_set.cpp
rclpy/src/rclpy/wait_set.hpp
rclpy/src/rclpy_common/include/rclpy_common/common.h
rclpy/test/test_destruction.py
rclpy/test/test_node.py
rclpy/test/test_qos_event.py
rclpy/test/test_waitable.py

Part of #665.
This converts the Publisher and Subscription functions to a C++ classes. 
I have some issue with the QoSEvent destructor in some of the tests:
```bash
Thread 29 "python3" received signal SIGSEGV, Segmentation fault.
[Cambiando a Thread 0x7fffa3fff700 (LWP 338069)]
0x00000000006152cf in _is_legal_capsule (invalid_capsule=0x6d7160 "PyCapsule_GetPointer called with invalid PyCapsule object", capsule=0x3) at ../Objects/capsule.c:84
84	../Objects/capsule.c: No existe el archivo o el directorio.
(gdb) bt
#0  0x00000000006152cf in _is_legal_capsule (invalid_capsule=0x6d7160 "PyCapsule_GetPointer called with invalid PyCapsule object", capsule=0x3) at ../Objects/capsule.c:84
#1  PyCapsule_GetPointer (o=<unknown at remote 0x3>, name=0x7ffff5985881 "rcl_node_t") at …
```

Convert Publisher and Subscription to use C++ Classes

---

rclpy/rclpy/executors.py
rclpy/rclpy/qos_event.py
rclpy/rclpy/waitable.py

Fixes #760
Also make QoS event waitable use it. This fixes a crash when another
thread is spinning on a destroyed subscription using cyclonedds.
I was never able to reproduce the crash with `rqt_console`, but I can confirm it fixes the crash with this MRE https://github.com/ros2/rclpy/issues/760#issuecomment-815287677

Fix segfault by adding __enter__ and __exit__ to Waitable

---

rclpy/test/test_messages.py

This PR fixes `test_serialized_publish` from `test_messages.py`. The test creates a publisher for type `BasicTypes` but then tries to publish a message of type `Strings`.

Use correct type when creating test publisher

---

rclpy/test/test_client.py
rclpy/test/test_node.py

This PR restores some test exceptions in `test_client.py` and `test_node.py` to skip tests which check message timestamps on Windows.
These exceptions were removed in the process of replacing `rmw_connext_cpp` with `rmw_connextdds`, but they should have been kept for Windows, since timestamps are currently not supported on this platform.

Restore exceptions for Connext and message timestamps on Windows

---

rclpy/rclpy/executors.py
rclpy/rclpy/qos_event.py
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/action_client.cpp
rclpy/src/rclpy/action_client.hpp
rclpy/src/rclpy/action_server.cpp
rclpy/src/rclpy/action_server.hpp
rclpy/src/rclpy/wait_set.cpp
rclpy/src/rclpy/wait_set.hpp
rclpy/test/test_qos_event.py
rclpy/test/test_waitable.py

This converts the WaitSet functions to a C++ class. 

Convert WaitSet to use C++ Classes

---

rclpy/src/rclpy_common/include/rclpy_common/common.h

Removed unused structs. These structs were replaced by C++ Classes

Removed unused structs

---

rclpy/rclpy/executors.py
rclpy/rclpy/guard_condition.py
rclpy/rclpy/signals.py
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/guard_condition.cpp
rclpy/src/rclpy/guard_condition.hpp
rclpy/src/rclpy/wait_set.cpp
rclpy/src/rclpy/wait_set.hpp
rclpy/test/test_waitable.py

This converts the GuardCondition functions to a C++ class. 

Convert Guardcondition to use C++ classes

---

rclpy/src/rclpy/action_client.cpp
rclpy/src/rclpy/action_client.hpp
rclpy/src/rclpy/action_goal_handle.cpp
rclpy/src/rclpy/action_goal_handle.hpp
rclpy/src/rclpy/action_server.cpp
rclpy/src/rclpy/action_server.hpp
rclpy/src/rclpy/client.cpp
rclpy/src/rclpy/client.hpp
rclpy/src/rclpy/context.cpp
rclpy/src/rclpy/context.hpp
rclpy/src/rclpy/destroyable.cpp
rclpy/src/rclpy/destroyable.hpp
rclpy/src/rclpy/guard_condition.cpp
rclpy/src/rclpy/guard_condition.hpp
rclpy/src/rclpy/node.cpp
rclpy/src/rclpy/node.hpp
rclpy/src/rclpy/publisher.cpp
rclpy/src/rclpy/publisher.hpp
rclpy/src/rclpy/qos_event.cpp
rclpy/src/rclpy/qos_event.hpp
rclpy/src/rclpy/service.cpp
rclpy/src/rclpy/service.hpp
rclpy/src/rclpy/subscription.cpp
rclpy/src/rclpy/subscription.hpp
rclpy/src/rclpy/timer.cpp
rclpy/src/rclpy/timer.hpp
rclpy/src/rclpy/wait_set.cpp
rclpy/src/rclpy/wait_set.hpp
rclpy/test/test_qos_event.py

This is an alternative to https://github.com/ros2/rclpy/compare/ahcorde/pybind11-node...ahcorde/pybind11-node_option2?expand=1
It implementions option2 from this comment: https://github.com/ros2/rclpy/pull/771#discussion_r616961035
part of #665 via part of #771
This PR intentionally copies the `rclpy::Node`, `rclpy::Context`, etc ... classes instead of copying a shared_ptr to an `rclpy::*::RclPtrs` struct.
The interesting things in this PR are:
* Lamdas passed as deleters for `shared_ptr<rcl_*_t>` types must not capture `this`, because that will always be the pointer to the original instance, but the struct might finally be deleted by a copy instead. Capturing the variables they need (`node` in all cases) by value solved this in all cases.
* `test_qos_event` circumvents the node API to …

Intentionally copy rclpy:: objects instead of having RclPtrs structs

---

rclpy/rclpy/duration.py
rclpy/rclpy/topic_endpoint_info.py
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/test/test_time.py

Sample output for `ros2 topic pub /chatter std_msgs/String "data: hello"`:
```
$ ros2 topic info -v /chatter
Type: std_msgs/msg/String
Publisher count: 1
Node name: _ros2cli_30830
Node namespace: /
Topic type: std_msgs/msg/String
Endpoint type: PUBLISHER
GID: 2d.26.10.01.fb.93.9b.48.9d.7e.d3.24.00.00.08.03.00.00.00.00.00.00.00.00
QoS profile:
Reliability: RELIABLE
Durability: VOLATILE
Lifespan: Infinite
Deadline: Infinite
Liveliness: AUTOMATIC
Liveliness lease duration: Infinite
Subscription count: 0
```
Connected to https://github.com/ros2/ros2cli/pull/616

Print 'Infinite' for infinite durations in topic endpoint info

---

rclpy/rclpy/exceptions.py
rclpy/rclpy/node.py
rclpy/test/test_node.py

Parameters can now be declared without a default value and without an override.
Attempting to access a statically typed parameter that does not have value will raise an exception.
Getting dynamically typed parameters will return an unset parameter value.
This change is equivalent to that made in rclcpp: https://github.com/ros2/rclcpp/pull/1673

Allow declaring uninitialized parameters

---

rclpy/rclpy/context.py

Follow up to https://github.com/ros2/rclpy/pull/803#discussion_r685518676
~~marking as Draft because I didn't test this locally~~ **edit: ready for review** - testing `rclpy` on CI: [![Build Status](https://ci.ros2.org/job/ci_linux/15025/badge/icon)](https://ci.ros2.org/job/ci_linux/15025/)

Set Context.__context to None in __init__

---

rclpy/rclpy/impl/logging_severity.py
rclpy/rclpy/impl/rcutils_logger.py
rclpy/rclpy/logging.py

This is a follow up to discussion in https://github.com/ros2/rclpy/pull/776.
LoggingSeverity enum is moved to its own module and it is imported both from logging and rcutils_logger modules.
This change should save a tiny bit of time in doing import for every call inside log method.

Lift LoggingSeverity enum as common dependency to logging and rcutils_logger modules

---

rclpy/rclpy/context.py

Fixes https://github.com/ros2/rclpy/pull/518#discussion_r636538358

Call Context._logging_fini() in Context.try_shutdown()

---

rclpy/test/test_client.py

`test_service_timestamps` has started failing lately with:
```
>                   self.assertNotEqual(0, header.source_timestamp)
E                   AttributeError: 'NoneType' object has no attribute 'source_timestamp'
```
See the test history here:
https://build.ros2.org/job/Rci__nightly-connext_ubuntu_focal_amd64/429/testReport/rclpy.rclpy.test.test_client/TestClient/test_service_timestamps/history/
I'm not sure what's the underlying issue that causes the header to be none, but catching that before trying to use the variable should allow the test to fail gracefully instead of throwing an error.
---
https://github.com/osrf/buildfarmer/issues/224

👩‍🌾 Check that header is not none before accessing it in test

---

rclpy/rclpy/parameter.py
rclpy/test/test_parameter.py

This function is particular useful when processing a GetParameters service request.
Tools like ros2param implement this function locally, but it would be nice to have a common implementation to avoid duplication.
This function was adapted from the implementation in ros2param: https://github.com/ros2/ros2cli/blob/1f4a3aaf7b930830b3fa04773715bf93ea65693e/ros2param/ros2param/api/__init__.py#L31

Add convert function from ParameterValue to Python builtin

---

rclpy/rclpy/executors.py

This seems to fix an issue in #605 
The issue is reproducible with the snippet below. It is using a `MultiThreadedExecutor` and sending sequential client requests to a server on a different node in the same executor. By the 3rd or 4th request, the observed behavior is the server stops responding. I observed with print statements in `MultiThreadedExecutor.spin_once_until_future_complete()` that the number of calls to it seems to grow very rapidly with each new client request.
I suspect that the previous future's done callbacks are being executed while the next future waits. The first future's done callbacks wake the executor, and that causes `MultiThreadedExecutor.spin_once_until_future_complete()` to be called again on the next future, which adds another done callback to the next future. …

Only add one done callback to a future

---

rclpy/rclpy/publisher.py
rclpy/src/rclpy/publisher.cpp
rclpy/src/rclpy/publisher.hpp
rclpy/test/test_publisher.py

Add wait_for_all_acked support

---

rclpy/test/test_publisher.py

Address #824
For connextdds, current timeout seting is too small in test_wait_for_all_acked

Increase the timeout in test_publisher.test_wait_for_all_acked

---

rclpy/src/rclpy/client.cpp
rclpy/src/rclpy/service.cpp

Signed-off-by: Lei Liu <Lei.Liu.AP@sony.com>

Fix memory leak.

---

rclpy/CMakeLists.txt
rclpy/rclpy/context.py
rclpy/test/test_context.py

Split from #858 
`WeakMethod` throws an exception if the callable is not a bound method, which prevented using free functions as a shutdown callback. This allows free functions by storing them with `weakref.ref`. 
Example exception before this PR
```python
9: >           raise TypeError("argument should be a bound method, not {}"
9:                             .format(type(meth))) from None
9: E           TypeError: argument should be a bound method, not <class 'function'>
```

Make context.on_shutdown allow free functions as shutdown callbacks

---

rclpy/rclpy/clock.py
rclpy/rclpy/time.py

Split from #858
This fixes a circular import between `time.py` and `clock.py`. Both need the `ClockType` type, which comes from `_rclpy_pybind11`, but `time.py` was importing it from `clock.py`. That forced `clock.py` to import `Time` inside functions that used it.
I also added type annotations where I touched code.

Fix time.py and clock.py circular import

---

rclpy/rclpy/clock.py
rclpy/test/test_clock.py

Split from #858
This documents `JumpThreshold`, and forbids passing zero Durations.
JumpThreshold `min_forward` and `min_backward` are disabled in `rclpy` when `None` is passed. In `rcl` the thresholds are disabled when set to 0. I chose to make `JumpThreshold` forbid zero Durations so that there's only one way to disable them. Otherwise, it's easy to pass a zero duration and think it's requesting the smallest possible time jump.

Improve JumpThreshold documentation and forbid zero durations

---

rclpy/src/rclpy/_rclpy_logging.cpp

There's no `rclpy._rclpy_logging_pybind11` module, the deleted line was just overriding the original docs.

Don't override `rclpy._rclpy_pybind11` docs

---

rclpy/rclpy/clock.py
rclpy/test/test_clock.py

Split from #858
This allows `JumpHandle` to be used with Python's `with` keyword, guaranteeing the time jump callback is unregestered even if an exception is thrown.

Add __enter__ and __exit__ to JumpHandle

---

rclpy/rclpy/clock.py
rclpy/test/test_clock.py

Add Clock.sleep_for using sleep_until

---

rclpy/rclpy/topic_endpoint_info.py
rclpy/test/test_topic_endpoint_info.py

address https://github.com/ros2/ros2cli/issues/667
Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>

print history and depth via topic info -v

---

rclpy/rclpy/node.py

In short, same as PR #647 but on foxy branch.
I was facing a problem where, when creating a subscriber (`create_subscription`) for a node that is already spinning the callback would never run (when it should run). It would only run after calling another random node method, for example creating a timer.
After searching we found out that the problem is that `create_subscription` wasn't calling `_wake_executor` so the node wasn't really aware of the new callback, until some other method called `_wake_executor`.
This problem has been fixed already but only in the master branch  (on PR #647) , so I thought it could be important to bring this fix to the foxy branch as well.
Signed-off-by: Leonardo Oliveira Wellausen <leonardo.wellausen@karelics.fi>

Adding _wake_executor to create_subscription on foxy

---

rclpy/rclpy/__init__.py
rclpy/rclpy/context.py
rclpy/rclpy/utilities.py

Needed by https://github.com/ros2/ros2cli/pull/683.
I'm not sure if this is the ideal approach, maybe init()/shutdown() are doing too much (?).
I'm open to alternatives.

Make rclpy.try_shutdown() behavior to follow rclpy.shutdown() more closely

---

rclpy/CMakeLists.txt
rclpy/package.xml
rclpy/rclpy/lifecycle.py
rclpy/rclpy/lifecycle/__init__.py
rclpy/rclpy/lifecycle/managed_entity.py
rclpy/rclpy/lifecycle/node.py
rclpy/rclpy/lifecycle/publisher.py
rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/lifecycle.cpp
rclpy/src/rclpy/lifecycle.hpp
rclpy/src/rclpy/service.cpp
rclpy/src/rclpy/service.hpp
rclpy/test/test_lifecycle.py

Fixes https://github.com/ros2/rclpy/issues/604.
I took into account the feedback provided here https://github.com/ros2/rclcpp/issues/1846, so you don't need to manually call on_activate/on_deactivate for managed entities like `LifecyclePublisher`.
I'm open to revert that bit, though I think it's a good idea.
~I have only manually tested that the lifecycle node services work correctly.
I have not tested the lifecycle publisher at all.~
This PR has tests now.
~I could write some automated tests for the lifecycle builtin services though.~
Done as well.
~This is not ready to be merged, though early feedback is appreciated anyway.~
This is ready now.
~I'm working to add a demo equivalent to [demos/lifecycle](https://github.com/ros2/demos/tree/master/lifecycle), but that shouldn't block this …

Implement managed nodes

---

rclpy/rclpy/topic_endpoint_info.py

follow-up for https://github.com/ros2/rclpy/pull/849 (see comment https://github.com/ros2/rclpy/pull/849#discussion_r774688205)

QoS history depth is only available with KEEP_LAST.

---

rclpy/CMakeLists.txt

We can remove most of the hacks we were carrying around, but we also need to add in one more overload of the Python executable so pybind11 properly detects things on Windows Debug.
Depends on https://github.com/ros2/pybind11_vendor/pull/10 (CI is over in that PR)

Update to pybind11 2.7.1

---

rclpy/rclpy/client.py
rclpy/rclpy/executors.py

Proposal to fix multi-threaded race condition in client.call_async as described in #870

Fix multi-threaded race condition in client.call_async

---

rclpy/docs/source/conf.py

The docs version number has not been updated since it was created.
Maybe it would be a good idea to read the version directly from package.xml?

Update documentation version number

---

rclpy/rclpy/task.py

I noticed this can happen when a service client does not receive a response from a server and the client times out.
Loosely related to https://github.com/ros2/rclpy/issues/367.

Document that Future.result() may return None

---

rclpy/rclpy/node.py

Remove -> bool annotation for destroy_node as mentioned in [issue #886](https://github.com/ros2/rclpy/issues/886).

Remove -> bool annotation for destroy_node #886

---

rclpy/test/test_qos_event.py

This PR removes the custom code paths that were checking `rmw_get_implementation_identifier()` on events-related tests.
Connected to ros2/rmw_fastrtps#583

Remove fastrtps customization on tests

---

rclpy/src/rclpy/action_server.cpp

Otherwise this leaks memory every time a status is published.
Discovered while using valgrind to track down an unrelated problem.

Make sure to free the goal_status_array when done using it.

---

rclpy/rclpy/action/client.py
rclpy/rclpy/action/server.py

This ensures that the underlying object won't be freed when
e.g. a WaitSet is still using it.
This should solve https://github.com/ros2/geometry2/issues/503 .  Still in draft because @sloretz and I are still working out some of the details.

Make sure to take out contexts on Action{Client,Server}.

---

rclpy/rclpy/action/client.py
rclpy/rclpy/action/server.py

In particular, it should never really be the case that the
underlying handle that we are using is None.  That only seemed
to be happening because we were double destroying; once in
the explicit call to destroy(), and once in __del__.  But
we don't actually need __del__; during garbage collection, we'll
drop the reference to the handle and then the underlying object
will get freed anyway.  Just remove all of that extraneous
infrastructure here.
Besides being a lot cleaner, this is also likely responsible for warnings during tests on the buildfarm like:
```
04:24:41.497 144: [test_action_client-3] Exception ignored in: <function ActionClient.__del__ at 0x00000245450633A0>
04:24:41.497 144: [test_action_client-3] Traceback (most …
```

Properly implement action server/client handle cleanup.

---

rclpy/src/rclpy/_rclpy.c

Affects middlewares like Cyclone DDS that fire events not supported by ROS2.
Signed-off-by: Erki Suurjaak <erki@lap.ee>

Fix crash on spinning raw subscription when publishes closes (#827).

---

rclpy/src/rclpy/timer.cpp
rclpy/src/rclpy/timer.hpp
rclpy/test/test_timer.py

aligned with https://github.com/ros2/rcl/pull/963 and https://github.com/ros2/rclcpp/pull/1893

time_until_next_call returns max if timer is canceled.

---

rclpy/rclpy/node.py
rclpy/test/test_create_node.py

Allow to create a Node with 'use_sim_time' parameter in parameter overrides.
Avoid exception `
rclpy.exceptions.ParameterAlreadyDeclaredException: ('Parameter(s) already declared', ['use_sim_time'])
`

Avoid exception in Node constructor when use override for 'use_sim_time'

---

rclpy/rclpy/executors.py
rclpy/rclpy/subscription.py
rclpy/src/rclpy/subscription.cpp
rclpy/test/test_subscription.py

The cpp `Subscription.take_message()` was also updated to include `reception_sequence_number`/`publication_sequence_number` in the message info.
This should be merged AFTER the API freeze ends.

Allow to create a subscription with a callback that also receives the message info

---

rclpy/rclpy/qos.py
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/qos.cpp

If users set certain a QoS policy to 'best available', then the middleware will query the graph
for endpoint info before creating a subscription or publisher.
A QoS policy will be selected such that is matches the majority of endpoints while maintaining
the highest level of service possible.
Connects to https://github.com/ros2/rmw/pull/320

Expose 'best available' QoS policies

---

rclpy/test/test_client.py
rclpy/test/test_node.py

Fix https://github.com/ros2/rclpy/issues/934

Avoid causing infinite loop when message is empty

---

rclpy/src/rclpy/_rclpy_action.c

Based on the comment following the patched line, it appears that the error condition is  inverted. 
This avoids the thrown exception as explained in #801, and similar scenarios where action servers leave/disappear/restart while rmw_cyclonedds_cpp is the rmw implementation

[foxy] fix inverted error code check for action client take

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

This PR closes https://github.com/ros2/rclpy/issues/944 by allowing for a `executor.shutdown` call to happen in a callback. 
A caveat of the proposed approach is that this does raise an `InvalidHandle` but it appears to be harmless and we just catch it. This is what is [currently used](https://github.com/ros2/rclpy/blob/7ffe94865f38c67812799bf5751a8f0f3f918c25/rclpy/rclpy/executors.py#L525-L564) in `rclpy`.  Alternatively we could track whether or not if a `GuardCondition` has been destroyed

fix rclpy.shutdown() from hanging when triggered from callback

---

rclpy/rclpy/node.py

address https://github.com/ros2/rclpy/issues/879

name and type in descriptor(s) is ignored via declare_parameter(s).

---

rclpy/docs/source/conf.py
rclpy/package.xml

ROS2's sphinx-generated documentation is overwhelmingly in the Read the Docs theme. This PR moves `rclpy` from the current built-in alabaster theme to read the docs. RTD is also (at least in my experience) nicer to use.

Change sphinx theme to readthedocs

---

rclpy/rclpy/node.py

This makes it match Galactic, Humble, and Rolling.
Interestingly, this was fixed in Foxy before: https://github.com/ros2/rclpy/pull/482 .  However, it seems to have been reverted later on in #457 , so this updates the Foxy version with what is in later ROS distributions.

[Foxy]: Fix type annotation for get_parameters_by_prefix.

---

rclpy/src/rclpy/_rclpy.c
rclpy/src/rclpy_common/src/common.c

* Operating System: Ubuntu 20.04.2 LTS (5.8.0-41-generic)
* Version or commit hash: https://github.com/ros2/rclpy/commit/1bebfa252d1314ac636bf31d2a86dbe28f759e0c
* Client library (if applicable): rclpy (foxy)
* Python version: python 3.8
Steps to reproduce issue: 
> Run the below code on env which has lots of topics.
```python
import rclpy
from rclpy.node import Node
class MonitoTopics(Node):
def __init__(self):
super().__init__('monitor_topics')
self._timer = self.create_timer(
timer_period_sec=1.0, 
callback=self._monitor_topics)
def _monitor_topics(self):
for topic_name, topic_types in self.get_topic_names_and_types():
del topic_types
for topic_info in self.get_publishers_info_by_topic(topic_name):
del topic_info
for topic_info in self.get_subscriptions_info_by_topic(topic_name):
del …
```

[Foxy] fix memory leak for get_(publishers|subscriptions)_info_by_topic.

---

rclpy/src/rclpy/context.cpp
rclpy/src/rclpy/timer.hpp

I know this is probably a corner case, but I'm building humble using gcc 7.5 on an older version of linux. It has partial support for C++17, and adding these resolved my build errors. Could we get these pushed into rolling and humble branches? It seems for modern gcc or llvm these aren't necessary.

Fix gcc 7.5 build errors

---

rclpy/rclpy/node.py
rclpy/test/test_node.py

This PR supports adding new parameters registered callbacks namely `pre_set_parameter` and `post_set_parameter` callback to node API. Full description can be found in rclcpp version of the PR here https://github.com/ros2/rclcpp/pull/1947
**Design document:** https://github.com/ros2/rclcpp/blob/deepanshu/local-param-changed-callback-support/rclcpp/doc/proposed_node_parameter_callbacks.md
**Demo node:** https://github.com/ros2/demos/pull/565
**rclcpp ticket:**  https://github.com/ros2/rclcpp/pull/1947
**Related discussion:** https://github.com/ros2/rclcpp/issues/1190, https://github.com/ros2/rclcpp/issues/609
Signed-off-by: deepanshu [deepanshubansal01@gmail.com](mailto:deepanshubansal01@gmail.com)

Support for pre-set and post-set parameter callback.

---

rclpy/rclpy/action/client.py
rclpy/rclpy/action/server.py

Addresses https://github.com/ros2/rclpy/issues/969

Create sublogger for action server and action client

---

rclpy/rclpy/node.py
rclpy/test/test_action_graph.py
rclpy/test/test_node.py

Related #823 
Signed-off-by: Gonzalo de Pedro <gonzalo@depedro.com.ar>

Adds wait_for_node

---

rclpy/src/rclpy/node.cpp

ament_cpplint recognizes headers with extensions in angle brackets as c system headers
excepts some headers defines in _CPP_HEADERS
Signed-off-by: Chen Lihui <lihui.chen@sony.com>

fix cpplint

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

https://github.com/ros2/rclcpp/pull/2030 for `rclpy`

Set the default number of threads of the MultiThreadedExecutor to 2

---

rclpy/rclpy/utilities.py

I noticed this function was missing a docstring while telling someone about it.

Document rclpy.utilities.remove_ros_args

---

README.md

Update the instructions for building docs to work on Jammy.
I don't think CI is required for this one. Nothing tests the README at the root of the repository.

Update docs instructions for Jammy

---

rclpy/docs/source/api.rst
rclpy/docs/source/api/time.rst
rclpy/rclpy/time.py

This adds documentation for the Time class. Here's how it looks.

Document rclpy.time.Time class

---

rclpy/CMakeLists.txt
rclpy/rclpy/wait_for_message.py
rclpy/test/test_wait_for_message.py

Add feature of wait for message.

Add feature of wait for message (#953).

---

rclpy/rclpy/qos.py
rclpy/test/test_node.py
rclpy/test/test_publisher.py
rclpy/test/test_qos.py

It really doesn't make much sense to have a KeepLast depth of 0; no data could possibly be stored. Indeed, the underlying DDS implementations don't actually support this. It currently "works" because a KeepLast depth of 0 is assumed to be system default, so the RMW layer typically chooses "1" instead. But this isn't something we should be encouraging users to do, so add a warning.
This is the rclpy companion PR to https://github.com/ros2/rclcpp/pull/2048

Add in a warning for a depth of 0 with KEEP_LAST.

---

rclpy/test/test_callback_group.py

Following up on the suggestion in #1039, this pull request adds a test case which checks if the parallel processing of callback is working when the reentrant callback group and the multithreaded executor are used. This behavior was broken recently, and the test should ensure that future regressions are noticed.
The test case is based on the reproduction example from #1039. I put it together with the callback group test cases, but we could put it somewhere else.

Add parallel callback test

---

rclpy/CMakeLists.txt
rclpy/test/test_parameter_client.py
rclpy/test/test_parameter_service.py

Address this comments https://github.com/ros2/rclpy/pull/1041#issuecomment-1318956122  
I move test code for not depending on parameter client.  
And remove  test_parameter_client.py in CMakeLists.txt since #1033 added this file.   
@ivanpauno Please help to review it, and then I will add this test to backport of #1033.

Rewrite test code without depending on parameter client

---

rclpy/docs/source/api.rst
rclpy/docs/source/api/clock.rst
rclpy/rclpy/clock.py

This adds a documentation page for the clock module, and improves the documentation in that module slightly.

Add documentation page for rclpy.clock

---

rclpy/rclpy/parameter_client.py
rclpy/test/test_parameter_client.py

This essentially is just a subscription to the /parameter_event topic, but makes it match the rclcpp API of the same name.
This should fix https://github.com/ros2/rclpy/issues/1060

Add on_parameter_event method to the AsyncParameterClient.

---

rclpy/test/test_publisher.py

Signed-off-by: Crola1702 <cristobal.arroyo@ekumenlabs.com>
[`do_test_topic_name` docstring](https://github.com/ros2/rclpy/blob/rolling/rclpy/test/test_publisher.py#L60) is different from others in rclpy (e.g., [utilities](https://github.com/ros2/rclpy/blob/d2901dded38267b59b6d492cb64425c5bcacf650/rclpy/rclpy/utilities.py#L46)), this causes a test regression in pep257 with the new pydocstyle 6.2.0 version.
This PR changes this docstring format, so it can pass pep257 tests. 
Reference builds:
* [Linux](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2535/), [Aarch64](https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/2219/), [Windows](https://ci.ros2.org/view/nightly/job/nightly_win_deb/2596/)

Fix `test_publisher` linter for pydocstyle 6.2.2

---

rclpy/CMakeLists.txt

This fixes https://github.com/ros2/rclpy/issues/1064. 
When building with Clang, tell cmake to link atomic
to the _rclpy_pybind11 target.
Signed-off-by: Sebastian Freitag
<sebastian.freitag@pylot.tech>

Issue 1064

---

rclpy/src/rclpy/utils.cpp

The unique_ptr way to do this works, but clang static analysis complains that data could be leaked if the construction of the unique_ptr fails.  Since this code is really old, switch to using RCPPUTILS_SCOPE_EXIT, which is our more modern way to deal with this problem.

Use RCPPUTILS_SCOPE_EXIT to cleanup unparsed_indices_c.

---

rclpy/CMakeLists.txt

This is so we can use clang static analysis to be used with rclpy.

Force C++17 support on.

---

rclpy/rclpy/executors.py

Fixes #983 while preserving functionality as reported in #1016 
Implementation follows @fujitatomoya 's [recommendation](https://github.com/ros2/rclpy/issues/983#issuecomment-1271782711). Rather than save the executor's returned future, I save the handler since the future doesn't seem to have access to the exception.

Fix #983 by saving future and checking for + raising any exceptions

---

rclpy/rclpy/subscription.py
rclpy/src/rclpy/subscription.cpp
rclpy/src/rclpy/subscription.hpp
rclpy/test/test_subscription.py

This is available in the rcl and rclcpp layers, just seems like an oversight that it wasn't available here. I'll also be using this in some upcoming work.

Add in subscription.get_publisher_count()

---

rclpy/CMakeLists.txt

This is related to issue #1095 where building ROS 2 from source would fail at this package on OSX Ventura 13.2.1 with clang. I know MacOS is a tier 3 platform, but this pull request is very minuscule and doesn't rupture the build or its times significantly, just opening up other opportunities. Apple Clang cannot process atomic early in the build process so it just can't be included in the main `CMakeLists.txt` but it doesn't cause any issues later in this package so it is included elsewhere.

Solving Atomic undefined on OSX with clang

---

rclpy/CMakeLists.txt
rclpy/package.xml

It is required for both, so set it for both and find it in the CMakeLists.txt as appropriate.

Make rcl_interfaces a build and exec dependency.

---

rclpy/rclpy/topic_endpoint_info.py
rclpy/test/test_topic_endpoint_info.py

Part of ros2/ros2#1159
Enables https://github.com/ros2/rclpy/pull/1104 and https://github.com/ros2/ros2cli/pull/816 as backports for first Iron sync (post-release). 
Adds extra line for "Topic type hash:" to string representation of  `TopicEndpointInfo`, in case any parsers expect specific format from that string.

Stub type hash value line in TopicEndpointInfo string

---

rclpy/test/test_parameter_client.py

Fixes recent CI failure: https://ci.ros2.org/job/ci_linux/18542/testReport/junit/rclpy/flake8/C419____test_test_parameter_client_py_149_20_/
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18550)](http://ci.ros2.org/job/ci_linux/18550/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13094)](http://ci.ros2.org/job/ci_linux-aarch64/13094/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19284)](http://ci.ros2.org/job/ci_windows/19284/)

Fix unnecessary list comprehension flake8

---

rclpy/rclpy/action/server.py

replace https://github.com/ros2/rclpy/pull/1070.
This PR addresses the following two issues.
1. memory leak. It should call destroy() before removing `ServerGoalHandle`. (original issue https://answers.ros.org/question/411394/rclpy-action-server-seems-slowing-down-and-consuming-memory-in-long-term/)
2. `ActionServer` should own the `result_future`, but `ServerGoalHandle`. (see https://github.com/ros2/rclpy/pull/1070#discussion_r1080592437) 
@otamachan i borrowed your code from https://github.com/ros2/rclpy/pull/1070, so added you as Co-Author.

ServerGoalHandle should be destroyed before removing.

---

rclpy/CMakeLists.txt
rclpy/rclpy/__init__.py
rclpy/rclpy/logging.py
rclpy/rclpy/logging_service.py
rclpy/rclpy/node.py
rclpy/src/rclpy/_rclpy_logging.cpp
rclpy/test/test_logging_service.py

Address ros2/ros2#1355
Depend on ros2/rcl_interfaces#154
The commit `Add the lock for get/set logger` (423b47114886e732fac612c0b3a339af7b4a3dc6) can be reverted after ros2/rcutils#397 is implemented.

Logging service support

---

rclpy/rclpy/node.py

Fixes this typing issue:
```
Argument of type "None" cannot be assigned to parameter "parameter_overrides" of type "List[Parameter]" in function "__init__"
Type "None" cannot be assigned to type "List[Parameter]"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

Fix typing in Node init args

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

Similar to #1117, but for `rclpy.executors.Executor`.

Turn Executor into a ContextManager

---

rclpy/CMakeLists.txt
rclpy/rclpy/topic_endpoint_info.py
rclpy/rclpy/type_hash.py
rclpy/src/rclpy/utils.cpp
rclpy/src/rclpy/utils.hpp
rclpy/test/test_topic_endpoint_info.py
rclpy/test/test_type_hash.py

Part of https://github.com/ros2/ros2/issues/1159
Features
- Adds the `TypeHash` class
- Adds the type hash to the `TopicEndpointInfo` class
This will print the type hash when printing out verbose topic information with `rostopic info --verbose`. Note that without the `--no-daemon` flag, https://github.com/ros2/ros2cli/pull/816 is required which adds xmlrpc marshalling support for the new `rclpy.type_hash.TypeHash` class

Include type hash in topic endpoint info (rep2011)

---

rclpy/rclpy/node.py
rclpy/rclpy/timer.py
rclpy/src/rclpy/timer.cpp
rclpy/src/rclpy/timer.hpp
rclpy/test/test_timer.py
rclpy/test/test_waitable.py

This was possible in the past by creating a timer
and then immediately canceling it.  But that could lead to a potential race where the timer fired once before it was canceled.  By allowing for the user
to create it paused, we avoid that race.
This is the rclpy version of https://github.com/ros2/rclcpp/pull/2005
@Voldivh @fujitatomoya FYI.  This fixes #1137

Add in the ability to start timers paused.

---

rclpy/CMakeLists.txt
rclpy/rclpy/node.py
rclpy/rclpy/type_description_service.py
rclpy/src/rclpy/_rclpy_pybind11.cpp
rclpy/src/rclpy/type_description_service.cpp
rclpy/src/rclpy/type_description_service.hpp
rclpy/test/test_node.py

Part of ros2/ros2#1159
Depends on https://github.com/ros2/rcl/pull/1052
Equivalent to https://github.com/ros2/rclcpp/pull/2224
Defines and implements a new component of `rclpy.Node` that initializes and handles requests for the `~/get_type_description` service.

GetTypeDescription service

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

This makes it match the function name much more closely. While we are in here, also fix a bug where the multi-threaded version would not quit immediately after the future completes. And also add tests for both of these situations.
This should fix #989

Fix spin_once_until_future_complete to quit when the future finishes.

---

rclpy/test/test_node.py

These tests weren't always properly cleaning up after themselves, and were sometimes improperly using the setUp{Class} fixtures.  They also didn't always clean up between tests, so sometimes the same node was reused over and over again.  Clean all that up here, which should make the tests much more robust.

Cleanup of test_node.py.

---

rclpy/rclpy/node.py
rclpy/test/test_node.py

This addresses the issue (https://github.com/ros2/rclpy/issues/1097) by implementing the functionality for list_parameters that the node owns. 
This feature should help with logging and debugging by allowing users to easily retrieve all declared parameters and their values, similar to the functionality in ROS1.

add list_parameters & test

---

rclpy/rclpy/wait_for_message.py

Closes https://github.com/ros2/rclpy/issues/1169. As mentioned there, this is much easier to fix than it is to reproduce and regress test.

Handle take failure in `wait_for_message`

---

rclpy/src/rclpy/signal_handler.cpp

@clalancette minor fix, could you review this?

unregister_sigterm_signal_handler should be called.

---

rclpy/rclpy/node.py
rclpy/src/rclpy/node.cpp
rclpy/src/rclpy/node.hpp
rclpy/test/test_node.py

this PR is for service counts using it's name like topic.
Related to https://github.com/ros2/ros2cli/pull/771
Signed-off-by: leeminju531 <dlalswn531@naver.com>

Add count services, clients & test

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

Address #1159
The solution was mentioned at https://github.com/ros2/rclpy/issues/1159#issuecomment-1709622820. But I optimized code to avoid changing wait_for_ready_callbacks().

Use timeout object to avoid callback losing in wait_for_ready_callbacks

---

rclpy/src/rclpy/type_description_service.cpp

In https://github.com/ros2/rcl/pull/1112, the API is updated to populate the service structure, rather than `init`, `get`, and `fini`.  This updates rclpy to use the new API pattern.

Adjust python usage of the type_description service API

---

rclpy/rclpy/impl/rcutils_logger.py
rclpy/src/rclpy/_rclpy_logging.cpp
rclpy/test/test_rosout_subscription.py

align with https://github.com/ros2/rcl/pull/1115

aligh with rcl that a rosout publisher of a node might not exist

---

rclpy/rclpy/client.py
rclpy/test/test_client.py

Add an optional timeout_sec input so that the `call()` function can break away from the deadlock if RMW fails to response. The `call()` function returns future.result() which is `None`.
Another approach of adding timeout to the future returned by `call_async()` is much more difficult to implement, requiring changes from the `Future` class and upward. Also there is no timeout input for the rclcpp version of `async_send_request()`. So I would prefer not taking this approach instead.

Add an optional timeout_sec input to Client.call() to fix issue https://github.com/ros2/rclpy/issues/1181

---

rclpy/rclpy/publisher.py
rclpy/rclpy/subscription.py

The constructors for publisher.py and subscription.py have warnings in their doc-string that they should not be used directly to create Publisher or Subscription objects (see [API documentation](https://docs.ros2.org/latest/api/rclpy/api/topics.html)), but that the `create_publisher` or `create_subscription` methods from a node should be called instead. I believe the same warning applies to the `destroy()` method for these classes, and that `destroy_publisher` / `destroy_subscription` should be called from a node instead of calling `destroy()` on these objects directly, so I've added a warning to the doc-string for these `destroy()` methods.

Add doc-string warnings for destroy() methods

---

rclpy/test/test_qos.py

They aren't needed, and this fixes a warning on newer versions of flake8.

Remove parentheses from assert statements.

---

rclpy/rclpy/logging_service.py
rclpy/test/test_logging_service.py

Added static typing to logging_service.py. This change was already done similarly in https://github.com/ros2/rclpy/pull/979 in response to issue https://github.com/ros2/rclpy/issues/976.  Also fixes a spelling error of Invaild -> Invalid.

Add types to logging_service.py

---

rclpy/rclpy/topic_or_service_is_hidden.py

Added static typing to  topic_or_service_is_hidden.py. This change was already done similarly in https://github.com/ros2/rclpy/pull/979 in response to issue https://github.com/ros2/rclpy/issues/976.

Add types to topic_or_service_is_hidden.py

---

rclpy/rclpy/duration.py
rclpy/rclpy/logging_service.py
rclpy/test/test_logging_service.py

Adds types to duration.py. Also adds an RCLDuration Type/Object Alias so type inference can be on the _duration_handle.

Add types to duration.py

---

rclpy/rclpy/type_hash.py

Adds static typing to type_hash.py. In the constructor I switch away from `**kwargs` to explicit variable names. If there is some reason the `**kwargs` is preferred for now I can use Any. Just let me know so I can add a TODO to use Unpack[] when python 3.12 is supported. Or I suppose I could use typing_extensions package to use Unpack on older versions of python.

Add types to TypeHash and moved away from __slots__ usage

---

rclpy/rclpy/type_hash.py

Reverts ros2/rclpy#1232
This is causing problems in CI: https://ci.ros2.org/job/ci_linux/20452/testReport/junit/ros2cli.ros2cli.test/test_daemon/test_get_subscriptions_info_by_topic/
In particular, it isn't clear to me why we removed the `__slots__` (as that is a performance enhancement), and it is also causing downstream packages to fail.

Revert "Add types to TypeHash and moved away from __slots__ usage"

---

rclpy/rclpy/type_hash.py
rclpy/test/test_type_hash.py

Following the regression caused by #1232 this adds back the `__slots__` Also adds a test case to ensure this gets caught by CI in the future. Should probably wait until the revert in #1243 is completed.

Add back Type hash __slots__ and add test cases.

---

rclpy/rclpy/parameter.py
rclpy/test/test_logging_rosout.py

It doesn't like to compare types with ==, so switch to isinstance as appropriate.

Small fixes for modern flake8.

---

rclpy/rclpy/wait_for_message.py
rclpy/test/test_wait_for_message.py

This function didn't work for transient local publishers.
This is a breaking change because the argument order is changed. However with the future in mind, this order makes most sense to me as all first arguments are passed directly to the subscription.
If you like the original order I can change this.

Allow specifying qos

---

rclpy/rclpy/node.py

Newer versions of flake8 complain that using 'str' as a variable shadows a builtin.  Just make it 's'.

Fix small flake8 error in rclpy.

---

rclpy/rclpy/lifecycle/publisher.py
rclpy/rclpy/node.py
rclpy/rclpy/publisher.py
rclpy/rclpy/serialization.py
rclpy/rclpy/subscription.py
rclpy/rclpy/type_support.py

Using Generics for messages

---

rclpy/rclpy/node.py
rclpy/test/test_node.py

Same as [c3af8a](https://github.com/ros2/rclpy/commit/c3af8a72fa1f81e5dcd384a9d2912ea244950cfb) , but for `humble`.

Fix incorrect comparsion on whether parameter type is NOT_SET (#1032)

---

rclpy/rclpy/publisher.py

The main reason to do this is so that we can change example code to use context managers for managing the lifetimes of publishers (and other entities), which should make the code significantly easier to read.

Make publishers context-manager aware.

---

rclpy/rclpy/node.py
rclpy/test/test_node.py
rclpy/test/test_publisher.py
rclpy/test/test_subscription.py

This way it is much easier to create examples that properly clean up after themselves.
This partially fixes #1280, but we'll need more PRs to fully complete that.

Make nodes context-manager aware.

---

rclpy/rclpy/client.py
rclpy/test/test_client.py

This way it is much easier to create examples that properly clean up after themselves.
This partially solves #1280 , though we'll need further PRs to complete it.

Make service clients context-aware.

---

rclpy/rclpy/timer.py
rclpy/test/test_timer.py

This should make it easier to create examples and demos that properly clean up after themselves.
This partially solves #1280 , though we'll need additional PRs to complete it.

Make timers context-aware.

---

rclpy/rclpy/action/server.py

Fix bug in Humble reported here: https://github.com/ros2/rclpy/pull/982#issuecomment-2145899244
I decided not to backport #982 to avoid the new sublogger affecting someone's filtering of the log messages in Humble. I checked and this bug does not affect Iron.

[Humble] Fix AttributeError _logger in Action Server

---

rclpy/CMakeLists.txt
rclpy/rclpy/wait_for_message.py
rclpy/test/test_wait_for_message.py

This is the backport of the following PRs. (conflicts are resolved already)
- https://github.com/ros2/rclpy/pull/960
- https://github.com/ros2/rclpy/pull/1180
backport is originally requested here, https://github.com/ros2/rclpy/issues/1179
note, this is purely adding a new method, this does not break API nor user application behavior.

Support wait for message backport humble

---

rclpy/rclpy/node.py

Added `Optional` types to function declarations in `node.py` where relevant on the `humble` branch. Missing `Optional` types cause static type checking failures. Example:
```
class ExampleNode(Node):
def __init__(self, cbg: Optional[CallbackGroup] = None) -> None:
super().__init__("example_node")
self.timer = self.create_timer(
0.001,
self.timer_callback,
callback_group=cbg,  # fails static type checking - this field wasn't annotated as Optional[CallbackGroup]
)
```

Add missing `Optional` types to `node.py` on `humble` branch

---

rclpy/rclpy/executors.py
rclpy/test/test_executor.py

address https://github.com/ros2/rclpy/issues/1303

Executor executes the tasks in FIFO order.

---

rclpy/rclpy/__init__.py

That is, if you call rclpy.init as a context manager within the same process, and using the default context, it currently fails.  That is because you cannot reinitialize (call init) on a Context object once it has been shutdown.  Instead, force try_shutdown to replace the global context object with a new one on rclpy.init shutdown by passing a None.
This should fix some failing tests on the repeated jobs, like https://ci.ros2.org/view/nightly/job/nightly_linux_repeated/3516/testReport/junit/test_launch_ros.test.test_launch_ros.actions/test_ros_timer/test_timer_uses_sim_time_2_3_/
@Crola1702 FYI

Fix a bug when using multiple rclpy.init context managers.

---

rclpy/CMakeLists.txt
rclpy/src/rclpy/lifecycle.cpp
rclpy/test/test_lifecycle.py

We were fetching one more lifecycle transition than existed in the source list (i.e. we should use < instead of <=).
In turn, this allows us to enable the test_lifecycle.py test, and to fix the spurious "empty" string in the expected states.
This supersedes #1318.  @fujitatomoya FYI.

Fix a bad bug in fetching the lifecycle transitions.

---

rclpy/rclpy/__init__.py

This bug was found by @Yadunund, who also noticed [rclcpp initializes the context before installing the signal handlers]( https://github.com/ros2/rclcpp/blob/2739327ee9af0256c7edcbccb810513af0018851/rclcpp/src/rclcpp/utilities.cpp#L41-L43).
The only thing the rclcpp and rclpy signal handlers do is [notify another thread that the signal was received](https://github.com/ros2/rclpy/blob/ee79763648858bffa2a84b76e092fe0b20504aa8/rclpy/src/rclpy/signal_handler.cpp#L311). That thread [loops through the initialized contexts and shuts them down](https://github.com/ros2/rclpy/blob/ee79763648858bffa2a84b76e092fe0b20504aa8/rclpy/src/rclpy/signal_handler.cpp#L141-L144). Nothing happens if there are no initialized contexts.

Install signal handlers after context is initialized

---

rclpy/rclpy/client.py
rclpy/rclpy/node.py
rclpy/rclpy/service.py
rclpy/rclpy/type_support.py

Building off of https://github.com/ros2/rclpy/pull/1275 and #1254, Uses the new Futures inside client.py and update srv_type to be `Type[Srv[...]]` rather than `Srv[...]`.

Minor Typing Updates to Service/Client

---

rclpy/rclpy/event_handler.py
rclpy/rclpy/node.py
rclpy/rclpy/subscription.py

Adds types to Subscriptions. Also fixes previously incorrect callback type. Same as #1239. It needs https://github.com/ros2/rosidl_python/pull/205 or all of the generics are treated as `Any`.

Subscription types

---

rclpy/rclpy/publisher.py

#1255 changed `DurationType` to `DurationHandle`, but  #1310 still referred to `DurationType`. That caused [the rclpy dev job to fail](https://build.ros2.org/job/Rdev__rclpy__ubuntu_noble_amd64/42/testReport/junit/(root)/projectroot/test_action_client/) after both were merged. Running CI on both those PRs in parallel hid the incompatibility.

Import DurationHandle not DurationType

---

rclpy/rclpy/time.py

Using an `@overload`  to make type more narrow.

Fix Time subtraction typing

---

rclpy/rclpy/impl/_rclpy_pybind11.pyi
rclpy/rclpy/impl/implementation_singleton.pyi
rclpy/rclpy/utilities.py

Currently using `rclpyHandle` to mock the pybind implementation has cause some weirdness when dealing with type annotations. A better and more scalable solutions is replacing it with custom type stubs. One day in the future I would love to use stubgen to automatically generate stubs however it is still missing many features for example generics, TypeDicts, etc. Pybind has made progress in the recent years with function type annotations it however still needs work. This would also allow us to move the Various `Handle` Protocols into type stubs which is probably a better long term plan.

Replace rclpyHandle with type stubs

---

rclpy/rclpy/action/client.py
rclpy/rclpy/action/server.py
rclpy/rclpy/client.py
rclpy/rclpy/impl/_rclpy_pybind11.pyi
rclpy/rclpy/impl/implementation_singleton.pyi
rclpy/rclpy/node.py
rclpy/rclpy/service.py
rclpy/rclpy/type_support.py
rclpy/rclpy/waitable.py
rclpy/src/rclpy/action_server.cpp

This reverts commit d1d7d0540ca9769e98dd11cf5d52622d9e0b2ace.
Depends on https://github.com/ros2/rclpy/pull/1360

Revert "Add types to Action Server and Action Client (#1349)"

---

rclpy/test/test_client.py

closes https://github.com/ros2/rclpy/issues/1347
note: backport all distros.

TestClient.test_service_timestamps failing consistently.

---

rclpy/CMakeLists.txt
rclpy/package.xml

Also add in hints so that we find the unversioned python3 before finding versioned ones.
This must be merged before https://github.com/ros2/ros2/pull/1524 ; see that pull request for more information about this change.

Remove python_cmake_module use

---

rclpy/rclpy/action/server.py

closes https://github.com/ros2/rclpy/issues/1236

adjust debug message that requested goal is already expired.

---

rclpy/test/test_qos.py
rclpy/test/test_qos_event.py

Clean qos zenoh tests.
Related to https://github.com/ros2/rmw_zenoh/issues/286

Clean qos zenoh tests

---

rclpy/src/rclpy/context.cpp
rclpy/src/rclpy/context.hpp
rclpy/src/rclpy/exceptions.hpp

Fix the race condition while calling rcl_shutdown

---

rclpy/package.xml

We need this because we call find_package(Python3 Development) in our CMakeLists.txt here.
Also see https://github.com/ros2/ros2_tracing/pull/146#issuecomment-2492724725 for a long explanation of why we need this.

Add in python3-dev build dependency.

---

rclpy/rclpy/client.py
rclpy/test/test_client.py

follow-up of https://github.com/ros2/rclpy/pull/1188 (https://github.com/ros2/rclpy/pull/1188#issuecomment-2052469167)

Client:call generates TimeoutError exception when it is timed out.

---

rclpy/rclpy/lifecycle/node.py
rclpy/test/test_lifecycle.py

addresses https://github.com/ros2/rclpy/issues/1209
replaces https://github.com/ros2/rclpy/pull/1317

avoid lifecycle node transition exception

---

rclpy/rclpy/executors.py
rclpy/rclpy/task.py
rclpy/test/test_executor.py
rclpy/test/test_task.py

closes https://github.com/ros2/rclpy/issues/1099

Check if Task(Future) is canceled.

---

rclpy/rclpy/__init__.py
rclpy/rclpy/impl/_rclpy_pybind11.pyi
rclpy/rclpy/node.py
rclpy/rclpy/qos.py
rclpy/src/rclpy/node.cpp
rclpy/src/rclpy/node.hpp
rclpy/src/rclpy/qos.cpp
rclpy/test/test_create_node.py

closes https://github.com/ros2/rclpy/issues/1368
depends on https://github.com/ros2/rmw/pull/381

add QoS Profile/Depth support to Node.

---

rclpy/rclpy/action/server.py

address https://github.com/ros2/rclpy/issues/1072

publish action goal status once accepted before execution.

---

rclpy/CMakeLists.txt

When the module is compiled with `MODULE` (the default), the proper linker flags are added on macOS (specifically `-undefined dynamic_lookup`). Otherwise, `rclpy` segfaults when linked on conda. 
Is the `SHARED` really necessary? The `pybind11` documentation says:
> Specifying `SHARED` will create a more traditional dynamic library which can also be linked from elsewhere. 
Is anyone linking against this library as a "traditional dynamic library"?

Remove `SHARED` from `pybind11_add_module`

---

rclpy/rclpy/parameter.py
rclpy/rclpy/parameter_client.py
rclpy/test/test_parameter.py
rclpy/test/test_parameter_client.py

address https://github.com/ros2/ros2cli/issues/863
in this PR, it tries to address a few things as following.
- `parameter_dict_from_yaml_file` do not use temporary list, it now parses parameter yaml file and directly stores the contents in the dictionary.
- `parameter_dict_from_yaml_file` is now capable of parsing the yaml file with multiple keys with `namespace` and `base nodename`.
- `load_parameter_file` of Parameter Client should specifies the target node to parse the parameter yaml file. this should be done to avoid the original problem reported address https://github.com/ros2/ros2cli/issues/863
- add more unit tests to `parameter_dict_from_yaml_file` accordingly.

fix loading parameter behavior from yaml file.
